/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn genann_init(
        inputs: ::core::ffi::c_int,
        hidden_layers: ::core::ffi::c_int,
        hidden: ::core::ffi::c_int,
        outputs: ::core::ffi::c_int,
    ) -> *mut genann;
}
unsafe extern "C" {
    pub fn genann_read(in_: *mut FILE) -> *mut genann;
}
unsafe extern "C" {
    pub fn genann_randomize(ann: *mut genann);
}
unsafe extern "C" {
    pub fn genann_copy(ann: *const genann) -> *mut genann;
}
unsafe extern "C" {
    pub fn genann_free(ann: *mut genann);
}
unsafe extern "C" {
    pub fn genann_run(ann: *const genann, inputs: *const f64) -> *const f64;
}
unsafe extern "C" {
    pub fn genann_train(
        ann: *const genann,
        inputs: *const f64,
        desired_outputs: *const f64,
        learning_rate: f64,
    );
}
unsafe extern "C" {
    pub fn genann_write(ann: *const genann, out: *mut FILE);
}
unsafe extern "C" {
    pub fn genann_act_sigmoid(a: f64) -> f64;
}
unsafe extern "C" {
    pub fn genann_act_sigmoid_cached(a: f64) -> f64;
}
unsafe extern "C" {
    pub fn genann_act_threshold(a: f64) -> f64;
}
unsafe extern "C" {
    pub fn genann_act_linear(a: f64) -> f64;
}
