/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DevHostServiceConstruct(service: *mut DevHostService);
}
unsafe extern "C" {
    pub fn DevHostServiceDestruct(service: *mut DevHostService);
}
unsafe extern "C" {
    pub fn DevHostServiceAddDevice(
        inst: *mut IDevHostService,
        deviceInfo: *const HdfDeviceInfo,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevHostServiceDelDevice(
        inst: *mut IDevHostService,
        devId: devid_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevHostServiceNewInstance(
        hostId: u16,
        hostName: *const ::core::ffi::c_char,
    ) -> *mut IDevHostService;
}
unsafe extern "C" {
    pub fn DevHostServiceFreeInstance(service: *mut IDevHostService);
}
unsafe extern "C" {
    pub fn DevHostServiceCreate() -> *mut HdfObject;
}
unsafe extern "C" {
    pub fn DevHostServiceRelease(object: *mut HdfObject);
}
