/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DevmgrServiceClntGetInstance() -> *mut DevmgrServiceClnt;
}
unsafe extern "C" {
    pub fn DevmgrServiceClntFreeInstance(inst: *mut DevmgrServiceClnt);
}
unsafe extern "C" {
    pub fn DevmgrServiceClntAttachDevice(deviceToken: *mut IHdfDeviceToken) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevmgrServiceClntDetachDevice(devid: devid_t) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevmgrServiceClntAttachDeviceHost(
        hostId: u16,
        hostService: *mut IDevHostService,
    ) -> ::core::ffi::c_int;
}
