/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DevSvcManagerClntGetService(svcName: *const ::core::ffi::c_char) -> *const HdfObject;
}
unsafe extern "C" {
    pub fn DevSvcManagerClntGetInstance() -> *mut DevSvcManagerClnt;
}
unsafe extern "C" {
    pub fn DevSvcManagerClntGetDeviceObject(
        svcName: *const ::core::ffi::c_char,
    ) -> *mut HdfDeviceObject;
}
unsafe extern "C" {
    pub fn DevSvcManagerClntAddService(
        service: *mut HdfDeviceObject,
        servinfo: *const HdfServiceInfo,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerClntUpdateService(
        service: *mut HdfDeviceObject,
        servinfo: *const HdfServiceInfo,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerClntRemoveService(svcName: *const ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn DevSvcManagerClntSubscribeService(
        svcName: *const ::core::ffi::c_char,
        callback: SubscriberCallback,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerClntUnsubscribeService(
        svcName: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerClntFreeInstance(instance: *mut DevSvcManagerClnt);
}
