/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn HdfDeviceTokenCreate() -> *mut HdfObject;
}
unsafe extern "C" {
    pub fn HdfDeviceTokenRelease(object: *mut HdfObject);
}
unsafe extern "C" {
    pub fn HdfDeviceTokenNewInstance() -> *mut IHdfDeviceToken;
}
unsafe extern "C" {
    pub fn HdfDeviceTokenFreeInstance(token: *mut IHdfDeviceToken);
}
