/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn HdfDeviceDetach(
        devInst: *mut IHdfDevice,
        devNode: *mut HdfDeviceNode,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn HdfDeviceConstruct(device: *mut HdfDevice);
}
unsafe extern "C" {
    pub fn HdfDeviceDestruct(device: *mut HdfDevice);
}
unsafe extern "C" {
    pub fn HdfDeviceCreate() -> *mut HdfObject;
}
unsafe extern "C" {
    pub fn HdfDeviceRelease(object: *mut HdfObject);
}
unsafe extern "C" {
    pub fn HdfDeviceNewInstance() -> *mut HdfDevice;
}
unsafe extern "C" {
    pub fn HdfDeviceFreeInstance(device: *mut HdfDevice);
}
