/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn HdfServiceObserverRecordObtain(serviceKey: u32) -> *mut HdfServiceObserverRecord;
}
unsafe extern "C" {
    pub fn HdfServiceObserverRecordRecycle(observerRecord: *mut HdfServiceObserverRecord);
}
unsafe extern "C" {
    pub fn HdfServiceObserverRecordCompare(listEntry: *mut HdfSListNode, serviceKey: u32) -> bool;
}
unsafe extern "C" {
    pub fn HdfServiceObserverRecordNotifySubscribers(
        record: *mut HdfServiceObserverRecord,
        deviceId: devid_t,
        policy: u16,
    );
}
unsafe extern "C" {
    pub fn HdfServiceObserverRecordDelete(listEntry: *mut HdfSListNode);
}
