/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn HdfServiceObserverConstruct(observer: *mut HdfServiceObserver) -> bool;
}
unsafe extern "C" {
    pub fn HdfServiceObserverDestruct(observer: *mut HdfServiceObserver);
}
unsafe extern "C" {
    pub fn HdfServiceObserverPublishService(
        observer: *mut HdfServiceObserver,
        svcName: *const ::core::ffi::c_char,
        deviceId: devid_t,
        policy: u16,
        service: *mut HdfObject,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn HdfServiceObserverSubscribeService(
        observer: *mut HdfServiceObserver,
        svcName: *const ::core::ffi::c_char,
        deviceId: devid_t,
        callback: SubscriberCallback,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn HdfServiceObserverRemoveRecord(
        observer: *mut HdfServiceObserver,
        svcName: *const ::core::ffi::c_char,
    );
}
