/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub static mut g_audioSapmCompNameList: [*mut ::core::ffi::c_char; 100usize];
}
unsafe extern "C" {
    pub static mut g_audioSapmCfgNameList: [*mut ::core::ffi::c_char; 100usize];
}
unsafe extern "C" {
    pub static mut g_audioCodecControlsList: [*mut ::core::ffi::c_char; 100usize];
}
