/* automatically generated by rust-bindgen 0.72.1 */

pub const PERIOD_COUNT: i32 = 4;
pub const RENDER_TRAF_BUF_SIZE: i32 = 1024;
pub const TIME_OUT_CONST: i32 = 50;
pub const SLEEP_TIME: i32 = 5;
pub const MIN_PERIOD_SILENCE_THRESHOLD: i32 = 4096;
pub const MAX_PERIOD_SILENCE_THRESHOLD: i32 = 16384;
