/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn GetDevUdid(
        udid: *mut ::core::ffi::c_char,
        size: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
