/* automatically generated by rust-bindgen 0.72.1 */

pub type size_t = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn calloc(arg1: size_t, arg2: size_t) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn free(arg1: *mut ::core::ffi::c_void);
}
pub type mbedtls_mpi_uint = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_mpi {
    pub private_p: *mut mbedtls_mpi_uint,
    pub private_s: ::core::ffi::c_short,
    pub private_n: ::core::ffi::c_ushort,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_asn1_buf {
    pub tag: ::core::ffi::c_int,
    pub len: size_t,
    pub p: *mut ::core::ffi::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_asn1_sequence {
    pub buf: mbedtls_asn1_buf,
    pub next: *mut mbedtls_asn1_sequence,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_asn1_named_data {
    pub oid: mbedtls_asn1_buf,
    pub val: mbedtls_asn1_buf,
    pub next: *mut mbedtls_asn1_named_data,
    pub private_next_merged: ::core::ffi::c_uchar,
}
unsafe extern "C" {
    pub fn mbedtls_asn1_get_tag(
        p: *mut *mut ::core::ffi::c_uchar,
        end: *const ::core::ffi::c_uchar,
        len: *mut size_t,
        tag: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_asn1_get_int(
        p: *mut *mut ::core::ffi::c_uchar,
        end: *const ::core::ffi::c_uchar,
        val: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_asn1_get_alg(
        p: *mut *mut ::core::ffi::c_uchar,
        end: *const ::core::ffi::c_uchar,
        alg: *mut mbedtls_asn1_buf,
        params: *mut mbedtls_asn1_buf,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_asn1_get_alg_null(
        p: *mut *mut ::core::ffi::c_uchar,
        end: *const ::core::ffi::c_uchar,
        alg: *mut mbedtls_asn1_buf,
    ) -> ::core::ffi::c_int;
}
pub const MBEDTLS_MD_NONE: mbedtls_md_type_t = 0;
pub const MBEDTLS_MD_MD5: mbedtls_md_type_t = 1;
pub const MBEDTLS_MD_RIPEMD160: mbedtls_md_type_t = 4;
pub const MBEDTLS_MD_SHA1: mbedtls_md_type_t = 5;
pub const MBEDTLS_MD_SHA224: mbedtls_md_type_t = 8;
pub const MBEDTLS_MD_SHA256: mbedtls_md_type_t = 9;
pub const MBEDTLS_MD_SHA384: mbedtls_md_type_t = 10;
pub const MBEDTLS_MD_SHA512: mbedtls_md_type_t = 11;
pub const MBEDTLS_MD_SHA3_224: mbedtls_md_type_t = 16;
pub const MBEDTLS_MD_SHA3_256: mbedtls_md_type_t = 17;
pub const MBEDTLS_MD_SHA3_384: mbedtls_md_type_t = 18;
pub const MBEDTLS_MD_SHA3_512: mbedtls_md_type_t = 19;
pub type mbedtls_md_type_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_rsa_context {
    pub private_ver: ::core::ffi::c_int,
    pub private_len: size_t,
    pub private_N: mbedtls_mpi,
    pub private_E: mbedtls_mpi,
    pub private_D: mbedtls_mpi,
    pub private_P: mbedtls_mpi,
    pub private_Q: mbedtls_mpi,
    pub private_DP: mbedtls_mpi,
    pub private_DQ: mbedtls_mpi,
    pub private_QP: mbedtls_mpi,
    pub private_RN: mbedtls_mpi,
    pub private_RP: mbedtls_mpi,
    pub private_RQ: mbedtls_mpi,
    pub private_Vi: mbedtls_mpi,
    pub private_Vf: mbedtls_mpi,
    pub private_padding: ::core::ffi::c_int,
    pub private_hash_id: ::core::ffi::c_int,
}
unsafe extern "C" {
    pub fn mbedtls_rsa_set_padding(
        ctx: *mut mbedtls_rsa_context,
        padding: ::core::ffi::c_int,
        hash_id: mbedtls_md_type_t,
    ) -> ::core::ffi::c_int;
}
pub const MBEDTLS_PK_NONE: mbedtls_pk_type_t = 0;
pub const MBEDTLS_PK_RSA: mbedtls_pk_type_t = 1;
pub const MBEDTLS_PK_ECKEY: mbedtls_pk_type_t = 2;
pub const MBEDTLS_PK_ECKEY_DH: mbedtls_pk_type_t = 3;
pub const MBEDTLS_PK_ECDSA: mbedtls_pk_type_t = 4;
pub const MBEDTLS_PK_RSA_ALT: mbedtls_pk_type_t = 5;
pub const MBEDTLS_PK_RSASSA_PSS: mbedtls_pk_type_t = 6;
pub const MBEDTLS_PK_OPAQUE: mbedtls_pk_type_t = 7;
pub type mbedtls_pk_type_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_pk_info_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_pk_context {
    pub private_pk_info: *const mbedtls_pk_info_t,
    pub private_pk_ctx: *mut ::core::ffi::c_void,
}
unsafe extern "C" {
    pub fn mbedtls_pk_verify(
        ctx: *mut mbedtls_pk_context,
        md_alg: mbedtls_md_type_t,
        hash: *const ::core::ffi::c_uchar,
        hash_len: size_t,
        sig: *const ::core::ffi::c_uchar,
        sig_len: size_t,
    ) -> ::core::ffi::c_int;
}
pub type mbedtls_x509_buf = mbedtls_asn1_buf;
pub type mbedtls_x509_name = mbedtls_asn1_named_data;
pub type mbedtls_x509_sequence = mbedtls_asn1_sequence;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_x509_authority {
    pub keyIdentifier: mbedtls_x509_buf,
    pub authorityCertIssuer: mbedtls_x509_sequence,
    pub authorityCertSerialNumber: mbedtls_x509_buf,
    pub raw: mbedtls_x509_buf,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_x509_time {
    pub year: ::core::ffi::c_int,
    pub mon: ::core::ffi::c_int,
    pub day: ::core::ffi::c_int,
    pub hour: ::core::ffi::c_int,
    pub min: ::core::ffi::c_int,
    pub sec: ::core::ffi::c_int,
}
unsafe extern "C" {
    pub fn mbedtls_x509_dn_gets(
        buf: *mut ::core::ffi::c_char,
        size: size_t,
        dn: *const mbedtls_x509_name,
    ) -> ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_x509_crl_entry {
    pub raw: mbedtls_x509_buf,
    pub serial: mbedtls_x509_buf,
    pub revocation_date: mbedtls_x509_time,
    pub entry_ext: mbedtls_x509_buf,
    pub next: *mut mbedtls_x509_crl_entry,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_x509_crl {
    pub raw: mbedtls_x509_buf,
    pub tbs: mbedtls_x509_buf,
    pub version: ::core::ffi::c_int,
    pub sig_oid: mbedtls_x509_buf,
    pub issuer_raw: mbedtls_x509_buf,
    pub issuer: mbedtls_x509_name,
    pub this_update: mbedtls_x509_time,
    pub next_update: mbedtls_x509_time,
    pub entry: mbedtls_x509_crl_entry,
    pub crl_ext: mbedtls_x509_buf,
    pub private_sig_oid2: mbedtls_x509_buf,
    pub private_sig: mbedtls_x509_buf,
    pub private_sig_md: mbedtls_md_type_t,
    pub private_sig_pk: mbedtls_pk_type_t,
    pub private_sig_opts: *mut ::core::ffi::c_void,
    pub next: *mut mbedtls_x509_crl,
}
unsafe extern "C" {
    pub fn mbedtls_x509_crl_parse(
        chain: *mut mbedtls_x509_crl,
        buf: *const ::core::ffi::c_uchar,
        buflen: size_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_x509_crl_init(crl: *mut mbedtls_x509_crl);
}
unsafe extern "C" {
    pub fn mbedtls_x509_crl_free(crl: *mut mbedtls_x509_crl);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_x509_crt {
    pub private_own_buffer: ::core::ffi::c_int,
    pub raw: mbedtls_x509_buf,
    pub tbs: mbedtls_x509_buf,
    pub version: ::core::ffi::c_int,
    pub serial: mbedtls_x509_buf,
    pub sig_oid: mbedtls_x509_buf,
    pub issuer_raw: mbedtls_x509_buf,
    pub subject_raw: mbedtls_x509_buf,
    pub issuer: mbedtls_x509_name,
    pub subject: mbedtls_x509_name,
    pub valid_from: mbedtls_x509_time,
    pub valid_to: mbedtls_x509_time,
    pub pk_raw: mbedtls_x509_buf,
    pub pk: mbedtls_pk_context,
    pub issuer_id: mbedtls_x509_buf,
    pub subject_id: mbedtls_x509_buf,
    pub v3_ext: mbedtls_x509_buf,
    pub subject_alt_names: mbedtls_x509_sequence,
    pub subject_key_id: mbedtls_x509_buf,
    pub authority_key_id: mbedtls_x509_authority,
    pub certificate_policies: mbedtls_x509_sequence,
    pub private_ext_types: ::core::ffi::c_int,
    pub private_ca_istrue: ::core::ffi::c_int,
    pub private_max_pathlen: ::core::ffi::c_int,
    pub private_key_usage: ::core::ffi::c_uint,
    pub ext_key_usage: mbedtls_x509_sequence,
    pub private_ns_cert_type: ::core::ffi::c_uchar,
    pub private_sig: mbedtls_x509_buf,
    pub private_sig_md: mbedtls_md_type_t,
    pub private_sig_pk: mbedtls_pk_type_t,
    pub private_sig_opts: *mut ::core::ffi::c_void,
    pub next: *mut mbedtls_x509_crt,
}
unsafe extern "C" {
    pub fn mbedtls_x509_crt_parse(
        chain: *mut mbedtls_x509_crt,
        buf: *const ::core::ffi::c_uchar,
        buflen: size_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_x509_crt_verify_info(
        buf: *mut ::core::ffi::c_char,
        size: size_t,
        prefix: *const ::core::ffi::c_char,
        flags: u32,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_x509_crt_verify(
        crt: *mut mbedtls_x509_crt,
        trust_ca: *mut mbedtls_x509_crt,
        ca_crl: *mut mbedtls_x509_crl,
        cn: *const ::core::ffi::c_char,
        flags: *mut u32,
        f_vrfy: ::core::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::core::ffi::c_void,
                arg2: *mut mbedtls_x509_crt,
                arg3: ::core::ffi::c_int,
                arg4: *mut u32,
            ) -> ::core::ffi::c_int,
        >,
        p_vrfy: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_x509_crt_init(crt: *mut mbedtls_x509_crt);
}
unsafe extern "C" {
    pub fn mbedtls_x509_crt_free(crt: *mut mbedtls_x509_crt);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_pem_context {
    pub private_buf: *mut ::core::ffi::c_uchar,
    pub private_buflen: size_t,
    pub private_info: *mut ::core::ffi::c_uchar,
}
unsafe extern "C" {
    pub fn mbedtls_pem_init(ctx: *mut mbedtls_pem_context);
}
unsafe extern "C" {
    pub fn mbedtls_pem_read_buffer(
        ctx: *mut mbedtls_pem_context,
        header: *const ::core::ffi::c_char,
        footer: *const ::core::ffi::c_char,
        data: *const ::core::ffi::c_uchar,
        pwd: *const ::core::ffi::c_uchar,
        pwdlen: size_t,
        use_len: *mut size_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_pem_free(ctx: *mut mbedtls_pem_context);
}
unsafe extern "C" {
    pub fn islower(arg1: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn isupper(arg1: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn memcmp(
        arg1: *const ::core::ffi::c_void,
        arg2: *const ::core::ffi::c_void,
        arg3: size_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn strstr(
        arg1: *const ::core::ffi::c_char,
        arg2: *const ::core::ffi::c_char,
    ) -> *mut ::core::ffi::c_char;
}
pub const LOG_TYPE_MIN: LogType = 0;
pub const LOG_INIT: LogType = 1;
pub const LOG_CORE: LogType = 3;
pub const LOG_TYPE_MAX: LogType = 4;
pub type LogType = ::core::ffi::c_uint;
pub const LOG_DEBUG: LogLevel = 3;
pub const LOG_INFO: LogLevel = 4;
pub const LOG_WARN: LogLevel = 5;
pub const LOG_ERROR: LogLevel = 6;
pub const LOG_FATAL: LogLevel = 7;
pub type LogLevel = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn HiLogPrint(
        type_: LogType,
        level: LogLevel,
        domain: ::core::ffi::c_uint,
        tag: *const ::core::ffi::c_char,
        fmt: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mbedtls_calloc(n: size_t, size: size_t) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn mbedtls_free(ptr: *mut ::core::ffi::c_void);
}
pub type errno_t = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn memset_s(
        dest: *mut ::core::ffi::c_void,
        destMax: size_t,
        c: ::core::ffi::c_int,
        count: size_t,
    ) -> errno_t;
}
unsafe extern "C" {
    pub fn strncpy_s(
        strDest: *mut ::core::ffi::c_char,
        destMax: size_t,
        strSrc: *const ::core::ffi::c_char,
        count: size_t,
    ) -> errno_t;
}
