//! Auto-generated types module (TU truth entry)
//!
//! - Source of truth: stage1 pinned preprocessed `.i` from tu_context_map.json
//! - Shared/global types are re-exported here (crate::types::*).
//! - Per-module private types live in each module's `local_types` submodule.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused)]

// ============================================================
// C2R: TU-pinned type supplements (from stage1 `.i` truth)
// ============================================================
pub mod __c2r_tu_types_src_osal_sysevent {
    include!("__c2r_generated/tu_types_src_osal_sysevent.rs");
}
pub use __c2r_tu_types_src_osal_sysevent::{DListHead, FILE, HdfDevEventlistener, HdfIoDispatcher, HdfIoService, HdfObject, HdfSBuf, HdfSysEvent, HdfSysEventNotifier, HdfSysEventNotifierFn, HdfSysEventNotifyNode, OnDevEventReceive, OnEventReceived, OsalMutex, _IO_FILE};


// ============================================================
// Auto-generated Defensive Opaque Types
// These types were found in function signatures or variable
// declarations but were not generated by bindgen.
// ============================================================

/// Opaque placeholder for external type `HdfIoServiceGroup`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoServiceGroup {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `HdfRemoteService`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfRemoteService {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `HdfSBufImpl`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBufImpl {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `char16_t`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct char16_t {
    _private: [u8; 0],
}

// ============================================================
// TU Truth Constants (from preprocessed translation units)
// ============================================================

pub const DEVICE_CLASS_AUDIO: i32 = 32;
pub const DEVICE_CLASS_CAMERA: i32 = 64;
pub const DEVICE_CLASS_DEFAULT: i32 = 1;
pub const DEVICE_CLASS_DISPLAY: i32 = 16;
pub const DEVICE_CLASS_HIMEDIACOMM: i32 = 512;
pub const DEVICE_CLASS_INPUT: i32 = 8;
pub const DEVICE_CLASS_MAX: i32 = 1024;
pub const DEVICE_CLASS_PLAT: i32 = 2;
pub const DEVICE_CLASS_SENSOR: i32 = 4;
pub const DEVICE_CLASS_USB: i32 = 128;
pub const DEVICE_CLASS_USERAUTH: i32 = 256;
pub const HDF_BSP_ERR_OP: i32 = -101;
pub const HDF_DEV_ERR_ATTACHDEV_FAIL: i32 = -206;
pub const HDF_DEV_ERR_DEV_INIT_FAIL: i32 = -204;
pub const HDF_DEV_ERR_NETDOWN: i32 = -211;
pub const HDF_DEV_ERR_NODATA: i32 = -207;
pub const HDF_DEV_ERR_NORANGE: i32 = -208;
pub const HDF_DEV_ERR_NO_DEVICE: i32 = -202;
pub const HDF_DEV_ERR_NO_DEVICE_SERVICE: i32 = -203;
pub const HDF_DEV_ERR_NO_MEMORY: i32 = -201;
pub const HDF_DEV_ERR_OP: i32 = -210;
pub const HDF_DEV_ERR_PUBLISH_FAIL: i32 = -205;
pub const HDF_ERR_BAD_FD: i32 = -18;
pub const HDF_ERR_BSP_PLT_API_ERR: i32 = -102;
pub const HDF_ERR_DEVICE_BUSY: i32 = -16;
pub const HDF_ERR_INVALID_OBJECT: i32 = -4;
pub const HDF_ERR_INVALID_PARAM: i32 = -3;
pub const HDF_ERR_IO: i32 = -17;
pub const HDF_ERR_MALLOC_FAIL: i32 = -6;
pub const HDF_ERR_NOPERM: i32 = -19;
pub const HDF_ERR_NOT_SUPPORT: i32 = -2;
pub const HDF_ERR_OUT_OF_RANGE: i32 = -20;
pub const HDF_ERR_QUEUE_FULL: i32 = -15;
pub const HDF_ERR_THREAD_CREATE_FAIL: i32 = -10;
pub const HDF_ERR_TIMEOUT: i32 = -7;
pub const HDF_FAILURE: i32 = -1;
pub const HDF_PAL_ERR_DEV_CREATE: i32 = -103;
pub const HDF_PAL_ERR_INNER: i32 = -104;
pub const HDF_SUCCESS: i32 = 0;
pub const HILOG_MODULE_ACE: i32 = 3;
pub const HILOG_MODULE_APP: i32 = 4;
pub const HILOG_MODULE_HIVIEW: i32 = 0;
pub const HILOG_MODULE_MAX: i32 = 5;
pub const HILOG_MODULE_SAMGR: i32 = 1;
pub const HILOG_MODULE_UPDATE: i32 = 2;
pub const LOG_CORE: i32 = 3;
pub const LOG_DEBUG: i32 = 3;
pub const LOG_ERROR: i32 = 6;
pub const LOG_FATAL: i32 = 7;
pub const LOG_INFO: i32 = 4;
pub const LOG_INIT: i32 = 1;
pub const LOG_TYPE_MAX: i32 = 4;
pub const LOG_TYPE_MIN: i32 = 0;
pub const LOG_WARN: i32 = 5;
pub const LOS_MOD_BUTT: i32 = 66;
pub const LOS_MOD_CACHE: i32 = 11;
pub const LOS_MOD_CPUP: i32 = 30;
pub const LOS_MOD_CSTK: i32 = 17;
pub const LOS_MOD_DRIVER: i32 = 65;
pub const LOS_MOD_ERR: i32 = 15;
pub const LOS_MOD_EVENT: i32 = 28;
pub const LOS_MOD_EVTTIME: i32 = 22;
pub const LOS_MOD_EXC: i32 = 16;
pub const LOS_MOD_HOOK: i32 = 31;
pub const LOS_MOD_HWI: i32 = 9;
pub const LOS_MOD_HWTMR: i32 = 12;
pub const LOS_MOD_HWWDG: i32 = 10;
pub const LOS_MOD_IPC: i32 = 24;
pub const LOS_MOD_KNLSTAT: i32 = 21;
pub const LOS_MOD_LOG: i32 = 14;
pub const LOS_MOD_MBOX: i32 = 8;
pub const LOS_MOD_MEM: i32 = 1;
pub const LOS_MOD_MMU: i32 = 13;
pub const LOS_MOD_MPU: i32 = 18;
pub const LOS_MOD_MSG: i32 = 5;
pub const LOS_MOD_MUX: i32 = 29;
pub const LOS_MOD_NMHWI: i32 = 19;
pub const LOS_MOD_PERF: i32 = 32;
pub const LOS_MOD_PM: i32 = 33;
pub const LOS_MOD_QUE: i32 = 6;
pub const LOS_MOD_RESLEAKMON: i32 = 27;
pub const LOS_MOD_SEM: i32 = 7;
pub const LOS_MOD_SHELL: i32 = 49;
pub const LOS_MOD_STKMON: i32 = 25;
pub const LOS_MOD_SWTMR: i32 = 3;
pub const LOS_MOD_SYS: i32 = 0;
pub const LOS_MOD_THRDCPUP: i32 = 23;
pub const LOS_MOD_TICK: i32 = 4;
pub const LOS_MOD_TIMER: i32 = 26;
pub const LOS_MOD_TRACE: i32 = 20;
pub const LOS_MOD_TSK: i32 = 2;

// --- POSIX Thread Types ---
#[repr(C)]
pub struct pthread_mutex_t { _opaque: [u8; 40] }
#[repr(C)]
pub struct pthread_cond_t { _opaque: [u8; 48] }
#[repr(C)]
pub struct pthread_rwlock_t { _opaque: [u8; 56] }
pub type pthread_once_t = i32;


// ============================================================
// Common Constants (自动追加)
// ============================================================

pub const PTHREAD_MUTEX_INITIALIZER: pthread_mutex_t = pthread_mutex_t { _opaque: [0; 40] };
pub const PTHREAD_COND_INITIALIZER: pthread_cond_t = pthread_cond_t { _opaque: [0; 48] };
pub const PTHREAD_RWLOCK_INITIALIZER: pthread_rwlock_t = pthread_rwlock_t { _opaque: [0; 56] };
pub const PTHREAD_ONCE_INIT: pthread_once_t = 0i32;
pub const __PTHREAD_MUTEX_INITIALIZER: pthread_mutex_t = pthread_mutex_t { _opaque: [0; 40] };
pub const __PTHREAD_COND_INITIALIZER: pthread_cond_t = pthread_cond_t { _opaque: [0; 48] };
pub const __PTHREAD_RWLOCK_INITIALIZER: pthread_rwlock_t = pthread_rwlock_t { _opaque: [0; 56] };
pub const __PTHREAD_ONCE_INIT: pthread_once_t = 0i32;
pub const EINVAL: i32 = 22;
pub const ENOMEM: i32 = 12;
pub const ENOENT: i32 = 2;
pub const EEXIST: i32 = 17;
pub const EBUSY: i32 = 16;
pub const EAGAIN: i32 = 11;
pub const ETIMEDOUT: i32 = 110;
pub const ENODEV: i32 = 19;
pub const EFAULT: i32 = 14;
pub const ENOSYS: i32 = 38;
pub const ERANGE: i32 = 34;
pub const ENOTCONN: i32 = 107;
pub const TRUE: i32 = 1;
pub const FALSE: i32 = 0;
pub const SOFTBUS_OK: i32 = 0;
pub const SOFTBUS_ERR: i32 = -1;
pub const SOFTBUS_NOT_IMPLEMENT: i32 = -2;
pub const SOFTBUS_INVALID_PARAM: i32 = -3;
pub const SOFTBUS_MEM_ERR: i32 = -4;
pub const SOFTBUS_MALLOC_ERR: i32 = -5;
pub const SOFTBUS_PERMISSION_DENIED: i32 = -6;
pub const SOFTBUS_NETWORK_ERR: i32 = -7;
pub const LOS_OK: i32 = 0;
pub const LOS_NOK: i32 = -1;
pub const LOS_ERRNO_BASE: u32 = 0x02000000;
pub const AUDIO_FORMAT_TYPE_PCM_16_BIT: i32 = 1;
pub const AUDIO_FORMAT_TYPE_PCM_8_BIT: i32 = 0;
pub const AUDIO_FORMAT_TYPE_PCM_24_BIT: i32 = 2;
pub const AUDIO_FORMAT_TYPE_PCM_32_BIT: i32 = 3;
// === C2R_AUTO_MISSING_TYPES_BEGIN ===
/// C2R_AUTO_TYPE: placeholder for external type `size_t`
pub type size_t = usize;

// === C2R_AUTO_MISSING_TYPES_END ===
