/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DevHostServiceClntInstallDriver(hostClnt: *mut DevHostServiceClnt)
        -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevHostServiceClntNewInstance(
        hostId: u16,
        hostName: *const ::core::ffi::c_char,
    ) -> *mut DevHostServiceClnt;
}
unsafe extern "C" {
    pub fn DevHostServiceClntFreeInstance(hostClnt: *mut DevHostServiceClnt);
}
unsafe extern "C" {
    pub fn DevHostServiceClntDelete(hostClnt: *mut DevHostServiceClnt);
}
