/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DeviceTokenClntNewInstance(tokenIf: *mut IHdfDeviceToken) -> *mut DeviceTokenClnt;
}
unsafe extern "C" {
    pub fn DeviceTokenClntFreeInstance(tokenClnt: *mut DeviceTokenClnt);
}
unsafe extern "C" {
    pub fn DeviceTokenClntDelete(listEntry: *mut HdfSListNode);
}
