/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DevmgrServiceStartService(inst: *mut IDevmgrService) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevmgrServiceConstruct(inst: *mut DevmgrService) -> bool;
}
unsafe extern "C" {
    pub fn DevmgrServiceCreate() -> *mut HdfObject;
}
unsafe extern "C" {
    pub fn DevmgrServiceRelease(object: *mut HdfObject);
}
unsafe extern "C" {
    pub fn DevmgrServiceGetInstance() -> *mut IDevmgrService;
}
unsafe extern "C" {
    pub fn DevmgrServiceLoadLeftDriver(devMgrSvc: *mut DevmgrService) -> i32;
}
unsafe extern "C" {
    pub fn DevmgrServicePowerStateChange(
        devmgrService: *mut IDevmgrService,
        powerState: HdfPowerState,
    ) -> ::core::ffi::c_int;
}
