/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DevSvcManagerCreate() -> *mut HdfObject;
}
unsafe extern "C" {
    pub fn DevSvcManagerConstruct(inst: *mut DevSvcManager) -> bool;
}
unsafe extern "C" {
    pub fn DevSvcManagerRelease(inst: *mut IDevSvcManager);
}
unsafe extern "C" {
    pub fn DevSvcManagerGetInstance() -> *mut IDevSvcManager;
}
unsafe extern "C" {
    pub fn DevSvcManagerStartService() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerAddService(
        inst: *mut IDevSvcManager,
        service: *mut HdfDeviceObject,
        servInfo: *const HdfServiceInfo,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerGetService(
        inst: *mut IDevSvcManager,
        svcName: *const ::core::ffi::c_char,
    ) -> *mut HdfObject;
}
unsafe extern "C" {
    pub fn DevSvcManagerRemoveService(
        inst: *mut IDevSvcManager,
        svcName: *const ::core::ffi::c_char,
        devObj: *const HdfDeviceObject,
    );
}
unsafe extern "C" {
    pub fn DevSvcManagerListService(serviceNameSet: *mut HdfSBuf, deviceClass: DeviceClass);
}
unsafe extern "C" {
    pub fn DevSvcManagerListServiceByInterfaceDesc(
        inst: *mut IDevSvcManager,
        interfaceDesc: *const ::core::ffi::c_char,
        reply: *mut HdfSBuf,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerUpdateService(
        inst: *mut IDevSvcManager,
        service: *mut HdfDeviceObject,
        servInfo: *const HdfServiceInfo,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerSubscribeService(
        inst: *mut IDevSvcManager,
        svcName: *const ::core::ffi::c_char,
        callBack: SubscriberCallback,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerGetObject(
        inst: *mut IDevSvcManager,
        svcName: *const ::core::ffi::c_char,
    ) -> *mut HdfDeviceObject;
}
unsafe extern "C" {
    pub fn DevSvcManagerListAllService(inst: *mut IDevSvcManager, reply: *mut HdfSBuf);
}
unsafe extern "C" {
    pub fn DevSvcManagerRegsterServListener(
        inst: *mut IDevSvcManager,
        listenerHolder: *mut ServStatListenerHolder,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn DevSvcManagerUnregsterServListener(
        inst: *mut IDevSvcManager,
        listenerHolder: *mut ServStatListenerHolder,
    );
}
