/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DriverInstallerCreate() -> *mut HdfObject;
}
unsafe extern "C" {
    pub fn DriverInstallerGetInstance() -> *mut IDriverInstaller;
}
