/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn HdfHostInfoNewInstance() -> *mut HdfHostInfo;
}
unsafe extern "C" {
    pub fn HdfHostInfoFreeInstance(hostInfo: *mut HdfHostInfo);
}
unsafe extern "C" {
    pub fn HdfHostInfoDelete(listEntry: *mut HdfSListNode);
}
