/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn VosAvlBalanceTree(pstTree: *mut AVLBASE_TREE_S, pstNode: *mut AVLBASE_NODE_S);
}
unsafe extern "C" {
    pub fn VosAvlDelete(pstBaseNode: *mut AVLBASE_NODE_S, pstBaseTree: *mut AVLBASE_TREE_S);
}
unsafe extern "C" {
    pub fn VOS_AVL3_Next(
        pstNode: *mut AVL3_NODE,
        pstTreeInfo: *mut AVL3_TREE_INFO,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL3_Prev(
        pstNode: *mut AVL3_NODE,
        pstTreeInfo: *mut AVL3_TREE_INFO,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn AVL3_Find_Or_Find_Next(
        pstTree: *mut AVL3_TREE,
        pKey: *const ::core::ffi::c_void,
        bFlag: ::core::ffi::c_uint,
        pstTreeInfo: *mut AVL3_TREE_INFO,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL3_Insert_Or_Find(
        pstTree: *mut AVL3_TREE,
        pstNode: *mut AVL3_NODE,
        pstTreeInfo: *mut AVL3_TREE_INFO,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL3_Delete(pstTree: *mut AVL3_TREE, pstNode: *mut AVL3_NODE);
}
unsafe extern "C" {
    pub fn VOS_AVL3_Find(
        pstTree: *mut AVL3_TREE,
        pstKey: *const ::core::ffi::c_void,
        pstTreeInfo: *mut AVL3_TREE_INFO,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL3_First(
        pstTree: *mut AVL3_TREE,
        pstTreeInfo: *mut AVL3_TREE_INFO,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL3_Last(
        pstTree: *mut AVL3_TREE,
        pstTreeInfo: *mut AVL3_TREE_INFO,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VosAvlRotateRight(ppstSubTree: *mut *mut AVLBASE_NODE_S);
}
unsafe extern "C" {
    pub fn VosAvlRotateLeft(ppstSubTree: *mut *mut AVLBASE_NODE_S);
}
unsafe extern "C" {
    pub fn VosAvlUpdateSwapNode(
        pstTree: *mut AVLBASE_TREE_S,
        pstSwapNode: *mut AVLBASE_NODE_S,
        pstBaseNode: *const AVLBASE_NODE_S,
    );
}
unsafe extern "C" {
    pub fn VosAvlMoveNodeToNewPos(
        pstNode: *mut AVLBASE_NODE_S,
        pstNewParent: *mut AVLBASE_NODE_S,
        pstNewLeftSon: *mut AVLBASE_NODE_S,
        pstNewRightSon: *mut AVLBASE_NODE_S,
    );
}
unsafe extern "C" {
    pub fn VosAvlSwapRightMost(
        pstTree: *mut AVLBASE_TREE_S,
        pstSubTree: *mut AVLBASE_NODE_S,
        pstNode: *mut AVLBASE_NODE_S,
    );
}
unsafe extern "C" {
    pub fn VosAvlSwapLeftMost(
        pstTree: *mut AVLBASE_TREE_S,
        pstSubTree: *mut AVLBASE_NODE_S,
        pstNode: *mut AVLBASE_NODE_S,
    );
}
unsafe extern "C" {
    pub fn VosAvlRebalance(ppstSubTree: *mut *mut AVLBASE_NODE_S);
}
unsafe extern "C" {
    pub fn VosAVLSearchReplaceNodeInRTree(
        pstTree: *mut AVLBASE_TREE_S,
        pstNode: *mut AVLBASE_NODE_S,
    ) -> *mut AVLBASE_NODE_S;
}
unsafe extern "C" {
    pub fn VosAvlSearchReplaceNodeInLTree(
        pstTree: *mut AVLBASE_TREE_S,
        pstNode: *mut AVLBASE_NODE_S,
    ) -> *mut AVLBASE_NODE_S;
}
unsafe extern "C" {
    pub fn VosAvlSearchReplaceNode(
        pstTree: *mut AVLBASE_TREE_S,
        pstNode: *mut AVLBASE_NODE_S,
    ) -> *mut AVLBASE_NODE_S;
}
unsafe extern "C" {
    pub fn VosAvlDeleteCheck(
        pstTree: *mut AVLBASE_TREE_S,
        pstNode: *mut AVLBASE_NODE_S,
    ) -> *mut AVLBASE_NODE_S;
}
unsafe extern "C" {
    pub fn VOS_AVL_Insert_Or_Find(
        pstTree: *mut AVL_TREE,
        pstNode: *mut AVL_NODE,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL_Delete(pstTree: *mut AVL_TREE, pstNode: *mut AVL_NODE);
}
unsafe extern "C" {
    pub fn VOS_AVL_Find(
        pstTree: *mut AVL_TREE,
        pKey: *const ::core::ffi::c_void,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL_Next(pstNode: *mut AVL_NODE) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL_Prev(pstNode: *mut AVL_NODE) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn VOS_AVL_Find_Or_Find_Next(
        pstTree: *mut AVL_TREE,
        pKey: *const ::core::ffi::c_void,
        bValue: ::core::ffi::c_uint,
    ) -> *mut ::core::ffi::c_void;
}
