/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn HdfObjectManagerGetObject(objectId: ::core::ffi::c_int) -> *mut HdfObject;
}
unsafe extern "C" {
    pub fn HdfObjectManagerFreeObject(object: *mut HdfObject);
}
