/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DevSvcRecordNewInstance() -> *mut DevSvcRecord;
}
unsafe extern "C" {
    pub fn DevSvcRecordFreeInstance(inst: *mut DevSvcRecord);
}
