/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn IoServiceStatusListenerNewInstance() -> *mut ServiceStatusListener;
}
unsafe extern "C" {
    pub fn IoServiceStatusListenerFree(listener: *mut ServiceStatusListener);
}
