/* automatically generated by rust-bindgen 0.72.1 */
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused)]

pub const _REDIR_TIME64: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST64_MAX: i32 = -1;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INTMAX_MIN: i64 = -9223372036854775808;
pub const INTMAX_MAX: u64 = 9223372036854775807;
pub const UINTMAX_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const INT_FAST16_MIN: i32 = -2147483648;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST16_MAX: u32 = 2147483647;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const UINT_FAST16_MAX: u32 = 4294967295;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const INTPTR_MIN: i32 = -2147483648;
pub const INTPTR_MAX: u32 = 2147483647;
pub const UINTPTR_MAX: u32 = 4294967295;
pub const PTRDIFF_MIN: i32 = -2147483648;
pub const PTRDIFF_MAX: u32 = 2147483647;
pub const SIZE_MAX: u32 = 4294967295;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const FORTIFY_LONG_MAX: u32 = 2147483647;
pub const FORTIFY_SSIZE_MAX: u32 = 2147483647;
pub const FORTIFY_PATH_MAX: u32 = 4096;
pub const FORTIFY_RUNTIME_ERROR_PREFIX: &[u8; 29] = b"Musl Fortify runtime error: \0";
pub const OPEN_TOO_MANY_ARGS_ERROR: &[u8; 29] = b"There are too many arguments\0";
pub const OPEN_TOO_FEW_ARGS_ERROR: &[u8; 57] =
    b"invoking with O_CREAT or O_TMPFILE, but missing pattern.\0";
pub const OPEN_USELESS_MODES_WARNING: &[u8; 49] =
    b"having redundant mode bits; but missing O_CREAT.\0";
pub const CALLED_WITH_STRING_BIGGER_BUFFER: &[u8; 44] =
    b"called with a string larger than the buffer\0";
pub const FD_COUNT_LARGE_GIVEN_BUFFER: &[u8; 42] = b"fd_count is greater than the given buffer\0";
pub const CALLED_WITH_SIZE_BIGGER_BUFFER: &[u8; 40] = b"called with bigger size than the buffer\0";
pub const OUTPUT_PARAMETER_BYTES : & [u8 ; 95] = b"the output parameter must be nullptr or a pointer to the buffer with >= FORTIFY_PATH_MAX bytes\0" ;
pub const SIZE_LARGER_THEN_DESTINATION_BUFFER: &[u8; 43] =
    b"the size is greater than the target buffer\0";
pub const CHAR_MIN: u32 = 0;
pub const CHAR_MAX: u32 = 255;
pub const CHAR_BIT: u32 = 8;
pub const SCHAR_MIN: i32 = -128;
pub const SCHAR_MAX: u32 = 127;
pub const UCHAR_MAX: u32 = 255;
pub const SHRT_MIN: i32 = -32768;
pub const SHRT_MAX: u32 = 32767;
pub const USHRT_MAX: u32 = 65535;
pub const INT_MIN: i32 = -2147483648;
pub const INT_MAX: u32 = 2147483647;
pub const UINT_MAX: u32 = 4294967295;
pub const LONG_MAX: u32 = 2147483647;
pub const ULONG_MAX: u32 = 4294967295;
pub const LLONG_MAX: u64 = 9223372036854775807;
pub const ULLONG_MAX: i32 = -1;
pub const MB_LEN_MAX: u32 = 4;
pub const PIPE_BUF: u32 = 4096;
pub const FILESIZEBITS: u32 = 64;
pub const NAME_MAX: u32 = 255;
pub const PATH_MAX: u32 = 4096;
pub const ARG_MAX: u32 = 131072;
pub const NGROUPS_MAX: u32 = 32;
pub const IOV_MAX: u32 = 1024;
pub const SYMLOOP_MAX: u32 = 40;
pub const WORD_BIT: u32 = 32;
pub const SSIZE_MAX: u32 = 2147483647;
pub const TZNAME_MAX: u32 = 6;
pub const TTY_NAME_MAX: u32 = 32;
pub const HOST_NAME_MAX: u32 = 255;
pub const LONG_BIT: u32 = 32;
pub const PTHREAD_KEYS_MAX: u32 = 128;
pub const PTHREAD_STACK_MIN: u32 = 2048;
pub const PTHREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const SEM_VALUE_MAX: u32 = 2147483647;
pub const SEM_NSEMS_MAX: u32 = 256;
pub const DELAYTIMER_MAX: u32 = 2147483647;
pub const MQ_PRIO_MAX: u32 = 32768;
pub const LOGIN_NAME_MAX: u32 = 256;
pub const BC_BASE_MAX: u32 = 99;
pub const BC_DIM_MAX: u32 = 2048;
pub const BC_SCALE_MAX: u32 = 99;
pub const BC_STRING_MAX: u32 = 1000;
pub const CHARCLASS_NAME_MAX: u32 = 14;
pub const COLL_WEIGHTS_MAX: u32 = 2;
pub const EXPR_NEST_MAX: u32 = 32;
pub const LINE_MAX: u32 = 4096;
pub const RE_DUP_MAX: u32 = 255;
pub const NL_ARGMAX: u32 = 9;
pub const NL_MSGMAX: u32 = 32767;
pub const NL_SETMAX: u32 = 255;
pub const NL_TEXTMAX: u32 = 2048;
pub const NZERO: u32 = 20;
pub const NL_LANGMAX: u32 = 32;
pub const NL_NMAX: u32 = 16;
pub const _POSIX_AIO_LISTIO_MAX: u32 = 2;
pub const _POSIX_AIO_MAX: u32 = 1;
pub const _POSIX_ARG_MAX: u32 = 4096;
pub const _POSIX_CHILD_MAX: u32 = 25;
pub const _POSIX_CLOCKRES_MIN: u32 = 20000000;
pub const _POSIX_DELAYTIMER_MAX: u32 = 32;
pub const _POSIX_HOST_NAME_MAX: u32 = 255;
pub const _POSIX_LINK_MAX: u32 = 8;
pub const _POSIX_LOGIN_NAME_MAX: u32 = 9;
pub const _POSIX_MAX_CANON: u32 = 255;
pub const _POSIX_MAX_INPUT: u32 = 255;
pub const _POSIX_MQ_OPEN_MAX: u32 = 8;
pub const _POSIX_MQ_PRIO_MAX: u32 = 32;
pub const _POSIX_NAME_MAX: u32 = 14;
pub const _POSIX_NGROUPS_MAX: u32 = 8;
pub const _POSIX_OPEN_MAX: u32 = 20;
pub const _POSIX_PATH_MAX: u32 = 256;
pub const _POSIX_PIPE_BUF: u32 = 512;
pub const _POSIX_RE_DUP_MAX: u32 = 255;
pub const _POSIX_RTSIG_MAX: u32 = 8;
pub const _POSIX_SEM_NSEMS_MAX: u32 = 256;
pub const _POSIX_SEM_VALUE_MAX: u32 = 32767;
pub const _POSIX_SIGQUEUE_MAX: u32 = 32;
pub const _POSIX_SSIZE_MAX: u32 = 32767;
pub const _POSIX_STREAM_MAX: u32 = 8;
pub const _POSIX_SS_REPL_MAX: u32 = 4;
pub const _POSIX_SYMLINK_MAX: u32 = 255;
pub const _POSIX_SYMLOOP_MAX: u32 = 8;
pub const _POSIX_THREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const _POSIX_THREAD_KEYS_MAX: u32 = 128;
pub const _POSIX_THREAD_THREADS_MAX: u32 = 64;
pub const _POSIX_TIMER_MAX: u32 = 32;
pub const _POSIX_TRACE_EVENT_NAME_MAX: u32 = 30;
pub const _POSIX_TRACE_NAME_MAX: u32 = 8;
pub const _POSIX_TRACE_SYS_MAX: u32 = 8;
pub const _POSIX_TRACE_USER_EVENT_MAX: u32 = 32;
pub const _POSIX_TTY_NAME_MAX: u32 = 9;
pub const _POSIX_TZNAME_MAX: u32 = 6;
pub const _POSIX2_BC_BASE_MAX: u32 = 99;
pub const _POSIX2_BC_DIM_MAX: u32 = 2048;
pub const _POSIX2_BC_SCALE_MAX: u32 = 99;
pub const _POSIX2_BC_STRING_MAX: u32 = 1000;
pub const _POSIX2_CHARCLASS_NAME_MAX: u32 = 14;
pub const _POSIX2_COLL_WEIGHTS_MAX: u32 = 2;
pub const _POSIX2_EXPR_NEST_MAX: u32 = 32;
pub const _POSIX2_LINE_MAX: u32 = 2048;
pub const _POSIX2_RE_DUP_MAX: u32 = 255;
pub const _XOPEN_IOV_MAX: u32 = 16;
pub const _XOPEN_NAME_MAX: u32 = 255;
pub const _XOPEN_PATH_MAX: u32 = 1024;
pub const HDF_BSP_ERR_START: i32 = -100;
pub const HDF_DEV_ERR_START: i32 = -200;
pub const HDF_WAIT_FOREVER: u32 = 4294967295;
pub const HDF_KILO_UNIT: u32 = 1000;
pub const HDF_LIBRARY_DIR: &[u8; 12] = b"/vendor/lib\0";
pub const HDF_ETC_DIR: &[u8; 12] = b"/vendor/etc\0";
pub const HDF_CONFIG_DIR: &[u8; 22] = b"/vendor/etc/hdfconfig\0";
pub const HDF_CHIP_PROD_CONFIG_DIR: &[u8; 25] = b"/chip_prod/etc/hdfconfig\0";
pub const HDF_MODULE_DIR: &[u8; 17] = b"/vendor/modules/\0";
pub const LOG_DOMAIN: u32 = 0;
pub const SECUREC_USING_STD_SECURE_LIB: u32 = 0;
pub const SECUREC_DISABLE_CRT_FUNC: u32 = 0;
pub const SECUREC_DISABLE_CRT_IMP: u32 = 0;
pub const SECUREC_IN_KERNEL: u32 = 0;
pub const SECUREC_EXPORT_KERNEL_SYMBOL: u32 = 0;
pub const SECUREC_ENABLE_SCANF_FILE: u32 = 1;
pub const SECUREC_ENABLE_WCHAR_FUNC: u32 = 1;
pub const SECUREC_SNPRINTF_TRUNCATED: u32 = 1;
pub const SECUREC_ENABLE_MEMSET: u32 = 1;
pub const SECUREC_ENABLE_MEMMOVE: u32 = 1;
pub const SECUREC_ENABLE_MEMCPY: u32 = 1;
pub const SECUREC_ENABLE_STRCPY: u32 = 1;
pub const SECUREC_ENABLE_STRNCPY: u32 = 1;
pub const SECUREC_ENABLE_STRCAT: u32 = 1;
pub const SECUREC_ENABLE_STRNCAT: u32 = 1;
pub const SECUREC_ENABLE_SPRINTF: u32 = 1;
pub const SECUREC_ENABLE_VSPRINTF: u32 = 1;
pub const SECUREC_ENABLE_SNPRINTF: u32 = 1;
pub const SECUREC_ENABLE_VSNPRINTF: u32 = 1;
pub const SECUREC_ENABLE_SSCANF: u32 = 1;
pub const SECUREC_ENABLE_VSSCANF: u32 = 1;
pub const SECUREC_ENABLE_SCANF: u32 = 1;
pub const SECUREC_ENABLE_VSCANF: u32 = 1;
pub const SECUREC_ENABLE_FSCANF: u32 = 1;
pub const SECUREC_ENABLE_VFSCANF: u32 = 1;
pub const SECUREC_ENABLE_STRTOK: u32 = 1;
pub const SECUREC_ENABLE_GETS: u32 = 1;
pub const SECUREC_HAVE_STDIO_H: u32 = 1;
pub const SECUREC_HAVE_STRING_H: u32 = 1;
pub const SECUREC_HAVE_STDLIB_H: u32 = 1;
pub const EOF: i32 = -1;
pub const SEEK_SET: u32 = 0;
pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const _IOFBF: u32 = 0;
pub const _IOLBF: u32 = 1;
pub const _IONBF: u32 = 2;
pub const BUFSIZ: u32 = 1024;
pub const FILENAME_MAX: u32 = 4096;
pub const FOPEN_MAX: u32 = 1000;
pub const TMP_MAX: u32 = 10000;
pub const L_tmpnam: u32 = 20;
pub const RENAME_NOREPLACE: u32 = 1;
pub const RENAME_EXCHANGE: u32 = 2;
pub const RENAME_WHITEOUT: u32 = 4;
pub const L_ctermid: u32 = 20;
pub const P_tmpdir: &[u8; 5] = b"/tmp\0";
pub const L_cuserid: u32 = 20;
pub const EXIT_FAILURE: u32 = 1;
pub const EXIT_SUCCESS: u32 = 0;
pub const RAND_MAX: u32 = 2147483647;
pub const WNOHANG: u32 = 1;
pub const WUNTRACED: u32 = 2;
pub const SECUREC_WITH_PERFORMANCE_ADDONS: u32 = 1;
pub const SECUREC_HAVE_STDDEF_H: u32 = 1;
pub const SECUREC_SUPPORT_FORMAT_WARNING: u32 = 0;
pub const SECUREC_SUPPORT_BUILTIN_EXPECT: u32 = 1;
pub const SECUREC_STRING_MAX_LEN: u32 = 2147483647;
pub const SECUREC_MEM_MAX_LEN: u32 = 2147483647;
pub const SECUREC_SUPPORT_STRTOLD: u32 = 0;
pub const SECUREC_HAVE_STDARG_H: u32 = 1;
pub const SECUREC_HAVE_ERRNO_H: u32 = 1;
pub const EPERM: u32 = 1;
pub const ENOENT: u32 = 2;
pub const ESRCH: u32 = 3;
pub const EINTR: u32 = 4;
pub const EIO: u32 = 5;
pub const ENXIO: u32 = 6;
pub const E2BIG: u32 = 7;
pub const ENOEXEC: u32 = 8;
pub const EBADF: u32 = 9;
pub const ECHILD: u32 = 10;
pub const EAGAIN: u32 = 11;
pub const ENOMEM: u32 = 12;
pub const EACCES: u32 = 13;
pub const EFAULT: u32 = 14;
pub const ENOTBLK: u32 = 15;
pub const EBUSY: u32 = 16;
pub const EEXIST: u32 = 17;
pub const EXDEV: u32 = 18;
pub const ENODEV: u32 = 19;
pub const ENOTDIR: u32 = 20;
pub const EISDIR: u32 = 21;
pub const EINVAL: u32 = 22;
pub const ENFILE: u32 = 23;
pub const EMFILE: u32 = 24;
pub const ENOTTY: u32 = 25;
pub const ETXTBSY: u32 = 26;
pub const EFBIG: u32 = 27;
pub const ENOSPC: u32 = 28;
pub const ESPIPE: u32 = 29;
pub const EROFS: u32 = 30;
pub const EMLINK: u32 = 31;
pub const EPIPE: u32 = 32;
pub const EDOM: u32 = 33;
pub const ERANGE: u32 = 34;
pub const EDEADLK: u32 = 35;
pub const ENAMETOOLONG: u32 = 36;
pub const ENOLCK: u32 = 37;
pub const ENOSYS: u32 = 38;
pub const ENOTEMPTY: u32 = 39;
pub const ELOOP: u32 = 40;
pub const EWOULDBLOCK: u32 = 11;
pub const ENOMSG: u32 = 42;
pub const EIDRM: u32 = 43;
pub const ECHRNG: u32 = 44;
pub const EL2NSYNC: u32 = 45;
pub const EL3HLT: u32 = 46;
pub const EL3RST: u32 = 47;
pub const ELNRNG: u32 = 48;
pub const EUNATCH: u32 = 49;
pub const ENOCSI: u32 = 50;
pub const EL2HLT: u32 = 51;
pub const EBADE: u32 = 52;
pub const EBADR: u32 = 53;
pub const EXFULL: u32 = 54;
pub const ENOANO: u32 = 55;
pub const EBADRQC: u32 = 56;
pub const EBADSLT: u32 = 57;
pub const EDEADLOCK: u32 = 35;
pub const EBFONT: u32 = 59;
pub const ENOSTR: u32 = 60;
pub const ENODATA: u32 = 61;
pub const ETIME: u32 = 62;
pub const ENOSR: u32 = 63;
pub const ENONET: u32 = 64;
pub const ENOPKG: u32 = 65;
pub const EREMOTE: u32 = 66;
pub const ENOLINK: u32 = 67;
pub const EADV: u32 = 68;
pub const ESRMNT: u32 = 69;
pub const ECOMM: u32 = 70;
pub const EPROTO: u32 = 71;
pub const EMULTIHOP: u32 = 72;
pub const EDOTDOT: u32 = 73;
pub const EBADMSG: u32 = 74;
pub const EOVERFLOW: u32 = 75;
pub const ENOTUNIQ: u32 = 76;
pub const EBADFD: u32 = 77;
pub const EREMCHG: u32 = 78;
pub const ELIBACC: u32 = 79;
pub const ELIBBAD: u32 = 80;
pub const ELIBSCN: u32 = 81;
pub const ELIBMAX: u32 = 82;
pub const ELIBEXEC: u32 = 83;
pub const EILSEQ: u32 = 84;
pub const ERESTART: u32 = 85;
pub const ESTRPIPE: u32 = 86;
pub const EUSERS: u32 = 87;
pub const ENOTSOCK: u32 = 88;
pub const EDESTADDRREQ: u32 = 89;
pub const EMSGSIZE: u32 = 90;
pub const EPROTOTYPE: u32 = 91;
pub const ENOPROTOOPT: u32 = 92;
pub const EPROTONOSUPPORT: u32 = 93;
pub const ESOCKTNOSUPPORT: u32 = 94;
pub const EOPNOTSUPP: u32 = 95;
pub const ENOTSUP: u32 = 95;
pub const EPFNOSUPPORT: u32 = 96;
pub const EAFNOSUPPORT: u32 = 97;
pub const EADDRINUSE: u32 = 98;
pub const EADDRNOTAVAIL: u32 = 99;
pub const ENETDOWN: u32 = 100;
pub const ENETUNREACH: u32 = 101;
pub const ENETRESET: u32 = 102;
pub const ECONNABORTED: u32 = 103;
pub const ECONNRESET: u32 = 104;
pub const ENOBUFS: u32 = 105;
pub const EISCONN: u32 = 106;
pub const ENOTCONN: u32 = 107;
pub const ESHUTDOWN: u32 = 108;
pub const ETOOMANYREFS: u32 = 109;
pub const ETIMEDOUT: u32 = 110;
pub const ECONNREFUSED: u32 = 111;
pub const EHOSTDOWN: u32 = 112;
pub const EHOSTUNREACH: u32 = 113;
pub const EALREADY: u32 = 114;
pub const EINPROGRESS: u32 = 115;
pub const ESTALE: u32 = 116;
pub const EUCLEAN: u32 = 117;
pub const ENOTNAM: u32 = 118;
pub const ENAVAIL: u32 = 119;
pub const EISNAM: u32 = 120;
pub const EREMOTEIO: u32 = 121;
pub const EDQUOT: u32 = 122;
pub const ENOMEDIUM: u32 = 123;
pub const EMEDIUMTYPE: u32 = 124;
pub const ECANCELED: u32 = 125;
pub const ENOKEY: u32 = 126;
pub const EKEYEXPIRED: u32 = 127;
pub const EKEYREVOKED: u32 = 128;
pub const EKEYREJECTED: u32 = 129;
pub const EOWNERDEAD: u32 = 130;
pub const ENOTRECOVERABLE: u32 = 131;
pub const ERFKILL: u32 = 132;
pub const EHWPOISON: u32 = 133;
pub const EOK: u32 = 0;
pub const EINVAL_AND_RESET: u32 = 150;
pub const ERANGE_AND_RESET: u32 = 162;
pub const EOVERLAP_AND_RESET: u32 = 182;
pub const SECUREC_ONLY_DECLARE_MEMSET: u32 = 0;
pub const HOSTID_BITS: u32 = 8;
pub const DEVICEID_BITS: u32 = 16;
pub const DEVNODEID_BITS: u32 = 8;
pub const DEVNODEID_MASK: u32 = 255;
pub const DEVICEID_MASK: u32 = 65535;
pub const HCS_MATCH_ATTR: &[u8; 11] = b"match_attr\0";
pub type wchar_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __ll: ::core::ffi::c_longlong,
    pub __ld: f64,
}
pub type size_t = ::core::ffi::c_uint;
pub type intmax_t = ::core::ffi::c_longlong;
pub type uintmax_t = ::core::ffi::c_ulonglong;
pub type int_fast8_t = i8;
pub type int_fast64_t = i64;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast64_t = u64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast16_t = i32;
pub type int_fast32_t = i32;
pub type uint_fast16_t = u32;
pub type uint_fast32_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __locale_struct {
    _unused: [u8; 0],
}
pub type locale_t = *mut __locale_struct;
pub const HDF_SUCCESS: HDF_STATUS = 0;
pub const HDF_FAILURE: HDF_STATUS = -1;
pub const HDF_ERR_NOT_SUPPORT: HDF_STATUS = -2;
pub const HDF_ERR_INVALID_PARAM: HDF_STATUS = -3;
pub const HDF_ERR_INVALID_OBJECT: HDF_STATUS = -4;
pub const HDF_ERR_MALLOC_FAIL: HDF_STATUS = -6;
pub const HDF_ERR_TIMEOUT: HDF_STATUS = -7;
pub const HDF_ERR_THREAD_CREATE_FAIL: HDF_STATUS = -10;
pub const HDF_ERR_QUEUE_FULL: HDF_STATUS = -15;
pub const HDF_ERR_DEVICE_BUSY: HDF_STATUS = -16;
pub const HDF_ERR_IO: HDF_STATUS = -17;
pub const HDF_ERR_BAD_FD: HDF_STATUS = -18;
pub const HDF_ERR_NOPERM: HDF_STATUS = -19;
pub const HDF_ERR_OUT_OF_RANGE: HDF_STATUS = -20;
pub const HDF_BSP_ERR_OP: HDF_STATUS = -101;
pub const HDF_ERR_BSP_PLT_API_ERR: HDF_STATUS = -102;
pub const HDF_PAL_ERR_DEV_CREATE: HDF_STATUS = -103;
pub const HDF_PAL_ERR_INNER: HDF_STATUS = -104;
pub const HDF_DEV_ERR_NO_MEMORY: HDF_STATUS = -201;
pub const HDF_DEV_ERR_NO_DEVICE: HDF_STATUS = -202;
pub const HDF_DEV_ERR_NO_DEVICE_SERVICE: HDF_STATUS = -203;
pub const HDF_DEV_ERR_DEV_INIT_FAIL: HDF_STATUS = -204;
pub const HDF_DEV_ERR_PUBLISH_FAIL: HDF_STATUS = -205;
pub const HDF_DEV_ERR_ATTACHDEV_FAIL: HDF_STATUS = -206;
pub const HDF_DEV_ERR_NODATA: HDF_STATUS = -207;
pub const HDF_DEV_ERR_NORANGE: HDF_STATUS = -208;
pub const HDF_DEV_ERR_OP: HDF_STATUS = -210;
pub const HDF_DEV_ERR_NETDOWN: HDF_STATUS = -211;
pub type HDF_STATUS = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSListNode {
    pub next: *mut HdfSListNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSList {
    pub root: *mut HdfSListNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSListIterator {
    pub stepOnNext: ::core::ffi::c_int,
    pub prev: *mut HdfSListNode,
    pub curr: *mut HdfSListNode,
}
pub type HdfSListDeleter = ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSListNode)>;
pub type HdfSListSearchComparer =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSListNode, arg2: u32) -> bool>;
pub type HdfSListAddComparer = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut HdfSListNode, arg2: *mut HdfSListNode) -> bool,
>;
pub const HDF_SERVICE_UNUSABLE: _bindgen_ty_1 = 0;
pub const HDF_SERVICE_USABLE: _bindgen_ty_1 = 1;
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const HDF_DEV_LOCAL_SERVICE: _bindgen_ty_2 = 0;
pub const HDF_DEV_REMOTE_SERVICE: _bindgen_ty_2 = 1;
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceInfo {
    pub node: HdfSListNode,
    pub isDynamic: bool,
    pub status: u16,
    pub deviceType: u16,
    pub deviceId: u32,
    pub policy: u16,
    pub priority: u16,
    pub preload: u16,
    pub permission: u16,
    pub moduleName: *const ::core::ffi::c_char,
    pub svcName: *const ::core::ffi::c_char,
    pub deviceMatchAttr: *const ::core::ffi::c_char,
    pub deviceName: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfPrivateInfo {
    pub length: u32,
    pub data: *const ::core::ffi::c_void,
}
pub type char16_t = u16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBuf {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBufImpl {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfRemoteService {
    _unused: [u8; 0],
}
pub const SBUF_RAW: HdfSbufType = 0;
pub const SBUF_IPC: HdfSbufType = 1;
pub const SBUF_IPC_HW: HdfSbufType = 2;
pub const SBUF_TYPE_MAX: HdfSbufType = 3;
pub type HdfSbufType = ::core::ffi::c_uint;
pub type va_list = u32;
pub const LOG_TYPE_MIN: LogType = 0;
pub const LOG_APP: LogType = 0;
pub const LOG_INIT: LogType = 1;
pub const LOG_CORE: LogType = 3;
pub const LOG_KMSG: LogType = 4;
pub const LOG_ONLY_PRERELEASE: LogType = 5;
pub const LOG_TYPE_MAX: LogType = 6;
pub type LogType = ::core::ffi::c_uint;
pub const LOG_LEVEL_MIN: LogLevel = 0;
pub const LOG_DEBUG: LogLevel = 3;
pub const LOG_INFO: LogLevel = 4;
pub const LOG_WARN: LogLevel = 5;
pub const LOG_ERROR: LogLevel = 6;
pub const LOG_FATAL: LogLevel = 7;
pub const LOG_LEVEL_MAX: LogLevel = 8;
pub type LogLevel = ::core::ffi::c_uint;
pub type LogCallback = ::core::option::Option<
    unsafe extern "C" fn(
        type_: LogType,
        level: LogLevel,
        domain: ::core::ffi::c_uint,
        tag: *const ::core::ffi::c_char,
        msg: *const ::core::ffi::c_char,
    ),
>;
pub type ssize_t = ::core::ffi::c_int;
pub type off_t = ::core::ffi::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    _unused: [u8; 0],
}
pub type FILE = _IO_FILE;
pub type __isoc_va_list = u32;
#[repr(C)]
#[derive(Copy, Clone)]
pub union _G_fpos64_t {
    pub __opaque: [::core::ffi::c_char; 16usize],
    pub __lldata: ::core::ffi::c_longlong,
    pub __align: f64,
}
pub type fpos_t = _G_fpos64_t;
pub type cookie_read_function_t = ::core::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::core::ffi::c_void,
        arg2: *mut ::core::ffi::c_char,
        arg3: size_t,
    ) -> ssize_t,
>;
pub type cookie_write_function_t = ::core::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::core::ffi::c_void,
        arg2: *const ::core::ffi::c_char,
        arg3: size_t,
    ) -> ssize_t,
>;
pub type cookie_seek_function_t = ::core::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::core::ffi::c_void,
        arg2: *mut off_t,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int,
>;
pub type cookie_close_function_t = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void) -> ::core::ffi::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_cookie_io_functions_t {
    pub read: cookie_read_function_t,
    pub write: cookie_write_function_t,
    pub seek: cookie_seek_function_t,
    pub close: cookie_close_function_t,
}
pub type cookie_io_functions_t = _IO_cookie_io_functions_t;
pub const FDSAN_OWNER_TYPE_DEFAULT: fdsan_owner_type = 0;
pub const FDSAN_OWNER_TYPE_MAX: fdsan_owner_type = 255;
pub const FDSAN_OWNER_TYPE_FILE: fdsan_owner_type = 1;
pub const FDSAN_OWNER_TYPE_DIRECTORY: fdsan_owner_type = 2;
pub const FDSAN_OWNER_TYPE_UNIQUE_FD: fdsan_owner_type = 3;
pub const FDSAN_OWNER_TYPE_ZIP_ARCHIVE: fdsan_owner_type = 4;
pub type fdsan_owner_type = ::core::ffi::c_uint;
pub const FDSAN_ERROR_LEVEL_DISABLED: fdsan_error_level = 0;
pub const FDSAN_ERROR_LEVEL_WARN_ONCE: fdsan_error_level = 1;
pub const FDSAN_ERROR_LEVEL_WARN_ALWAYS: fdsan_error_level = 2;
pub const FDSAN_ERROR_LEVEL_FATAL: fdsan_error_level = 3;
pub type fdsan_error_level = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct div_t {
    pub quot: ::core::ffi::c_int,
    pub rem: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ldiv_t {
    pub quot: ::core::ffi::c_long,
    pub rem: ::core::ffi::c_long,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lldiv_t {
    pub quot: ::core::ffi::c_longlong,
    pub rem: ::core::ffi::c_longlong,
}
pub type errno_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DListHead {
    pub next: *mut DListHead,
    pub prev: *mut DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObject {
    pub objectId: i32,
}
pub type devid_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceNode {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IHdfDevice {
    pub object: HdfObject,
    pub Attach: ::core::option::Option<
        unsafe extern "C" fn(
            device: *mut IHdfDevice,
            deviceNode: *mut HdfDeviceNode,
        ) -> ::core::ffi::c_int,
    >,
    pub Detach: ::core::option::Option<
        unsafe extern "C" fn(
            device: *mut IHdfDevice,
            deviceNode: *mut HdfDeviceNode,
        ) -> ::core::ffi::c_int,
    >,
    pub GetDeviceNode: ::core::option::Option<
        unsafe extern "C" fn(device: *mut IHdfDevice, devid: devid_t) -> *mut HdfDeviceNode,
    >,
    pub DetachWithDevid: ::core::option::Option<
        unsafe extern "C" fn(device: *mut IHdfDevice, devid: devid_t) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDevice {
    pub super_: IHdfDevice,
    pub node: DListHead,
    pub devNodes: DListHead,
    pub deviceId: devid_t,
    pub devidIndex: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDevHostService {
    pub object: HdfObject,
    pub AddDevice: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            devInfo: *const HdfDeviceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub DelDevice: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            devId: devid_t,
        ) -> ::core::ffi::c_int,
    >,
    pub StartService: ::core::option::Option<
        unsafe extern "C" fn(hostService: *mut IDevHostService) -> ::core::ffi::c_int,
    >,
    pub PmNotify: ::core::option::Option<
        unsafe extern "C" fn(service: *mut IDevHostService, powerState: u32) -> ::core::ffi::c_int,
    >,
    pub Dump: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MapNode {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Map {
    pub nodes: *mut *mut MapNode,
    pub nodeSize: u32,
    pub bucketSize: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalMutex {
    pub realMutex: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevHostServiceClnt {
    pub node: DListHead,
    pub devices: HdfSList,
    pub unloadDevInfos: HdfSList,
    pub dynamicDevInfos: HdfSList,
    pub deviceHashMap: *mut Map,
    pub hostService: *mut IDevHostService,
    pub hostLock: OsalMutex,
    pub devCount: u16,
    pub hostId: u16,
    pub hostPid: ::core::ffi::c_int,
    pub hostName: *const ::core::ffi::c_char,
    pub stopFlag: bool,
}
pub const HDF_CONFIG_SOURCE: DeviceResourceType = 0;
pub const INVALID: DeviceResourceType = 1;
pub type DeviceResourceType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceAttr {
    pub name: *const ::core::ffi::c_char,
    pub value: *const ::core::ffi::c_char,
    pub next: *mut DeviceResourceAttr,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceNode {
    pub name: *const ::core::ffi::c_char,
    pub hashValue: u32,
    pub attrData: *mut DeviceResourceAttr,
    pub parent: *mut DeviceResourceNode,
    pub child: *mut DeviceResourceNode,
    pub sibling: *mut DeviceResourceNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceIface {
    pub GetRootNode: ::core::option::Option<unsafe extern "C" fn() -> *const DeviceResourceNode>,
    pub GetBool: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
        ) -> bool,
    >,
    pub GetUint8: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u8,
            def: u8,
        ) -> i32,
    >,
    pub GetUint8ArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut u8,
            def: u8,
        ) -> i32,
    >,
    pub GetUint8Array: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u8,
            len: u32,
            def: u8,
        ) -> i32,
    >,
    pub GetUint16: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u16,
            def: u16,
        ) -> i32,
    >,
    pub GetUint16ArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut u16,
            def: u16,
        ) -> i32,
    >,
    pub GetUint16Array: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u16,
            len: u32,
            def: u16,
        ) -> i32,
    >,
    pub GetUint32: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u32,
            def: u32,
        ) -> i32,
    >,
    pub GetUint32ArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut u32,
            def: u32,
        ) -> i32,
    >,
    pub GetUint32Array: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u32,
            len: u32,
            def: u32,
        ) -> i32,
    >,
    pub GetUint64: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u64,
            def: u64,
        ) -> i32,
    >,
    pub GetUint64ArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut u64,
            def: u64,
        ) -> i32,
    >,
    pub GetUint64Array: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u64,
            len: u32,
            def: u64,
        ) -> i32,
    >,
    pub GetString: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut *const ::core::ffi::c_char,
            def: *const ::core::ffi::c_char,
        ) -> i32,
    >,
    pub GetStringArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut *const ::core::ffi::c_char,
            def: *const ::core::ffi::c_char,
        ) -> i32,
    >,
    pub GetElemNum: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
        ) -> i32,
    >,
    pub GetNodeByMatchAttr: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrValue: *const ::core::ffi::c_char,
        ) -> *const DeviceResourceNode,
    >,
    pub GetChildNode: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            nodeName: *const ::core::ffi::c_char,
        ) -> *const DeviceResourceNode,
    >,
    pub GetNodeByRefAttr: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
        ) -> *const DeviceResourceNode,
    >,
}
