/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObject {
    pub objectId: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBuf {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoDispatcher {
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            service: *mut HdfObject,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoService {
    pub object: HdfObject,
    pub target: *mut HdfObject,
    pub dispatcher: *mut HdfIoDispatcher,
    pub priv_: *mut ::core::ffi::c_void,
}
unsafe extern "C" {
    pub fn HdfIoServiceAdapterObtain(serviceName: *const ::core::ffi::c_char) -> *mut HdfIoService;
}
unsafe extern "C" {
    pub fn HdfIoServiceAdapterRecycle(service: *mut HdfIoService);
}
unsafe extern "C" {
    pub fn HdfIoServiceAdapterPublish(
        serviceName: *const ::core::ffi::c_char,
        mode: u32,
    ) -> *mut HdfIoService;
}
unsafe extern "C" {
    pub fn HdfIoServiceAdapterRemove(service: *mut HdfIoService);
}
