/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub static mut daiController: DListHead;
}
unsafe extern "C" {
    pub static mut platformController: DListHead;
}
unsafe extern "C" {
    pub static mut codecController: DListHead;
}
unsafe extern "C" {
    pub static mut dspController: DListHead;
}
