/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn rgba_new(rgba: u32) -> rgba_t;
}
unsafe extern "C" {
    pub fn rgba_from_string(str_: *const ::core::ffi::c_char, ok: *mut ::core::ffi::c_short)
        -> u32;
}
unsafe extern "C" {
    pub fn rgba_to_string(rgba: rgba_t, buf: *mut ::core::ffi::c_char, len: size_t);
}
unsafe extern "C" {
    pub fn rgba_inspect(rgba: u32);
}
