/* automatically generated by rust-bindgen 0.72.1 */
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused)]

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub const _REDIR_TIME64: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST64_MAX: i32 = -1;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INTMAX_MIN: i64 = -9223372036854775808;
pub const INTMAX_MAX: u64 = 9223372036854775807;
pub const UINTMAX_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const INT_FAST16_MIN: i32 = -2147483648;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST16_MAX: u32 = 2147483647;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const UINT_FAST16_MAX: u32 = 4294967295;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const INTPTR_MIN: i32 = -2147483648;
pub const INTPTR_MAX: u32 = 2147483647;
pub const UINTPTR_MAX: u32 = 4294967295;
pub const PTRDIFF_MIN: i32 = -2147483648;
pub const PTRDIFF_MAX: u32 = 2147483647;
pub const SIZE_MAX: u32 = 4294967295;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const FORTIFY_LONG_MAX: u32 = 2147483647;
pub const FORTIFY_SSIZE_MAX: u32 = 2147483647;
pub const FORTIFY_PATH_MAX: u32 = 4096;
pub const FORTIFY_RUNTIME_ERROR_PREFIX: &[u8; 29] = b"Musl Fortify runtime error: \0";
pub const OPEN_TOO_MANY_ARGS_ERROR: &[u8; 29] = b"There are too many arguments\0";
pub const OPEN_TOO_FEW_ARGS_ERROR: &[u8; 57] =
    b"invoking with O_CREAT or O_TMPFILE, but missing pattern.\0";
pub const OPEN_USELESS_MODES_WARNING: &[u8; 49] =
    b"having redundant mode bits; but missing O_CREAT.\0";
pub const CALLED_WITH_STRING_BIGGER_BUFFER: &[u8; 44] =
    b"called with a string larger than the buffer\0";
pub const FD_COUNT_LARGE_GIVEN_BUFFER: &[u8; 42] = b"fd_count is greater than the given buffer\0";
pub const CALLED_WITH_SIZE_BIGGER_BUFFER: &[u8; 40] = b"called with bigger size than the buffer\0";
pub const OUTPUT_PARAMETER_BYTES : & [u8 ; 95] = b"the output parameter must be nullptr or a pointer to the buffer with >= FORTIFY_PATH_MAX bytes\0" ;
pub const SIZE_LARGER_THEN_DESTINATION_BUFFER: &[u8; 43] =
    b"the size is greater than the target buffer\0";
pub const CHAR_MIN: u32 = 0;
pub const CHAR_MAX: u32 = 255;
pub const CHAR_BIT: u32 = 8;
pub const SCHAR_MIN: i32 = -128;
pub const SCHAR_MAX: u32 = 127;
pub const UCHAR_MAX: u32 = 255;
pub const SHRT_MIN: i32 = -32768;
pub const SHRT_MAX: u32 = 32767;
pub const USHRT_MAX: u32 = 65535;
pub const INT_MIN: i32 = -2147483648;
pub const INT_MAX: u32 = 2147483647;
pub const UINT_MAX: u32 = 4294967295;
pub const LONG_MAX: u32 = 2147483647;
pub const ULONG_MAX: u32 = 4294967295;
pub const LLONG_MAX: u64 = 9223372036854775807;
pub const ULLONG_MAX: i32 = -1;
pub const MB_LEN_MAX: u32 = 4;
pub const PIPE_BUF: u32 = 4096;
pub const FILESIZEBITS: u32 = 64;
pub const NAME_MAX: u32 = 255;
pub const PATH_MAX: u32 = 4096;
pub const ARG_MAX: u32 = 131072;
pub const NGROUPS_MAX: u32 = 32;
pub const IOV_MAX: u32 = 1024;
pub const SYMLOOP_MAX: u32 = 40;
pub const WORD_BIT: u32 = 32;
pub const SSIZE_MAX: u32 = 2147483647;
pub const TZNAME_MAX: u32 = 6;
pub const TTY_NAME_MAX: u32 = 32;
pub const HOST_NAME_MAX: u32 = 255;
pub const LONG_BIT: u32 = 32;
pub const PTHREAD_KEYS_MAX: u32 = 128;
pub const PTHREAD_STACK_MIN: u32 = 2048;
pub const PTHREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const SEM_VALUE_MAX: u32 = 2147483647;
pub const SEM_NSEMS_MAX: u32 = 256;
pub const DELAYTIMER_MAX: u32 = 2147483647;
pub const MQ_PRIO_MAX: u32 = 32768;
pub const LOGIN_NAME_MAX: u32 = 256;
pub const BC_BASE_MAX: u32 = 99;
pub const BC_DIM_MAX: u32 = 2048;
pub const BC_SCALE_MAX: u32 = 99;
pub const BC_STRING_MAX: u32 = 1000;
pub const CHARCLASS_NAME_MAX: u32 = 14;
pub const COLL_WEIGHTS_MAX: u32 = 2;
pub const EXPR_NEST_MAX: u32 = 32;
pub const LINE_MAX: u32 = 4096;
pub const RE_DUP_MAX: u32 = 255;
pub const NL_ARGMAX: u32 = 9;
pub const NL_MSGMAX: u32 = 32767;
pub const NL_SETMAX: u32 = 255;
pub const NL_TEXTMAX: u32 = 2048;
pub const NZERO: u32 = 20;
pub const NL_LANGMAX: u32 = 32;
pub const NL_NMAX: u32 = 16;
pub const _POSIX_AIO_LISTIO_MAX: u32 = 2;
pub const _POSIX_AIO_MAX: u32 = 1;
pub const _POSIX_ARG_MAX: u32 = 4096;
pub const _POSIX_CHILD_MAX: u32 = 25;
pub const _POSIX_CLOCKRES_MIN: u32 = 20000000;
pub const _POSIX_DELAYTIMER_MAX: u32 = 32;
pub const _POSIX_HOST_NAME_MAX: u32 = 255;
pub const _POSIX_LINK_MAX: u32 = 8;
pub const _POSIX_LOGIN_NAME_MAX: u32 = 9;
pub const _POSIX_MAX_CANON: u32 = 255;
pub const _POSIX_MAX_INPUT: u32 = 255;
pub const _POSIX_MQ_OPEN_MAX: u32 = 8;
pub const _POSIX_MQ_PRIO_MAX: u32 = 32;
pub const _POSIX_NAME_MAX: u32 = 14;
pub const _POSIX_NGROUPS_MAX: u32 = 8;
pub const _POSIX_OPEN_MAX: u32 = 20;
pub const _POSIX_PATH_MAX: u32 = 256;
pub const _POSIX_PIPE_BUF: u32 = 512;
pub const _POSIX_RE_DUP_MAX: u32 = 255;
pub const _POSIX_RTSIG_MAX: u32 = 8;
pub const _POSIX_SEM_NSEMS_MAX: u32 = 256;
pub const _POSIX_SEM_VALUE_MAX: u32 = 32767;
pub const _POSIX_SIGQUEUE_MAX: u32 = 32;
pub const _POSIX_SSIZE_MAX: u32 = 32767;
pub const _POSIX_STREAM_MAX: u32 = 8;
pub const _POSIX_SS_REPL_MAX: u32 = 4;
pub const _POSIX_SYMLINK_MAX: u32 = 255;
pub const _POSIX_SYMLOOP_MAX: u32 = 8;
pub const _POSIX_THREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const _POSIX_THREAD_KEYS_MAX: u32 = 128;
pub const _POSIX_THREAD_THREADS_MAX: u32 = 64;
pub const _POSIX_TIMER_MAX: u32 = 32;
pub const _POSIX_TRACE_EVENT_NAME_MAX: u32 = 30;
pub const _POSIX_TRACE_NAME_MAX: u32 = 8;
pub const _POSIX_TRACE_SYS_MAX: u32 = 8;
pub const _POSIX_TRACE_USER_EVENT_MAX: u32 = 32;
pub const _POSIX_TTY_NAME_MAX: u32 = 9;
pub const _POSIX_TZNAME_MAX: u32 = 6;
pub const _POSIX2_BC_BASE_MAX: u32 = 99;
pub const _POSIX2_BC_DIM_MAX: u32 = 2048;
pub const _POSIX2_BC_SCALE_MAX: u32 = 99;
pub const _POSIX2_BC_STRING_MAX: u32 = 1000;
pub const _POSIX2_CHARCLASS_NAME_MAX: u32 = 14;
pub const _POSIX2_COLL_WEIGHTS_MAX: u32 = 2;
pub const _POSIX2_EXPR_NEST_MAX: u32 = 32;
pub const _POSIX2_LINE_MAX: u32 = 2048;
pub const _POSIX2_RE_DUP_MAX: u32 = 255;
pub const _XOPEN_IOV_MAX: u32 = 16;
pub const _XOPEN_NAME_MAX: u32 = 255;
pub const _XOPEN_PATH_MAX: u32 = 1024;
pub const HDF_BSP_ERR_START: i32 = -100;
pub const HDF_DEV_ERR_START: i32 = -200;
pub const HDF_WAIT_FOREVER: u32 = 4294967295;
pub const HDF_KILO_UNIT: u32 = 1000;
pub const HDF_LIBRARY_DIR: &[u8; 12] = b"/vendor/lib\0";
pub const HDF_ETC_DIR: &[u8; 12] = b"/vendor/etc\0";
pub const HDF_CONFIG_DIR: &[u8; 22] = b"/vendor/etc/hdfconfig\0";
pub const HDF_CHIP_PROD_CONFIG_DIR: &[u8; 25] = b"/chip_prod/etc/hdfconfig\0";
pub const HDF_MODULE_DIR: &[u8; 17] = b"/vendor/modules/\0";
pub const SCHED_OTHER: u32 = 0;
pub const SCHED_FIFO: u32 = 1;
pub const SCHED_RR: u32 = 2;
pub const SCHED_BATCH: u32 = 3;
pub const SCHED_IDLE: u32 = 5;
pub const SCHED_DEADLINE: u32 = 6;
pub const SCHED_RESET_ON_FORK: u32 = 1073741824;
pub const CSIGNAL: u32 = 255;
pub const CLONE_NEWTIME: u32 = 128;
pub const CLONE_VM: u32 = 256;
pub const CLONE_FS: u32 = 512;
pub const CLONE_FILES: u32 = 1024;
pub const CLONE_SIGHAND: u32 = 2048;
pub const CLONE_PIDFD: u32 = 4096;
pub const CLONE_PTRACE: u32 = 8192;
pub const CLONE_VFORK: u32 = 16384;
pub const CLONE_PARENT: u32 = 32768;
pub const CLONE_THREAD: u32 = 65536;
pub const CLONE_NEWNS: u32 = 131072;
pub const CLONE_SYSVSEM: u32 = 262144;
pub const CLONE_SETTLS: u32 = 524288;
pub const CLONE_PARENT_SETTID: u32 = 1048576;
pub const CLONE_CHILD_CLEARTID: u32 = 2097152;
pub const CLONE_DETACHED: u32 = 4194304;
pub const CLONE_UNTRACED: u32 = 8388608;
pub const CLONE_CHILD_SETTID: u32 = 16777216;
pub const CLONE_NEWCGROUP: u32 = 33554432;
pub const CLONE_NEWUTS: u32 = 67108864;
pub const CLONE_NEWIPC: u32 = 134217728;
pub const CLONE_NEWUSER: u32 = 268435456;
pub const CLONE_NEWPID: u32 = 536870912;
pub const CLONE_NEWNET: u32 = 1073741824;
pub const CLONE_IO: u32 = 2147483648;
pub const CPU_SETSIZE: u32 = 1024;
pub const CLOCKS_PER_SEC: u32 = 1000000;
pub const TIME_UTC: u32 = 1;
pub const CLOCK_REALTIME: u32 = 0;
pub const CLOCK_MONOTONIC: u32 = 1;
pub const CLOCK_PROCESS_CPUTIME_ID: u32 = 2;
pub const CLOCK_THREAD_CPUTIME_ID: u32 = 3;
pub const CLOCK_MONOTONIC_RAW: u32 = 4;
pub const CLOCK_REALTIME_COARSE: u32 = 5;
pub const CLOCK_MONOTONIC_COARSE: u32 = 6;
pub const CLOCK_BOOTTIME: u32 = 7;
pub const CLOCK_REALTIME_ALARM: u32 = 8;
pub const CLOCK_BOOTTIME_ALARM: u32 = 9;
pub const CLOCK_SGI_CYCLE: u32 = 10;
pub const CLOCK_TAI: u32 = 11;
pub const TIMER_ABSTIME: u32 = 1;
pub const PTHREAD_CREATE_JOINABLE: u32 = 0;
pub const PTHREAD_CREATE_DETACHED: u32 = 1;
pub const PTHREAD_MUTEX_NORMAL: u32 = 0;
pub const PTHREAD_MUTEX_DEFAULT: u32 = 0;
pub const PTHREAD_MUTEX_RECURSIVE: u32 = 1;
pub const PTHREAD_MUTEX_ERRORCHECK: u32 = 2;
pub const PTHREAD_MUTEX_DESTROYED: i32 = -1;
pub const PTHREAD_MUTEX_STALLED: u32 = 0;
pub const PTHREAD_MUTEX_ROBUST: u32 = 1;
pub const PTHREAD_PRIO_NONE: u32 = 0;
pub const PTHREAD_PRIO_INHERIT: u32 = 1;
pub const PTHREAD_PRIO_PROTECT: u32 = 2;
pub const PTHREAD_INHERIT_SCHED: u32 = 0;
pub const PTHREAD_EXPLICIT_SCHED: u32 = 1;
pub const PTHREAD_SCOPE_SYSTEM: u32 = 0;
pub const PTHREAD_SCOPE_PROCESS: u32 = 1;
pub const PTHREAD_PROCESS_PRIVATE: u32 = 0;
pub const PTHREAD_PROCESS_SHARED: u32 = 1;
pub const PTHREAD_ONCE_INIT: u32 = 0;
pub const PTHREAD_CANCEL_ENABLE: u32 = 0;
pub const PTHREAD_CANCEL_DISABLE: u32 = 1;
pub const PTHREAD_CANCEL_MASKED: u32 = 2;
pub const PTHREAD_CANCEL_DEFERRED: u32 = 0;
pub const PTHREAD_CANCEL_ASYNCHRONOUS: u32 = 1;
pub const PTHREAD_BARRIER_SERIAL_THREAD: i32 = -1;
pub const MAX_PRIORITY_NUM: u32 = 200;
pub const HOSTID_BITS: u32 = 8;
pub const DEVICEID_BITS: u32 = 16;
pub const DEVNODEID_BITS: u32 = 8;
pub const DEVNODEID_MASK: u32 = 255;
pub const DEVICEID_MASK: u32 = 65535;
pub const HDF_SYSEVENT: u32 = 64222;
pub const HDF_SYSEVENT_CLASS_POWER: u32 = 1;
pub const HDF_SYSEVENT_CLASS_MODULE: u32 = 2;
pub const LOG_DOMAIN: u32 = 0;
pub const DEV_SVCMGR_NODE: &[u8; 11] = b"devsvc_mgr\0";
pub const DEV_NODE_PATH: &[u8; 10] = b"/dev/hdf/\0";
pub const DEV_PATH: &[u8; 6] = b"/dev/\0";
pub const DEV_MGR_NODE: &[u8; 8] = b"dev_mgr\0";
pub const MAX_MODE_SIZE: u32 = 511;
pub const DEV_NODE_PATH_MODE: u32 = 488;
pub type wchar_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __ll: ::core::ffi::c_longlong,
    pub __ld: f64,
}
pub type size_t = ::core::ffi::c_uint;
pub type intmax_t = ::core::ffi::c_longlong;
pub type uintmax_t = ::core::ffi::c_ulonglong;
pub type int_fast8_t = i8;
pub type int_fast64_t = i64;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast64_t = u64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast16_t = i32;
pub type int_fast32_t = i32;
pub type uint_fast16_t = u32;
pub type uint_fast32_t = u32;
pub const POWER_STATE_DOZE_RESUME: HdfPowerState = 0;
pub const POWER_STATE_DOZE_SUSPEND: HdfPowerState = 1;
pub const POWER_STATE_RESUME: HdfPowerState = 2;
pub const POWER_STATE_SUSPEND: HdfPowerState = 3;
pub const POWER_STATE_MAX: HdfPowerState = 4;
pub type HdfPowerState = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __locale_struct {
    _unused: [u8; 0],
}
pub type locale_t = *mut __locale_struct;
pub const HDF_SUCCESS: HDF_STATUS = 0;
pub const HDF_FAILURE: HDF_STATUS = -1;
pub const HDF_ERR_NOT_SUPPORT: HDF_STATUS = -2;
pub const HDF_ERR_INVALID_PARAM: HDF_STATUS = -3;
pub const HDF_ERR_INVALID_OBJECT: HDF_STATUS = -4;
pub const HDF_ERR_MALLOC_FAIL: HDF_STATUS = -6;
pub const HDF_ERR_TIMEOUT: HDF_STATUS = -7;
pub const HDF_ERR_THREAD_CREATE_FAIL: HDF_STATUS = -10;
pub const HDF_ERR_QUEUE_FULL: HDF_STATUS = -15;
pub const HDF_ERR_DEVICE_BUSY: HDF_STATUS = -16;
pub const HDF_ERR_IO: HDF_STATUS = -17;
pub const HDF_ERR_BAD_FD: HDF_STATUS = -18;
pub const HDF_ERR_NOPERM: HDF_STATUS = -19;
pub const HDF_ERR_OUT_OF_RANGE: HDF_STATUS = -20;
pub const HDF_BSP_ERR_OP: HDF_STATUS = -101;
pub const HDF_ERR_BSP_PLT_API_ERR: HDF_STATUS = -102;
pub const HDF_PAL_ERR_DEV_CREATE: HDF_STATUS = -103;
pub const HDF_PAL_ERR_INNER: HDF_STATUS = -104;
pub const HDF_DEV_ERR_NO_MEMORY: HDF_STATUS = -201;
pub const HDF_DEV_ERR_NO_DEVICE: HDF_STATUS = -202;
pub const HDF_DEV_ERR_NO_DEVICE_SERVICE: HDF_STATUS = -203;
pub const HDF_DEV_ERR_DEV_INIT_FAIL: HDF_STATUS = -204;
pub const HDF_DEV_ERR_PUBLISH_FAIL: HDF_STATUS = -205;
pub const HDF_DEV_ERR_ATTACHDEV_FAIL: HDF_STATUS = -206;
pub const HDF_DEV_ERR_NODATA: HDF_STATUS = -207;
pub const HDF_DEV_ERR_NORANGE: HDF_STATUS = -208;
pub const HDF_DEV_ERR_OP: HDF_STATUS = -210;
pub const HDF_DEV_ERR_NETDOWN: HDF_STATUS = -211;
pub type HDF_STATUS = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DListHead {
    pub next: *mut DListHead,
    pub prev: *mut DListHead,
}
pub const SERVIE_STATUS_START: ServiceStatusType = 0;
pub const SERVIE_STATUS_CHANGE: ServiceStatusType = 1;
pub const SERVIE_STATUS_STOP: ServiceStatusType = 2;
pub const SERVIE_STATUS_REGISTER: ServiceStatusType = 3;
pub const SERVIE_STATUS_MAX: ServiceStatusType = 4;
pub type ServiceStatusType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServiceStatus {
    pub serviceName: *const ::core::ffi::c_char,
    pub deviceClass: u16,
    pub status: u16,
    pub info: *const ::core::ffi::c_char,
}
pub type OnServiceStatusReceived = ::core::option::Option<
    unsafe extern "C" fn(listener: *mut ServiceStatusListener, status: *mut ServiceStatus),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServiceStatusListener {
    pub callback: OnServiceStatusReceived,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBuf {
    _unused: [u8; 0],
}
pub const SERVIE_STATUS_LISTENER_NOTIFY: ServiceStatusListenerCmd = 0;
pub const SERVIE_STATUS_LISTENER_MAX: ServiceStatusListenerCmd = 1;
pub type ServiceStatusListenerCmd = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServStatListenerHolder {
    pub listenClass: u16,
    pub node: DListHead,
    pub index: u64,
    pub NotifyStatus: ::core::option::Option<
        unsafe extern "C" fn(
            holder: *mut ServStatListenerHolder,
            status: *mut ServiceStatus,
        ) -> i32,
    >,
    pub Recycle: ::core::option::Option<unsafe extern "C" fn(holder: *mut ServStatListenerHolder)>,
}
pub const DEVICE_CLASS_DEFAULT: DeviceClass = 1;
pub const DEVICE_CLASS_PLAT: DeviceClass = 2;
pub const DEVICE_CLASS_SENSOR: DeviceClass = 4;
pub const DEVICE_CLASS_INPUT: DeviceClass = 8;
pub const DEVICE_CLASS_DISPLAY: DeviceClass = 16;
pub const DEVICE_CLASS_AUDIO: DeviceClass = 32;
pub const DEVICE_CLASS_CAMERA: DeviceClass = 64;
pub const DEVICE_CLASS_USB: DeviceClass = 128;
pub const DEVICE_CLASS_USERAUTH: DeviceClass = 256;
pub const DEVICE_CLASS_HIMEDIACOMM: DeviceClass = 512;
pub const DEVICE_CLASS_MAX: DeviceClass = 1024;
pub type DeviceClass = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObject {
    pub objectId: i32,
}
pub type char16_t = u16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBufImpl {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfRemoteService {
    _unused: [u8; 0],
}
pub const SBUF_RAW: HdfSbufType = 0;
pub const SBUF_IPC: HdfSbufType = 1;
pub const SBUF_IPC_HW: HdfSbufType = 2;
pub const SBUF_TYPE_MAX: HdfSbufType = 3;
pub type HdfSbufType = ::core::ffi::c_uint;
pub type OnEventReceived = ::core::option::Option<
    unsafe extern "C" fn(
        priv_: *mut ::core::ffi::c_void,
        id: u32,
        data: *mut HdfSBuf,
    ) -> ::core::ffi::c_int,
>;
pub type OnDevEventReceive = ::core::option::Option<
    unsafe extern "C" fn(
        listener: *mut HdfDevEventlistener,
        service: *mut HdfIoService,
        id: u32,
        data: *mut HdfSBuf,
    ) -> ::core::ffi::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDevEventlistener {
    pub callBack: OnEventReceived,
    pub onReceive: OnDevEventReceive,
    pub listNode: DListHead,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoDispatcher {
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            service: *mut HdfObject,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoService {
    pub object: HdfObject,
    pub target: *mut HdfObject,
    pub dispatcher: *mut HdfIoDispatcher,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoServiceGroup {
    pub object: HdfObject,
}
pub type time_t = ::core::ffi::c_longlong;
pub type clockid_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: time_t,
    pub tv_nsec: ::core::ffi::c_long,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
}
impl timespec {
    #[inline]
    pub fn new_bitfield_1() -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __pthread {
    _unused: [u8; 0],
}
pub type pthread_t = *mut __pthread;
pub type pthread_once_t = ::core::ffi::c_int;
pub type pthread_key_t = ::core::ffi::c_uint;
pub type pthread_spinlock_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutexattr_t {
    pub __attr: ::core::ffi::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_condattr_t {
    pub __attr: ::core::ffi::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_barrierattr_t {
    pub __attr: ::core::ffi::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlockattr_t {
    pub __attr: [::core::ffi::c_uint; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sigset_t {
    pub __bits: [::core::ffi::c_ulong; 32usize],
}
pub type sigset_t = __sigset_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_attr_t {
    pub __u: pthread_attr_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_attr_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 9usize],
    pub __vi: [::core::ffi::c_int; 9usize],
    pub __s: [::core::ffi::c_ulong; 9usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_mutex_t {
    pub __u: pthread_mutex_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_mutex_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 6usize],
    pub __vi: [::core::ffi::c_int; 6usize],
    pub __p: [*mut ::core::ffi::c_void; 6usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_cond_t {
    pub __u: pthread_cond_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_cond_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 12usize],
    pub __vi: [::core::ffi::c_int; 12usize],
    pub __p: [*mut ::core::ffi::c_void; 12usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_rwlock_t {
    pub __u: pthread_rwlock_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_rwlock_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 8usize],
    pub __vi: [::core::ffi::c_int; 8usize],
    pub __p: [*mut ::core::ffi::c_void; 8usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_barrier_t {
    pub __u: pthread_barrier_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_barrier_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 5usize],
    pub __vi: [::core::ffi::c_int; 5usize],
    pub __p: [*mut ::core::ffi::c_void; 5usize],
}
pub type pid_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sched_param {
    pub sched_priority: ::core::ffi::c_int,
    pub __reserved1: ::core::ffi::c_int,
    pub __reserved2: [::core::ffi::c_long; 4usize],
    pub __reserved3: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cpu_set_t {
    pub __bits: [::core::ffi::c_ulong; 32usize],
}
pub type timer_t = *mut ::core::ffi::c_void;
pub type clock_t = ::core::ffi::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tm {
    pub tm_sec: ::core::ffi::c_int,
    pub tm_min: ::core::ffi::c_int,
    pub tm_hour: ::core::ffi::c_int,
    pub tm_mday: ::core::ffi::c_int,
    pub tm_mon: ::core::ffi::c_int,
    pub tm_year: ::core::ffi::c_int,
    pub tm_wday: ::core::ffi::c_int,
    pub tm_yday: ::core::ffi::c_int,
    pub tm_isdst: ::core::ffi::c_int,
    pub tm_gmtoff: ::core::ffi::c_long,
    pub tm_zone: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct itimerspec {
    pub it_interval: timespec,
    pub it_value: timespec,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sigevent {
    _unused: [u8; 0],
}
extern "C" {
    pub static mut daylight: ::core::ffi::c_int;
    pub static mut timezone: ::core::ffi::c_long;
    pub static mut getdate_err: ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __ptcb {
    pub __f: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>,
    pub __x: *mut ::core::ffi::c_void,
    pub __next: *mut __ptcb,
}
pub const SERVICE_POLICY_NONE: ServicePolicy = 0;
pub const SERVICE_POLICY_PUBLIC: ServicePolicy = 1;
pub const SERVICE_POLICY_CAPACITY: ServicePolicy = 2;
pub const SERVICE_POLICY_FRIENDLY: ServicePolicy = 3;
pub const SERVICE_POLICY_PRIVATE: ServicePolicy = 4;
pub const SERVICE_POLICY_INVALID: ServicePolicy = 5;
pub type ServicePolicy = ::core::ffi::c_uint;
pub const DEVICE_PRELOAD_ENABLE: DevicePreload = 0;
pub const DEVICE_PRELOAD_ENABLE_STEP2: DevicePreload = 1;
pub const DEVICE_PRELOAD_DISABLE: DevicePreload = 2;
pub const DEVICE_PRELOAD_INVALID: DevicePreload = 3;
pub type DevicePreload = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct HdfDeviceObject {
    pub service: *mut IDeviceIoService,
    pub property: *mut DeviceResourceNode,
    pub deviceClass: DeviceClass,
    pub priv_: *mut ::core::ffi::c_void,
    pub mutex: pthread_rwlock_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceIoClient {
    pub device: *mut HdfDeviceObject,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDeviceIoService {
    pub object: HdfObject,
    pub Open: ::core::option::Option<unsafe extern "C" fn(client: *mut HdfDeviceIoClient) -> i32>,
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            client: *mut HdfDeviceIoClient,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> i32,
    >,
    pub Release: ::core::option::Option<unsafe extern "C" fn(client: *mut HdfDeviceIoClient)>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SubscriberCallback {
    pub deviceObject: *mut HdfDeviceObject,
    pub OnServiceConnected: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject, service: *const HdfObject) -> i32,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDriverEntry {
    pub moduleVersion: i32,
    pub moduleName: *const ::core::ffi::c_char,
    pub Bind:
        ::core::option::Option<unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> i32>,
    pub Init:
        ::core::option::Option<unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> i32>,
    pub Release: ::core::option::Option<unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject)>,
}
pub type devid_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IHdfDevice {
    pub object: HdfObject,
    pub Attach: ::core::option::Option<
        unsafe extern "C" fn(
            device: *mut IHdfDevice,
            deviceNode: *mut HdfDeviceNode,
        ) -> ::core::ffi::c_int,
    >,
    pub Detach: ::core::option::Option<
        unsafe extern "C" fn(
            device: *mut IHdfDevice,
            deviceNode: *mut HdfDeviceNode,
        ) -> ::core::ffi::c_int,
    >,
    pub GetDeviceNode: ::core::option::Option<
        unsafe extern "C" fn(device: *mut IHdfDevice, devid: devid_t) -> *mut HdfDeviceNode,
    >,
    pub DetachWithDevid: ::core::option::Option<
        unsafe extern "C" fn(device: *mut IHdfDevice, devid: devid_t) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDevice {
    pub super_: IHdfDevice,
    pub node: DListHead,
    pub devNodes: DListHead,
    pub deviceId: devid_t,
    pub devidIndex: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSListNode {
    pub next: *mut HdfSListNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSList {
    pub root: *mut HdfSListNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSListIterator {
    pub stepOnNext: ::core::ffi::c_int,
    pub prev: *mut HdfSListNode,
    pub curr: *mut HdfSListNode,
}
pub type HdfSListDeleter = ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSListNode)>;
pub type HdfSListSearchComparer =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSListNode, arg2: u32) -> bool>;
pub type HdfSListAddComparer = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut HdfSListNode, arg2: *mut HdfSListNode) -> bool,
>;
pub const HDF_SERVICE_UNUSABLE: _bindgen_ty_1 = 0;
pub const HDF_SERVICE_USABLE: _bindgen_ty_1 = 1;
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const HDF_DEV_LOCAL_SERVICE: _bindgen_ty_2 = 0;
pub const HDF_DEV_REMOTE_SERVICE: _bindgen_ty_2 = 1;
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceInfo {
    pub node: HdfSListNode,
    pub isDynamic: bool,
    pub status: u16,
    pub deviceType: u16,
    pub deviceId: u32,
    pub policy: u16,
    pub priority: u16,
    pub preload: u16,
    pub permission: u16,
    pub moduleName: *const ::core::ffi::c_char,
    pub svcName: *const ::core::ffi::c_char,
    pub deviceMatchAttr: *const ::core::ffi::c_char,
    pub deviceName: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfPrivateInfo {
    pub length: u32,
    pub data: *const ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDriver {
    pub entry: *const HdfDriverEntry,
    pub type_: u16,
    pub bus: u16,
    pub node: DListHead,
    pub priv_: *mut ::core::ffi::c_void,
}
pub const KEVENT_POWER_SUSPEND: PowerKeventId = 0;
pub const KEVENT_POWER_DISPLAY_OFF: PowerKeventId = 1;
pub const KEVENT_POWER_RESUME: PowerKeventId = 2;
pub const KEVENT_POWER_DISPLAY_ON: PowerKeventId = 3;
pub const KEVENT_POWER_EVENT_MAX: PowerKeventId = 4;
pub type PowerKeventId = ::core::ffi::c_uint;
pub const KEVENT_MODULE_INSTALL: DriverModuleKeventId = 0;
pub const KEVENT_MODULE_REMOVE: DriverModuleKeventId = 1;
pub const KEVENT_MODULE_EVENT_MAX: DriverModuleKeventId = 2;
pub type DriverModuleKeventId = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSysEvent {
    pub eventClass: u64,
    pub syncToken: u64,
    pub eventid: u32,
    pub reserved: u32,
}
pub type HdfSysEventNotifierFn = ::core::option::Option<
    unsafe extern "C" fn(
        self_: *mut HdfSysEventNotifyNode,
        eventClass: u64,
        event: u32,
        content: *const ::core::ffi::c_char,
    ) -> i32,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSysEventNotifyNode {
    pub callback: HdfSysEventNotifierFn,
    pub listNode: DListHead,
    pub classFilter: u64,
}
pub const HDF_POWER_SYS_CTRL: PowerManagementMode = 0;
pub const HDF_POWER_DYNAMIC_CTRL: PowerManagementMode = 1;
pub const HDF_POWER_MODE_MAX: PowerManagementMode = 2;
pub type PowerManagementMode = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IPowerEventListener {
    pub DozeResume: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> ::core::ffi::c_int,
    >,
    pub DozeSuspend: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> ::core::ffi::c_int,
    >,
    pub Resume: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> ::core::ffi::c_int,
    >,
    pub Suspend: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevHostService {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDeviceNode {
    pub object: HdfObject,
    pub PublishService: ::core::option::Option<
        unsafe extern "C" fn(devNode: *mut HdfDeviceNode) -> ::core::ffi::c_int,
    >,
    pub RemoveService: ::core::option::Option<
        unsafe extern "C" fn(devNode: *mut HdfDeviceNode) -> ::core::ffi::c_int,
    >,
    pub LaunchNode: ::core::option::Option<
        unsafe extern "C" fn(devNode: *mut HdfDeviceNode) -> ::core::ffi::c_int,
    >,
    pub UnlaunchNode: ::core::option::Option<unsafe extern "C" fn(devNode: *mut HdfDeviceNode)>,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct HdfDeviceNode {
    pub super_: IDeviceNode,
    pub entry: DListHead,
    pub powerToken: *mut PowerStateToken,
    pub hostService: *mut DevHostService,
    pub deviceObject: HdfDeviceObject,
    pub token: *mut IHdfDeviceToken,
    pub driver: *mut HdfDriver,
    pub device: *mut HdfDevice,
    pub servName: *mut ::core::ffi::c_char,
    pub servInfo: *const ::core::ffi::c_char,
    pub driverName: *mut ::core::ffi::c_char,
    pub devId: devid_t,
    pub policy: u16,
    pub permission: u16,
    pub devStatus: u8,
    pub servStatus: bool,
    pub interfaceDesc: *mut ::core::ffi::c_char,
}
pub const DEVNODE_NONE: DevNodeStaus = 0;
pub const DEVNODE_INITED: DevNodeStaus = 1;
pub const DEVNODE_LAUNCHED: DevNodeStaus = 2;
pub type DevNodeStaus = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfServiceInfo {
    pub servName: *const ::core::ffi::c_char,
    pub servInfo: *const ::core::ffi::c_char,
    pub devClass: u16,
    pub devId: devid_t,
    pub interfaceDesc: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDevSvcManager {
    pub object: HdfObject,
    pub StartService: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevSvcManager) -> ::core::ffi::c_int,
    >,
    pub AddService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut HdfDeviceObject,
            arg3: *const HdfServiceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub UpdateService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut HdfDeviceObject,
            arg3: *const HdfServiceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub SubscribeService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: SubscriberCallback,
        ) -> ::core::ffi::c_int,
    >,
    pub UnsubscribeService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub GetService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> *mut HdfObject,
    >,
    pub GetObject: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> *mut HdfDeviceObject,
    >,
    pub RemoveService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: *const HdfDeviceObject,
        ),
    >,
    pub RegsterServListener: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut ServStatListenerHolder,
        ) -> ::core::ffi::c_int,
    >,
    pub UnregsterServListener: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevSvcManager, arg2: *mut ServStatListenerHolder),
    >,
    pub ListAllService:
        ::core::option::Option<unsafe extern "C" fn(arg1: *mut IDevSvcManager, arg2: *mut HdfSBuf)>,
    pub ListServiceByInterfaceDesc: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
pub const PSM_STATE_IDLE: HdfPsmState = 0;
pub const PSM_STATE_ACTIVE: HdfPsmState = 1;
pub const PSM_STATE_INACTIVE: HdfPsmState = 2;
pub type HdfPsmState = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IPowerStateToken {
    pub AcquireWakeLock: ::core::option::Option<unsafe extern "C" fn(arg1: *mut IPowerStateToken)>,
    pub ReleaseWakeLock: ::core::option::Option<unsafe extern "C" fn(arg1: *mut IPowerStateToken)>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IHdfDeviceToken {
    pub object: HdfObject,
    pub devid: devid_t,
    pub servName: *const ::core::ffi::c_char,
    pub deviceName: *const ::core::ffi::c_char,
}
pub const HDF_OBJECT_ID_DEVMGR_SERVICE: _bindgen_ty_3 = 0;
pub const HDF_OBJECT_ID_DEVSVC_MANAGER: _bindgen_ty_3 = 1;
pub const HDF_OBJECT_ID_DEVHOST_SERVICE: _bindgen_ty_3 = 2;
pub const HDF_OBJECT_ID_DRIVER_INSTALLER: _bindgen_ty_3 = 3;
pub const HDF_OBJECT_ID_DRIVER_LOADER: _bindgen_ty_3 = 4;
pub const HDF_OBJECT_ID_DEVICE: _bindgen_ty_3 = 5;
pub const HDF_OBJECT_ID_DEVICE_TOKEN: _bindgen_ty_3 = 6;
pub const HDF_OBJECT_ID_DEVICE_SERVICE: _bindgen_ty_3 = 7;
pub const HDF_OBJECT_ID_REMOTE_SERVICE: _bindgen_ty_3 = 8;
pub const HDF_OBJECT_ID_MAX: _bindgen_ty_3 = 9;
pub type _bindgen_ty_3 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObjectCreator {
    pub Create: ::core::option::Option<unsafe extern "C" fn() -> *mut HdfObject>,
    pub Release: ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfObject)>,
}
pub type va_list = u32;
pub const LOG_TYPE_MIN: LogType = 0;
pub const LOG_APP: LogType = 0;
pub const LOG_INIT: LogType = 1;
pub const LOG_CORE: LogType = 3;
pub const LOG_KMSG: LogType = 4;
pub const LOG_ONLY_PRERELEASE: LogType = 5;
pub const LOG_TYPE_MAX: LogType = 6;
pub type LogType = ::core::ffi::c_uint;
pub const LOG_LEVEL_MIN: LogLevel = 0;
pub const LOG_DEBUG: LogLevel = 3;
pub const LOG_INFO: LogLevel = 4;
pub const LOG_WARN: LogLevel = 5;
pub const LOG_ERROR: LogLevel = 6;
pub const LOG_FATAL: LogLevel = 7;
pub const LOG_LEVEL_MAX: LogLevel = 8;
pub type LogLevel = ::core::ffi::c_uint;
pub type LogCallback = ::core::option::Option<
    unsafe extern "C" fn(
        type_: LogType,
        level: LogLevel,
        domain: ::core::ffi::c_uint,
        tag: *const ::core::ffi::c_char,
        msg: *const ::core::ffi::c_char,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDevHostMgr {
    pub hosts: DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfHostType {
    pub devHostName: *const ::core::ffi::c_char,
    pub priority: u16,
    pub devices: DListHead,
    pub hostEntry: DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceType {
    pub deviceNodes: DListHead,
    pub deviceEntry: DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceNodeType {
    pub policy: u16,
    pub priority: u16,
    pub preload: u16,
    pub permission: u16,
    pub moduleName: *const ::core::ffi::c_char,
    pub svcName: *const ::core::ffi::c_char,
    pub deviceName: *const ::core::ffi::c_char,
    pub deviceMatchAttr: *const ::core::ffi::c_char,
    pub deviceNodeEntry: DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDevHostService {
    pub object: HdfObject,
    pub AddDevice: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            devInfo: *const HdfDeviceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub DelDevice: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            devId: devid_t,
        ) -> ::core::ffi::c_int,
    >,
    pub StartService: ::core::option::Option<
        unsafe extern "C" fn(hostService: *mut IDevHostService) -> ::core::ffi::c_int,
    >,
    pub PmNotify: ::core::option::Option<
        unsafe extern "C" fn(service: *mut IDevHostService, powerState: u32) -> ::core::ffi::c_int,
    >,
    pub Dump: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MapNode {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Map {
    pub nodes: *mut *mut MapNode,
    pub nodeSize: u32,
    pub bucketSize: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalMutex {
    pub realMutex: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevHostServiceClnt {
    pub node: DListHead,
    pub devices: HdfSList,
    pub unloadDevInfos: HdfSList,
    pub dynamicDevInfos: HdfSList,
    pub deviceHashMap: *mut Map,
    pub hostService: *mut IDevHostService,
    pub hostLock: OsalMutex,
    pub devCount: u16,
    pub hostId: u16,
    pub hostPid: ::core::ffi::c_int,
    pub hostName: *const ::core::ffi::c_char,
    pub stopFlag: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevSvcRecord {
    pub entry: DListHead,
    pub key: u32,
    pub value: *mut HdfDeviceObject,
    pub servName: *const ::core::ffi::c_char,
    pub servInfo: *const ::core::ffi::c_char,
    pub devClass: u16,
    pub devId: devid_t,
    pub interfaceDesc: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct IDevmgrService {
    pub base: HdfObject,
    pub object: HdfDeviceObject,
    pub AttachDeviceHost: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            arg2: u16,
            arg3: *mut IDevHostService,
        ) -> ::core::ffi::c_int,
    >,
    pub AttachDevice: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            arg2: *mut IHdfDeviceToken,
        ) -> ::core::ffi::c_int,
    >,
    pub DetachDevice: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevmgrService, arg2: devid_t) -> ::core::ffi::c_int,
    >,
    pub LoadDevice: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            arg2: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub UnloadDevice: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            arg2: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub StartService: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevmgrService) -> ::core::ffi::c_int,
    >,
    pub PowerStateChange: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            pEvent: HdfPowerState,
        ) -> ::core::ffi::c_int,
    >,
    pub ListAllDevice: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevmgrService, arg2: *mut HdfSBuf) -> ::core::ffi::c_int,
    >,
}
pub const SVCMGR_REGISTER_LISTENER: SvcMgrIoCmd = 0;
pub const SVCMGR_UNREGISTER_LISTENER: SvcMgrIoCmd = 1;
pub type SvcMgrIoCmd = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ISvcMgrIoservice {
    pub RegisterServiceStatusListener: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *mut ISvcMgrIoservice,
            listener: *mut ServiceStatusListener,
            deviceClass: u16,
        ) -> i32,
    >,
    pub UnregisterServiceStatusListener: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *mut ISvcMgrIoservice,
            listener: *mut ServiceStatusListener,
        ) -> i32,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IoServiceStatusListener {
    pub svcstatListener: ServiceStatusListener,
    pub ioservListener: HdfDevEventlistener,
    pub node: DListHead,
    pub deviceClass: u16,
}
pub const DEVMGR_LOAD_SERVICE: DevMgrCmd = 0;
pub const DEVMGR_UNLOAD_SERVICE: DevMgrCmd = 1;
pub const DEVMGR_GET_SERVICE: DevMgrCmd = 2;
pub const DEVMGR_LIST_ALL_SERVICE: DevMgrCmd = 3;
pub const DEVMGR_LIST_ALL_DEVICE: DevMgrCmd = 4;
pub type DevMgrCmd = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfWriteReadBuf {
    pub writeSize: u32,
    pub writeConsumed: u32,
    pub writeBuffer: u64,
    pub readSize: u32,
    pub readConsumed: u32,
    pub readBuffer: u64,
    pub cmdCode: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceNode {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PowerStateToken {
    pub _address: u8,
}

// ============================================================
// C2R: TU-pinned type supplements (from stage1 `.i` truth)
// ============================================================
pub mod __c2r_tu_types_src_svcmgr_ioservice {
    include!("__c2r_generated/tu_types_src_svcmgr_ioservice.rs");
}
pub use __c2r_tu_types_src_svcmgr_ioservice::{SvcMgrIoservice};


// ============================================================
// Auto-generated Defensive Opaque Types
// These types were found in function signatures or variable
// declarations but were not generated by bindgen.
// ============================================================

/// Opaque placeholder for external type `clock_getres`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clock_getres {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `clock_gettime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clock_gettime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `clock_nanosleep`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clock_nanosleep {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `clock_settime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clock_settime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `ctime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ctime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `ctime_r`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ctime_r {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `difftime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct difftime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `gmtime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gmtime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `gmtime_r`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gmtime_r {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `localtime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct localtime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `localtime_r`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct localtime_r {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `mktime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mktime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `nanosleep`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nanosleep {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_cond_timedwait`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_cond_timedwait {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_mutex_timedlock`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutex_timedlock {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_rwlock_timedrdlock`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlock_timedrdlock {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_rwlock_timedwrlock`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlock_timedwrlock {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_timedjoin_np`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_timedjoin_np {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `sched_rr_get_interval`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sched_rr_get_interval {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `stime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct stime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `time`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct time {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `timegm`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timegm {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `timer_gettime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timer_gettime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `timer_settime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timer_settime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `timespec_get`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec_get {
    _private: [u8; 0],
}

// ============================================================
// Common Constants (自动追加)
// ============================================================

pub const PTHREAD_MUTEX_INITIALIZER: pthread_mutex_t = unsafe { ::core::mem::transmute([0u8; ::core::mem::size_of::<pthread_mutex_t>()]) };
pub const PTHREAD_COND_INITIALIZER: pthread_cond_t = unsafe { ::core::mem::transmute([0u8; ::core::mem::size_of::<pthread_cond_t>()]) };
pub const PTHREAD_RWLOCK_INITIALIZER: pthread_rwlock_t = unsafe { ::core::mem::transmute([0u8; ::core::mem::size_of::<pthread_rwlock_t>()]) };
pub const __PTHREAD_MUTEX_INITIALIZER: pthread_mutex_t = unsafe { ::core::mem::transmute([0u8; ::core::mem::size_of::<pthread_mutex_t>()]) };
pub const __PTHREAD_COND_INITIALIZER: pthread_cond_t = unsafe { ::core::mem::transmute([0u8; ::core::mem::size_of::<pthread_cond_t>()]) };
pub const __PTHREAD_RWLOCK_INITIALIZER: pthread_rwlock_t = unsafe { ::core::mem::transmute([0u8; ::core::mem::size_of::<pthread_rwlock_t>()]) };
pub const __PTHREAD_ONCE_INIT: pthread_once_t = unsafe { ::core::mem::transmute([0u8; ::core::mem::size_of::<pthread_once_t>()]) };
pub const EINVAL: i32 = 22;
pub const ENOMEM: i32 = 12;
pub const ENOENT: i32 = 2;
pub const EEXIST: i32 = 17;
pub const EBUSY: i32 = 16;
pub const EAGAIN: i32 = 11;
pub const ETIMEDOUT: i32 = 110;
pub const ENODEV: i32 = 19;
pub const EFAULT: i32 = 14;
pub const ENOSYS: i32 = 38;
pub const ERANGE: i32 = 34;
pub const ENOTCONN: i32 = 107;
pub const TRUE: i32 = 1;
pub const FALSE: i32 = 0;
pub const SOFTBUS_OK: i32 = 0;
pub const SOFTBUS_ERR: i32 = -1;
pub const SOFTBUS_NOT_IMPLEMENT: i32 = -2;
pub const SOFTBUS_INVALID_PARAM: i32 = -3;
pub const SOFTBUS_MEM_ERR: i32 = -4;
pub const SOFTBUS_MALLOC_ERR: i32 = -5;
pub const SOFTBUS_PERMISSION_DENIED: i32 = -6;
pub const SOFTBUS_NETWORK_ERR: i32 = -7;
pub const LOS_OK: i32 = 0;
pub const LOS_NOK: i32 = -1;
pub const LOS_ERRNO_BASE: u32 = 0x02000000;
pub const AUDIO_FORMAT_TYPE_PCM_16_BIT: i32 = 1;
pub const AUDIO_FORMAT_TYPE_PCM_8_BIT: i32 = 0;
pub const AUDIO_FORMAT_TYPE_PCM_24_BIT: i32 = 2;
pub const AUDIO_FORMAT_TYPE_PCM_32_BIT: i32 = 3;
