/* automatically generated by rust-bindgen 0.72.1 */

pub type size_t = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn strcmp(
        arg1: *const ::core::ffi::c_char,
        arg2: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn strlen(arg1: *const ::core::ffi::c_char) -> size_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DListHead {
    pub next: *mut DListHead,
    pub prev: *mut DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioCtrlElemId {
    pub cardServiceName: *const ::core::ffi::c_char,
    pub iface: i32,
    pub itemName: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioCtrlElemInfo {
    pub id: AudioCtrlElemId,
    pub count: u32,
    pub type_: i32,
    pub min: i32,
    pub max: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioCtrlElemValue {
    pub id: AudioCtrlElemId,
    pub value: [u32; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioEnumKcontrol {
    pub reg: u32,
    pub reg2: u32,
    pub shiftLeft: u8,
    pub shiftRight: u8,
    pub max: u32,
    pub mask: u32,
    pub texts: *const *const ::core::ffi::c_char,
    pub values: *const u32,
    pub sapm: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioMixerControl {
    pub min: u32,
    pub max: u32,
    pub platformMax: i32,
    pub mask: u32,
    pub reg: u32,
    pub rreg: u32,
    pub shift: u32,
    pub rshift: u32,
    pub invert: u32,
    pub value: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioKcontrol {
    pub name: *mut ::core::ffi::c_char,
    pub iface: i32,
    pub Info: ::core::option::Option<
        unsafe extern "C" fn(
            kcontrol: *const AudioKcontrol,
            elemInfo: *mut AudioCtrlElemInfo,
        ) -> i32,
    >,
    pub Get: ::core::option::Option<
        unsafe extern "C" fn(
            kcontrol: *const AudioKcontrol,
            elemValue: *mut AudioCtrlElemValue,
        ) -> i32,
    >,
    pub Set: ::core::option::Option<
        unsafe extern "C" fn(
            kcontrol: *const AudioKcontrol,
            elemValue: *const AudioCtrlElemValue,
        ) -> i32,
    >,
    pub privateData: *mut ::core::ffi::c_void,
    pub pri: *mut ::core::ffi::c_void,
    pub privateValue: ::core::ffi::c_ulong,
    pub list: DListHead,
}
pub const DEVICE_CLASS_DEFAULT: DeviceClass = 1;
pub const DEVICE_CLASS_PLAT: DeviceClass = 2;
pub const DEVICE_CLASS_SENSOR: DeviceClass = 4;
pub const DEVICE_CLASS_INPUT: DeviceClass = 8;
pub const DEVICE_CLASS_DISPLAY: DeviceClass = 16;
pub const DEVICE_CLASS_AUDIO: DeviceClass = 32;
pub const DEVICE_CLASS_CAMERA: DeviceClass = 64;
pub const DEVICE_CLASS_USB: DeviceClass = 128;
pub const DEVICE_CLASS_USERAUTH: DeviceClass = 256;
pub const DEVICE_CLASS_HIMEDIACOMM: DeviceClass = 512;
pub const DEVICE_CLASS_MAX: DeviceClass = 1024;
pub type DeviceClass = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObject {
    pub objectId: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBuf {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceObject {
    pub service: *mut IDeviceIoService,
    pub property: *const DeviceResourceNode,
    pub deviceClass: DeviceClass,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceIoClient {
    pub device: *mut HdfDeviceObject,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDeviceIoService {
    pub object: HdfObject,
    pub Open: ::core::option::Option<unsafe extern "C" fn(client: *mut HdfDeviceIoClient) -> i32>,
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            client: *mut HdfDeviceIoClient,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> i32,
    >,
    pub Release: ::core::option::Option<unsafe extern "C" fn(client: *mut HdfDeviceIoClient)>,
}
pub const LOG_TYPE_MIN: LogType = 0;
pub const LOG_INIT: LogType = 1;
pub const LOG_CORE: LogType = 3;
pub const LOG_TYPE_MAX: LogType = 4;
pub type LogType = ::core::ffi::c_uint;
pub const LOG_DEBUG: LogLevel = 3;
pub const LOG_INFO: LogLevel = 4;
pub const LOG_WARN: LogLevel = 5;
pub const LOG_ERROR: LogLevel = 6;
pub const LOG_FATAL: LogLevel = 7;
pub type LogLevel = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn HiLogPrint(
        type_: LogType,
        level: LogLevel,
        domain: ::core::ffi::c_uint,
        tag: *const ::core::ffi::c_char,
        fmt: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceAttr {
    pub name: *const ::core::ffi::c_char,
    pub value: *const ::core::ffi::c_char,
    pub next: *mut DeviceResourceAttr,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceNode {
    pub name: *const ::core::ffi::c_char,
    pub hashValue: u32,
    pub attrData: *mut DeviceResourceAttr,
    pub parent: *mut DeviceResourceNode,
    pub child: *mut DeviceResourceNode,
    pub sibling: *mut DeviceResourceNode,
}
unsafe extern "C" {
    pub fn OsalMemCalloc(size: size_t) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn OsalMemFree(mem: *mut ::core::ffi::c_void);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalMutex {
    pub realMutex: *mut ::core::ffi::c_void,
}
pub type errno_t = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn memset_s(
        dest: *mut ::core::ffi::c_void,
        destMax: size_t,
        c: ::core::ffi::c_int,
        count: size_t,
    ) -> errno_t;
}
unsafe extern "C" {
    pub fn memcpy_s(
        dest: *mut ::core::ffi::c_void,
        destMax: size_t,
        src: *const ::core::ffi::c_void,
        count: size_t,
    ) -> errno_t;
}
unsafe extern "C" {
    pub fn snprintf_s(
        strDest: *mut ::core::ffi::c_char,
        destMax: size_t,
        count: size_t,
        format: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
}
pub const AUDIO_FORMAT_TYPE_PCM_8_BIT: AudioFormat = 1;
pub const AUDIO_FORMAT_TYPE_PCM_16_BIT: AudioFormat = 2;
pub const AUDIO_FORMAT_TYPE_PCM_24_BIT: AudioFormat = 3;
pub const AUDIO_FORMAT_TYPE_PCM_32_BIT: AudioFormat = 4;
pub const AUDIO_FORMAT_TYPE_AAC_MAIN: AudioFormat = 16777217;
pub const AUDIO_FORMAT_TYPE_AAC_LC: AudioFormat = 16777218;
pub const AUDIO_FORMAT_TYPE_AAC_LD: AudioFormat = 16777219;
pub const AUDIO_FORMAT_TYPE_AAC_ELD: AudioFormat = 16777220;
pub const AUDIO_FORMAT_TYPE_AAC_HE_V1: AudioFormat = 16777221;
pub const AUDIO_FORMAT_TYPE_AAC_HE_V2: AudioFormat = 16777222;
pub const AUDIO_FORMAT_TYPE_G711A: AudioFormat = 33554433;
pub const AUDIO_FORMAT_TYPE_G711U: AudioFormat = 33554434;
pub const AUDIO_FORMAT_TYPE_G726: AudioFormat = 33554435;
pub type AudioFormat = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioConfigData {
    pub cardServiceName: *const ::core::ffi::c_char,
    pub codecName: *const ::core::ffi::c_char,
    pub platformName: *const ::core::ffi::c_char,
    pub cpuDaiName: *const ::core::ffi::c_char,
    pub codecDaiName: *const ::core::ffi::c_char,
    pub dspName: *const ::core::ffi::c_char,
    pub dspDaiName: *const ::core::ffi::c_char,
}
pub const AUDIO_SAPM_TURN_STANDBY_LATER: AudioSapmTurnStandbyMode = 0;
pub const AUDIO_SAPM_TURN_STANDBY_NOW: AudioSapmTurnStandbyMode = 1;
pub const AUDIO_SAPM_TURN_STANDBY_BUTT: AudioSapmTurnStandbyMode = 2;
pub type AudioSapmTurnStandbyMode = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioCard {
    pub device: *mut HdfDeviceObject,
    pub rtd: *mut AudioRuntimeDeivces,
    pub configData: AudioConfigData,
    pub sapmComponents: *const AudioSapmComponent,
    pub sapmComponentsNum: i32,
    pub sapmRoutes: *const AudioSapmRoute,
    pub sapmRoutesNum: i32,
    pub list: DListHead,
    pub controls: DListHead,
    pub components: DListHead,
    pub paths: DListHead,
    pub sapmDirty: DListHead,
    pub standbyMode: AudioSapmTurnStandbyMode,
    pub time: u64,
    pub sapmSleepState: bool,
    pub sapmStandbyState: bool,
    pub sapmMonitorState: bool,
    pub sapmStandbyStartTimeFlag: bool,
    pub sapmSleepStartTimeFlag: bool,
}
pub const AUDIO_CAPTURE_STREAM: AudioStreamType = 0;
pub const AUDIO_RENDER_STREAM: AudioStreamType = 1;
pub type AudioStreamType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioPcmStream {
    pub portDirection: u64,
    pub formats: u64,
    pub rates: u64,
    pub rateMin: u64,
    pub rateMax: u64,
    pub channelsMin: u64,
    pub channelsMax: u64,
    pub bufferBytesMax: u64,
    pub periodBytesMin: u64,
    pub periodBytesMax: u64,
    pub periodsMin: u64,
    pub periodsMax: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioPortInfo {
    pub render: AudioPcmStream,
    pub capture: AudioPcmStream,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PcmInfo {
    pub streamType: AudioStreamType,
    pub channels: u32,
    pub rate: u32,
    pub bitWidth: u32,
    pub frameSize: u32,
    pub isBigEndian: bool,
    pub isSignedData: bool,
    pub startThreshold: u32,
    pub stopThreshold: u32,
    pub silenceThreshold: u32,
    pub totalStreamSize: u32,
    pub interleaved: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioPcmHwParams {
    pub streamType: AudioStreamType,
    pub channels: u32,
    pub rate: u32,
    pub periodSize: u32,
    pub periodCount: u32,
    pub format: AudioFormat,
    pub cardServiceName: *const ::core::ffi::c_char,
    pub period: u32,
    pub frameSize: u32,
    pub isBigEndian: bool,
    pub isSignedData: bool,
    pub startThreshold: u32,
    pub stopThreshold: u32,
    pub silenceThreshold: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioMmapData {
    pub memoryAddress: *mut ::core::ffi::c_void,
    pub memoryFd: i32,
    pub totalBufferFrames: i32,
    pub transferFrameSize: i32,
    pub isShareable: i32,
    pub offset: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioRuntimeDeivces {
    pub codec: *mut CodecDevice,
    pub platform: *mut PlatformDevice,
    pub codecDai: *mut DaiDevice,
    pub cpuDai: *mut DaiDevice,
    pub dsp: *mut DspDevice,
    pub dspDai: *mut DaiDevice,
    pub complete: u8,
    pub frameBits: u32,
    pub dmaArea: *mut u8,
    pub bufferSize: ::core::ffi::c_ulong,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CodecDevice {
    pub devCodecName: *const ::core::ffi::c_char,
    pub devData: *mut CodecData,
    pub device: *mut HdfDeviceObject,
    pub list: DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CodecData {
    pub drvCodecName: *const ::core::ffi::c_char,
    pub Init: ::core::option::Option<
        unsafe extern "C" fn(audioCard: *mut AudioCard, codec: *const CodecDevice) -> i32,
    >,
    pub Read: ::core::option::Option<
        unsafe extern "C" fn(codec: *const CodecDevice, reg: u32, value: *mut u32) -> i32,
    >,
    pub Write: ::core::option::Option<
        unsafe extern "C" fn(codec: *const CodecDevice, reg: u32, value: u32) -> i32,
    >,
    pub controls: *mut AudioKcontrol,
    pub numControls: ::core::ffi::c_int,
    pub sapmComponents: *mut AudioSapmComponent,
    pub numSapmComponent: ::core::ffi::c_int,
    pub sapmRoutes: *const AudioSapmRoute,
    pub numSapmRoutes: ::core::ffi::c_int,
    pub virtualAddress: ::core::ffi::c_ulong,
    pub regConfig: *mut AudioRegCfgData,
    pub regCfgGroup: *mut *mut AudioRegCfgGroupNode,
    pub mutex: OsalMutex,
    pub privateParam: *mut ::core::ffi::c_void,
}
pub const AUDIO_RSET_GROUP: AudioRegOpsType = 0;
pub const AUDIO_INIT_GROUP: AudioRegOpsType = 1;
pub const AUDIO_CTRL_PATAM_GROUP: AudioRegOpsType = 2;
pub const AUDIO_CTRL_PATAM_MUX_GROUP: AudioRegOpsType = 3;
pub const AUDIO_CTRL_SAPM_PATAM_GROUP: AudioRegOpsType = 4;
pub const AUDIO_CTRL_SAPM_PATAM_MUX_GROUP: AudioRegOpsType = 5;
pub const AUDIO_DAI_STARTUP_PATAM_GROUP: AudioRegOpsType = 6;
pub const AUDIO_DAI_PATAM_GROUP: AudioRegOpsType = 7;
pub const AUDIO_DAI_TRIGGER_GROUP: AudioRegOpsType = 8;
pub const AUDIO_CTRL_CFG_GROUP: AudioRegOpsType = 9;
pub const AUDIO_SAPM_COMP_GROUP: AudioRegOpsType = 10;
pub const AUDIO_SAPM_CFG_GROUP: AudioRegOpsType = 11;
pub const AUDIO_GROUP_MAX: AudioRegOpsType = 12;
pub type AudioRegOpsType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioIdInfo {
    pub chipName: *const ::core::ffi::c_char,
    pub chipIdRegister: u32,
    pub chipIdSize: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioControlConfig {
    pub arrayIndex: u16,
    pub iface: u16,
    pub type_: u16,
    pub enable: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioAddrConfig {
    pub addr: u32,
    pub value: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioSapmCtrlConfig {
    pub sapmType: u8,
    pub compNameIndex: u16,
    pub reg: u32,
    pub mask: u32,
    pub shift: u8,
    pub invert: u8,
    pub kcontrolNews: u32,
    pub kcontrolsNum: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioEnumCtrlConfig {
    pub reg: u32,
    pub reg2: u32,
    pub shiftLeft: u8,
    pub shiftRight: u8,
    pub max: u32,
    pub mask: u32,
    pub texts: u32,
    pub values: u32,
    pub sapm: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioRegCfgGroupNode {
    pub itemNum: u8,
    pub groupIndex: AudioRegOpsType,
    pub addrCfgItem: *mut AudioAddrConfig,
    pub regCfgItem: *mut AudioMixerControl,
    pub regEnumCfgItem: *mut AudioEnumCtrlConfig,
    pub ctrlCfgItem: *mut AudioControlConfig,
    pub sapmCompItem: *mut AudioSapmCtrlConfig,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioRegCfgData {
    pub audioIdInfo: AudioIdInfo,
    pub audioRegParams: [*mut AudioRegCfgGroupNode; 12usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DaiDevice {
    pub devDaiName: *const ::core::ffi::c_char,
    pub devData: *mut DaiData,
    pub device: *mut HdfDeviceObject,
    pub list: DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioDaiOps {
    pub Startup: ::core::option::Option<
        unsafe extern "C" fn(audioCard: *const AudioCard, dai: *const DaiDevice) -> i32,
    >,
    pub HwParams: ::core::option::Option<
        unsafe extern "C" fn(audioCard: *const AudioCard, param: *const AudioPcmHwParams) -> i32,
    >,
    pub Trigger: ::core::option::Option<
        unsafe extern "C" fn(
            audioCard: *const AudioCard,
            cmd: ::core::ffi::c_int,
            dai: *const DaiDevice,
        ) -> i32,
    >,
    pub Shutdown: ::core::option::Option<
        unsafe extern "C" fn(audioCard: *const AudioCard, dai: *const DaiDevice) -> i32,
    >,
    pub MuteStream: ::core::option::Option<
        unsafe extern "C" fn(
            audioCard: *const AudioCard,
            dai: *const DaiDevice,
            mute: bool,
            direction: i32,
        ) -> i32,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DaiData {
    pub drvDaiName: *const ::core::ffi::c_char,
    pub DaiInit: ::core::option::Option<
        unsafe extern "C" fn(audioCard: *mut AudioCard, dai: *const DaiDevice) -> i32,
    >,
    pub Read: ::core::option::Option<
        unsafe extern "C" fn(dai: *const DaiDevice, reg: u32, value: *mut u32) -> i32,
    >,
    pub Write: ::core::option::Option<
        unsafe extern "C" fn(dai: *const DaiDevice, reg: u32, value: u32) -> i32,
    >,
    pub ops: *const AudioDaiOps,
    pub portInfo: AudioPortInfo,
    pub pcmInfo: PcmInfo,
    pub controls: *mut AudioKcontrol,
    pub numControls: ::core::ffi::c_int,
    pub daiInitFlag: bool,
    pub regVirtualAddr: ::core::ffi::c_ulong,
    pub regConfig: *mut AudioRegCfgData,
    pub regCfgGroup: *mut *mut AudioRegCfgGroupNode,
    pub mutex: OsalMutex,
    pub privateParam: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DspDevice {
    pub devDspName: *const ::core::ffi::c_char,
    pub devData: *mut DspData,
    pub device: *mut HdfDeviceObject,
    pub list: DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DspData {
    pub drvDspName: *const ::core::ffi::c_char,
    pub DspInit: ::core::option::Option<unsafe extern "C" fn(dsp: *const DspDevice) -> i32>,
    pub Read: ::core::option::Option<
        unsafe extern "C" fn(
            dsp: *const DspDevice,
            msgs: *const ::core::ffi::c_void,
            len: u32,
        ) -> i32,
    >,
    pub Write: ::core::option::Option<
        unsafe extern "C" fn(
            dsp: *const DspDevice,
            msgs: *const ::core::ffi::c_void,
            len: u32,
        ) -> i32,
    >,
    pub Decode: ::core::option::Option<
        unsafe extern "C" fn(
            audioCard: *const AudioCard,
            buf: *const u8,
            dsp: *const DspDevice,
        ) -> i32,
    >,
    pub Encode: ::core::option::Option<
        unsafe extern "C" fn(
            audioCard: *const AudioCard,
            buf: *const u8,
            dsp: *const DspDevice,
        ) -> i32,
    >,
    pub Equalizer: ::core::option::Option<
        unsafe extern "C" fn(
            audioCard: *const AudioCard,
            buf: *const u8,
            dsp: *const DspDevice,
        ) -> i32,
    >,
}
pub const PCM_STOP: PcmStatus = 0;
pub const PCM_PAUSE: PcmStatus = 1;
pub const PCM_START: PcmStatus = 2;
pub type PcmStatus = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CircleBufInfo {
    pub cirBufSize: u32,
    pub trafBufSize: u32,
    pub period: u32,
    pub periodSize: u32,
    pub periodCount: u32,
    pub phyAddr: ::core::ffi::c_ulong,
    pub virtAddr: *mut u32,
    pub wbufOffSet: u32,
    pub wptrOffSet: u32,
    pub rbufOffSet: u32,
    pub rptrOffSet: u32,
    pub runStatus: PcmStatus,
    pub chnId: u32,
    pub enable: u32,
    pub buffMutex: OsalMutex,
    pub framesPosition: u32,
    pub pointer: u32,
    pub periodsMax: u32,
    pub periodsMin: u32,
    pub cirBufMax: u32,
    pub curTrafSize: u32,
    pub oneMsBytes: u32,
    pub trafCompCount: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PlatformData {
    pub drvPlatformName: *const ::core::ffi::c_char,
    pub PlatformInit: ::core::option::Option<
        unsafe extern "C" fn(audioCard: *const AudioCard, platform: *const PlatformDevice) -> i32,
    >,
    pub ops: *mut AudioDmaOps,
    pub renderBufInfo: CircleBufInfo,
    pub captureBufInfo: CircleBufInfo,
    pub renderPcmInfo: PcmInfo,
    pub capturePcmInfo: PcmInfo,
    pub platformInitFlag: bool,
    pub mmapData: AudioMmapData,
    pub mmapLoopCount: u32,
    pub dmaPrv: *mut ::core::ffi::c_void,
    pub regConfig: *mut AudioRegCfgData,
    pub regCfgGroup: *mut *mut AudioRegCfgGroupNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioDmaOps {
    pub DmaBufAlloc: ::core::option::Option<
        unsafe extern "C" fn(platformData: *mut PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaBufFree: ::core::option::Option<
        unsafe extern "C" fn(platformData: *mut PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaRequestChannel: ::core::option::Option<
        unsafe extern "C" fn(platformData: *const PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaConfigChannel: ::core::option::Option<
        unsafe extern "C" fn(platformData: *const PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaPrep: ::core::option::Option<
        unsafe extern "C" fn(platformData: *const PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaSubmit: ::core::option::Option<
        unsafe extern "C" fn(platformData: *const PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaPending: ::core::option::Option<
        unsafe extern "C" fn(platformData: *mut PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaPause: ::core::option::Option<
        unsafe extern "C" fn(platformData: *mut PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaResume: ::core::option::Option<
        unsafe extern "C" fn(platformData: *const PlatformData, streamType: AudioStreamType) -> i32,
    >,
    pub DmaPointer: ::core::option::Option<
        unsafe extern "C" fn(
            platformData: *mut PlatformData,
            streamType: AudioStreamType,
            pointer: *mut u32,
        ) -> i32,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PlatformDevice {
    pub devPlatformName: *const ::core::ffi::c_char,
    pub devData: *mut PlatformData,
    pub device: *mut HdfDeviceObject,
    pub list: DListHead,
}
unsafe extern "C" {
    pub fn AudioCodecRegUpdate(codec: *mut CodecDevice, mixerCtrl: *mut AudioMixerControl) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecMuxRegUpdate(
        codec: *mut CodecDevice,
        enumCtrl: *mut AudioEnumKcontrol,
        value: *const u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioUpdateCodecRegBits(
        codec: *mut CodecDevice,
        reg: u32,
        mask: u32,
        shift: u32,
        value: u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioKcontrolGetCodec(kcontrol: *const AudioKcontrol) -> *mut CodecDevice;
}
unsafe extern "C" {
    pub fn AudioAddControl(
        audioCard: *const AudioCard,
        ctl: *const AudioKcontrol,
    ) -> *mut AudioKcontrol;
}
unsafe extern "C" {
    pub fn AudioCodecReadReg(codec: *const CodecDevice, reg: u32, val: *mut u32) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecGetCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *mut AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecGetEnumCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *mut AudioCtrlElemValue,
    ) -> i32;
}
pub const AUDIO_SAPM_INPUT: AudioSapmType = 0;
pub const AUDIO_SAPM_OUTPUT: AudioSapmType = 1;
pub const AUDIO_SAPM_MUX: AudioSapmType = 2;
pub const AUDIO_SAPM_DEMUX: AudioSapmType = 3;
pub const AUDIO_SAPM_VIRT_MUX: AudioSapmType = 4;
pub const AUDIO_SAPM_VALUE_MUX: AudioSapmType = 5;
pub const AUDIO_SAPM_MIXER: AudioSapmType = 6;
pub const AUDIO_SAPM_MIXER_NAMED_CTRL: AudioSapmType = 7;
pub const AUDIO_SAPM_PGA: AudioSapmType = 8;
pub const AUDIO_SAPM_OUT_DRV: AudioSapmType = 9;
pub const AUDIO_SAPM_ADC: AudioSapmType = 10;
pub const AUDIO_SAPM_DAC: AudioSapmType = 11;
pub const AUDIO_SAPM_MICBIAS: AudioSapmType = 12;
pub const AUDIO_SAPM_MIC: AudioSapmType = 13;
pub const AUDIO_SAPM_HP: AudioSapmType = 14;
pub const AUDIO_SAPM_SPK: AudioSapmType = 15;
pub const AUDIO_SAPM_LINE: AudioSapmType = 16;
pub const AUDIO_SAPM_ANALOG_SWITCH: AudioSapmType = 17;
pub const AUDIO_SAPM_VMID: AudioSapmType = 18;
pub const AUDIO_SAPM_PRE: AudioSapmType = 19;
pub const AUDIO_SAPM_POST: AudioSapmType = 20;
pub const AUDIO_SAPM_SUPPLY: AudioSapmType = 21;
pub const AUDIO_SAPM_REGULATOR_SUPPLY: AudioSapmType = 22;
pub const AUDIO_SAPM_CLOCK_SUPPLY: AudioSapmType = 23;
pub const AUDIO_SAPM_AIF_IN: AudioSapmType = 24;
pub const AUDIO_SAPM_AIF_OUT: AudioSapmType = 25;
pub const AUDIO_SAPM_SIGGEN: AudioSapmType = 26;
pub const AUDIO_SAPM_SINK: AudioSapmType = 27;
pub type AudioSapmType = ::core::ffi::c_uint;
pub const AUDIO_BIAS_OFF: AudioBiasLevel = 0;
pub const AUDIO_BIAS_STANDBY: AudioBiasLevel = 1;
pub const AUDIO_BIAS_PREPARE: AudioBiasLevel = 2;
pub const AUDIO_BIAS_ON: AudioBiasLevel = 3;
pub type AudioBiasLevel = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioSapmContext {
    pub componentNum: i32,
    pub biasLevel: AudioBiasLevel,
    pub suspendBiasLevel: AudioBiasLevel,
    pub codec: *mut CodecDevice,
    pub platform: *mut PlatformDevice,
    pub card: *mut AudioCard,
    pub targetBiasLevel: AudioBiasLevel,
    pub list: DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioSapmComponent {
    pub sapmType: AudioSapmType,
    pub componentName: *mut ::core::ffi::c_char,
    pub streamName: *mut ::core::ffi::c_char,
    pub sapm: *mut AudioSapmContext,
    pub codec: *mut CodecDevice,
    pub platform: *mut PlatformDevice,
    pub reg: u32,
    pub shift: u8,
    pub invert: u8,
    pub mask: u32,
    pub connected: u8,
    pub external: u8,
    pub active: u8,
    pub newPower: u8,
    pub power: u8,
    pub newCpt: u8,
    pub eventFlags: u16,
    pub Event: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut AudioSapmComponent,
            arg2: *mut AudioKcontrol,
            arg3: i32,
        ) -> i32,
    >,
    pub PowerCheck:
        ::core::option::Option<unsafe extern "C" fn(arg1: *const AudioSapmComponent) -> i32>,
    pub kcontrolsNum: i32,
    pub kcontrolNews: *mut AudioKcontrol,
    pub kcontrols: *mut *mut AudioKcontrol,
    pub list: DListHead,
    pub sources: DListHead,
    pub sinks: DListHead,
    pub powerList: DListHead,
    pub dirty: DListHead,
    pub PowerClockOp:
        ::core::option::Option<unsafe extern "C" fn(arg1: *mut AudioSapmComponent) -> i32>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AudioSapmRoute {
    pub sink: *const ::core::ffi::c_char,
    pub control: *const ::core::ffi::c_char,
    pub source: *const ::core::ffi::c_char,
    pub Connected: ::core::option::Option<
        unsafe extern "C" fn(source: *mut AudioSapmComponent, sink: *mut AudioSapmComponent) -> u32,
    >,
}
unsafe extern "C" {
    pub fn OsalSleep(sec: u32);
}
pub const OSAL_THREAD_PRI_LOW: OSAL_THREAD_PRIORITY = 0;
pub const OSAL_THREAD_PRI_DEFAULT: OSAL_THREAD_PRIORITY = 1;
pub const OSAL_THREAD_PRI_HIGH: OSAL_THREAD_PRIORITY = 2;
pub const OSAL_THREAD_PRI_HIGHEST: OSAL_THREAD_PRIORITY = 3;
pub type OSAL_THREAD_PRIORITY = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalThreadParam {
    pub name: *mut ::core::ffi::c_char,
    pub stackSize: size_t,
    pub priority: OSAL_THREAD_PRIORITY,
    pub policy: ::core::ffi::c_int,
}
pub type OsalThreadEntry = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void) -> ::core::ffi::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalThread {
    pub realThread: *mut ::core::ffi::c_void,
}
unsafe extern "C" {
    pub fn OsalThreadCreate(
        thread: *mut OsalThread,
        threadEntry: OsalThreadEntry,
        entryPara: *mut ::core::ffi::c_void,
    ) -> i32;
}
unsafe extern "C" {
    pub fn OsalThreadStart(thread: *mut OsalThread, param: *const OsalThreadParam) -> i32;
}
unsafe extern "C" {
    pub fn OsalThreadDestroy(thread: *mut OsalThread) -> i32;
}
