/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn VerifyIntegrityChunk(
        digestAlgorithm: i32,
        fp: i32,
        signInfo: *const SignatureInfo,
        actualDigest: *const HapBuf,
    ) -> bool;
}
unsafe extern "C" {
    pub fn GetDigestAlgorithmId(signAlgorithm: u32) -> i32;
}
