/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn PKCS7_ParseSignedData(
        buf: *const ::core::ffi::c_uchar,
        bufLen: size_t,
        pkcs7: *mut Pkcs7,
    ) -> i32;
}
unsafe extern "C" {
    pub fn PKCS7_VerifyCertsChain(pkcs7: *const Pkcs7) -> i32;
}
unsafe extern "C" {
    pub fn PKCS7_FreeRes(pkcs7: *mut Pkcs7);
}
unsafe extern "C" {
    pub fn PKCS7_GetContentData(
        pkcs7: *const Pkcs7,
        data: *mut *mut ::core::ffi::c_uchar,
        dataLen: *mut size_t,
    ) -> i32;
}
unsafe extern "C" {
    pub fn PKCS7_GetDigestInSignerAuthAttr(
        signer: *const SignerInfo,
        dig: *mut *mut ::core::ffi::c_uchar,
        digLen: *mut size_t,
    ) -> i32;
}
unsafe extern "C" {
    pub fn PKCS7_GetSignerAuthAttr(
        signer: *const SignerInfo,
        data: *mut *mut ::core::ffi::c_uchar,
        dataLen: *mut size_t,
    ) -> i32;
}
unsafe extern "C" {
    pub fn PKCS7_VerifySignerSignature(pkcs7: *const Pkcs7, calcDigest: PKCS7_CalcDigest) -> i32;
}
unsafe extern "C" {
    pub fn PKCS7_GetAllSignersResolvedInfo(pkcs7: *const Pkcs7) -> *mut SignersResovedInfo;
}
unsafe extern "C" {
    pub fn PKCS7_FreeAllSignersResolvedInfo(sri: *mut SignersResovedInfo);
}
unsafe extern "C" {
    pub fn PKCS7_EnableDebugMode(mode: bool) -> i32;
}
unsafe extern "C" {
    pub fn PKCS7_GetSignerSignningCertSubject(
        signer: *const SignerInfo,
        subject: *mut ::core::ffi::c_char,
        subjectLen: size_t,
    ) -> i32;
}
unsafe extern "C" {
    pub fn PKCS7_GetSignerSignningCertIssuer(
        signer: *const SignerInfo,
        issuer: *mut ::core::ffi::c_char,
        issuerLen: size_t,
    ) -> i32;
}
