//! Compatibility / Fallback Layer
//!
//! This module is auto-generated to keep the translated project compiling.
//!
//! Design goals:
//! - Centralize placeholders and shims in ONE place (easy to audit & remove later).
//! - Keep function bodies as close to translated semantics as possible.
//!
//! IMPORTANT:
//! - Items here may be placeholders (value/layout unknown). Always review before relying on semantics.

#![allow(dead_code)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]

/// Minimal FFI prelude (for legacy skeletons that import `crate::compat::ffi::*`).
pub mod ffi {
    pub use core::ffi::*;
}

// === C2R_COMPAT_PLACEHOLDERS_BEGIN ===
// (auto-appended placeholders will be inserted here)
// === C2R_COMPAT_PLACEHOLDERS_END ===

// === C2R_EXTERN_TYPES_BEGIN ===
// Auto-generated by C2R step 2.55 (bindgen allowlist extern prelude).
// Only includes missing type items required by extern decls below.
pub type LogLevel = ::core::ffi::c_uint;

pub type LogType = ::core::ffi::c_uint;

pub type clockid_t = ::core::ffi::c_int;

pub type errno_t = ::core::ffi::c_int;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutexattr_t {
    pub __attr: ::core::ffi::c_uint,
}

pub type pthread_spinlock_t = ::core::ffi::c_int;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sem_t {
    pub __val: [::core::ffi::c_int; 8usize],
}

pub type time_t = ::core::ffi::c_longlong;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: time_t,
    pub tv_nsec: ::core::ffi::c_long,
}

// === C2R_EXTERN_TYPES_END ===

// === C2R_EXTERN_DECLS_BEGIN ===
// Auto-generated extern decls (C2R step 2.55; bindgen allowlist).
// Source: archived_runs/deepseek-v4-pro-ohos10-full-0613-1/raw/framework_output/intermediate/posix__1b7f59c68bbc/workspace/.preprocessed/*.i (preprocessed translation units)
// Details: archived_runs/deepseek-v4-pro-ohos10-full-0613-1/raw/framework_output/intermediate/posix__1b7f59c68bbc/workspace/repair_history/posix__1b7f59c68bbc/translate_by_qwen3_coder/_manual_fix/extern_decls_from_bindgen_allowlist.json
#[allow(improper_ctypes)]
#[allow(non_snake_case)]
extern "C" {
    pub fn HiLogPrint(type_: LogType, level: LogLevel, domain: ::core::ffi::c_uint, tag: *const ::core::ffi::c_char, fmt: *const ::core::ffi::c_char, ...) -> ::core::ffi::c_int;
    pub fn __errno_location() -> *mut ::core::ffi::c_int;
    pub fn clock_gettime(arg1: clockid_t, arg2: *mut timespec) -> ::core::ffi::c_int;
    pub fn free(arg1: *mut ::core::ffi::c_void);
    pub fn malloc(arg1: crate::types::size_t) -> *mut ::core::ffi::c_void;
    pub fn memset_s(dest: *mut ::core::ffi::c_void, destMax: crate::types::size_t, c: ::core::ffi::c_int, count: crate::types::size_t) -> errno_t;
    pub fn nanosleep(arg1: *const timespec, arg2: *mut timespec) -> ::core::ffi::c_int;
    pub fn posix_memalign(arg1: *mut *mut ::core::ffi::c_void, arg2: crate::types::size_t, arg3: crate::types::size_t) -> ::core::ffi::c_int;
    pub fn pthread_attr_destroy(arg1: *mut crate::types::pthread_attr_t) -> ::core::ffi::c_int;
    pub fn pthread_attr_getschedparam(arg1: *const crate::types::pthread_attr_t, arg2: *mut crate::types::sched_param) -> ::core::ffi::c_int;
    pub fn pthread_attr_init(arg1: *mut crate::types::pthread_attr_t) -> ::core::ffi::c_int;
    pub fn pthread_attr_setinheritsched(arg1: *mut crate::types::pthread_attr_t, arg2: ::core::ffi::c_int) -> ::core::ffi::c_int;
    pub fn pthread_attr_setschedparam(arg1: *mut crate::types::pthread_attr_t, arg2: *const crate::types::sched_param) -> ::core::ffi::c_int;
    pub fn pthread_attr_setschedpolicy(arg1: *mut crate::types::pthread_attr_t, arg2: ::core::ffi::c_int) -> ::core::ffi::c_int;
    pub fn pthread_attr_setstacksize(arg1: *mut crate::types::pthread_attr_t, arg2: crate::types::size_t) -> ::core::ffi::c_int;
    pub fn pthread_create(arg1: *mut crate::types::pthread_t, arg2: *const crate::types::pthread_attr_t, arg3: ::core::option::Option< unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void) -> *mut ::core::ffi::c_void, >, arg4: *mut ::core::ffi::c_void) -> ::core::ffi::c_int;
    pub fn pthread_detach(arg1: crate::types::pthread_t) -> ::core::ffi::c_int;
    pub fn pthread_mutex_destroy(arg1: *mut crate::types::pthread_mutex_t) -> ::core::ffi::c_int;
    pub fn pthread_mutex_init(arg1: *mut crate::types::pthread_mutex_t, arg2: *const pthread_mutexattr_t) -> ::core::ffi::c_int;
    pub fn pthread_mutex_lock(arg1: *mut crate::types::pthread_mutex_t) -> ::core::ffi::c_int;
    pub fn pthread_mutex_timedlock(arg1: *mut crate::types::pthread_mutex_t, arg2: *const timespec) -> ::core::ffi::c_int;
    pub fn pthread_mutex_unlock(arg1: *mut crate::types::pthread_mutex_t) -> ::core::ffi::c_int;
    pub fn pthread_setname_np(arg1: crate::types::pthread_t, arg2: *const ::core::ffi::c_char) -> ::core::ffi::c_int;
    pub fn pthread_spin_destroy(arg1: *mut pthread_spinlock_t) -> ::core::ffi::c_int;
    pub fn pthread_spin_init(arg1: *mut pthread_spinlock_t, arg2: ::core::ffi::c_int) -> ::core::ffi::c_int;
    pub fn pthread_spin_lock(arg1: *mut pthread_spinlock_t) -> ::core::ffi::c_int;
    pub fn pthread_spin_unlock(arg1: *mut pthread_spinlock_t) -> ::core::ffi::c_int;
    pub fn sem_destroy(arg1: *mut sem_t) -> ::core::ffi::c_int;
    pub fn sem_init(arg1: *mut sem_t, arg2: ::core::ffi::c_int, arg3: ::core::ffi::c_uint) -> ::core::ffi::c_int;
    pub fn sem_post(arg1: *mut sem_t) -> ::core::ffi::c_int;
    pub fn sem_timedwait(arg1: *mut sem_t, arg2: *const timespec) -> ::core::ffi::c_int;
    pub fn sem_wait(arg1: *mut sem_t) -> ::core::ffi::c_int;
    pub fn sleep(arg1: ::core::ffi::c_uint) -> ::core::ffi::c_uint;
    pub fn strncpy_s(strDest: *mut ::core::ffi::c_char, destMax: crate::types::size_t, strSrc: *const ::core::ffi::c_char, count: crate::types::size_t) -> errno_t;
}
// === C2R_EXTERN_DECLS_END ===

// === C2R_ACCESSOR_SHIMS_BEGIN ===
// (auto-appended accessor shim declarations will be inserted here)
// === C2R_ACCESSOR_SHIMS_END ===
