/* automatically generated by rust-bindgen 0.72.1 */
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unused)]

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::core::slice::from_raw_parts(self.as_ptr(), len)
    }
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const _REDIR_TIME64: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST64_MAX: i32 = -1;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INTMAX_MIN: i64 = -9223372036854775808;
pub const INTMAX_MAX: u64 = 9223372036854775807;
pub const UINTMAX_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const INT_FAST16_MIN: i32 = -2147483648;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST16_MAX: u32 = 2147483647;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const UINT_FAST16_MAX: u32 = 4294967295;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const INTPTR_MIN: i32 = -2147483648;
pub const INTPTR_MAX: u32 = 2147483647;
pub const UINTPTR_MAX: u32 = 4294967295;
pub const PTRDIFF_MIN: i32 = -2147483648;
pub const PTRDIFF_MAX: u32 = 2147483647;
pub const SIZE_MAX: u32 = 4294967295;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const FORTIFY_LONG_MAX: u32 = 2147483647;
pub const FORTIFY_SSIZE_MAX: u32 = 2147483647;
pub const FORTIFY_PATH_MAX: u32 = 4096;
pub const FORTIFY_RUNTIME_ERROR_PREFIX: &[u8; 29] = b"Musl Fortify runtime error: \0";
pub const OPEN_TOO_MANY_ARGS_ERROR: &[u8; 29] = b"There are too many arguments\0";
pub const OPEN_TOO_FEW_ARGS_ERROR: &[u8; 57] =
    b"invoking with O_CREAT or O_TMPFILE, but missing pattern.\0";
pub const OPEN_USELESS_MODES_WARNING: &[u8; 49] =
    b"having redundant mode bits; but missing O_CREAT.\0";
pub const CALLED_WITH_STRING_BIGGER_BUFFER: &[u8; 44] =
    b"called with a string larger than the buffer\0";
pub const FD_COUNT_LARGE_GIVEN_BUFFER: &[u8; 42] = b"fd_count is greater than the given buffer\0";
pub const CALLED_WITH_SIZE_BIGGER_BUFFER: &[u8; 40] = b"called with bigger size than the buffer\0";
pub const OUTPUT_PARAMETER_BYTES : & [u8 ; 95] = b"the output parameter must be nullptr or a pointer to the buffer with >= FORTIFY_PATH_MAX bytes\0" ;
pub const SIZE_LARGER_THEN_DESTINATION_BUFFER: &[u8; 43] =
    b"the size is greater than the target buffer\0";
pub const CHAR_MIN: u32 = 0;
pub const CHAR_MAX: u32 = 255;
pub const CHAR_BIT: u32 = 8;
pub const SCHAR_MIN: i32 = -128;
pub const SCHAR_MAX: u32 = 127;
pub const UCHAR_MAX: u32 = 255;
pub const SHRT_MIN: i32 = -32768;
pub const SHRT_MAX: u32 = 32767;
pub const USHRT_MAX: u32 = 65535;
pub const INT_MIN: i32 = -2147483648;
pub const INT_MAX: u32 = 2147483647;
pub const UINT_MAX: u32 = 4294967295;
pub const LONG_MAX: u32 = 2147483647;
pub const ULONG_MAX: u32 = 4294967295;
pub const LLONG_MAX: u64 = 9223372036854775807;
pub const ULLONG_MAX: i32 = -1;
pub const MB_LEN_MAX: u32 = 4;
pub const PIPE_BUF: u32 = 4096;
pub const FILESIZEBITS: u32 = 64;
pub const NAME_MAX: u32 = 255;
pub const PATH_MAX: u32 = 4096;
pub const ARG_MAX: u32 = 131072;
pub const NGROUPS_MAX: u32 = 32;
pub const IOV_MAX: u32 = 1024;
pub const SYMLOOP_MAX: u32 = 40;
pub const WORD_BIT: u32 = 32;
pub const SSIZE_MAX: u32 = 2147483647;
pub const TZNAME_MAX: u32 = 6;
pub const TTY_NAME_MAX: u32 = 32;
pub const HOST_NAME_MAX: u32 = 255;
pub const LONG_BIT: u32 = 32;
pub const PTHREAD_KEYS_MAX: u32 = 128;
pub const PTHREAD_STACK_MIN: u32 = 2048;
pub const PTHREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const SEM_VALUE_MAX: u32 = 2147483647;
pub const SEM_NSEMS_MAX: u32 = 256;
pub const DELAYTIMER_MAX: u32 = 2147483647;
pub const MQ_PRIO_MAX: u32 = 32768;
pub const LOGIN_NAME_MAX: u32 = 256;
pub const BC_BASE_MAX: u32 = 99;
pub const BC_DIM_MAX: u32 = 2048;
pub const BC_SCALE_MAX: u32 = 99;
pub const BC_STRING_MAX: u32 = 1000;
pub const CHARCLASS_NAME_MAX: u32 = 14;
pub const COLL_WEIGHTS_MAX: u32 = 2;
pub const EXPR_NEST_MAX: u32 = 32;
pub const LINE_MAX: u32 = 4096;
pub const RE_DUP_MAX: u32 = 255;
pub const NL_ARGMAX: u32 = 9;
pub const NL_MSGMAX: u32 = 32767;
pub const NL_SETMAX: u32 = 255;
pub const NL_TEXTMAX: u32 = 2048;
pub const NZERO: u32 = 20;
pub const NL_LANGMAX: u32 = 32;
pub const NL_NMAX: u32 = 16;
pub const _POSIX_AIO_LISTIO_MAX: u32 = 2;
pub const _POSIX_AIO_MAX: u32 = 1;
pub const _POSIX_ARG_MAX: u32 = 4096;
pub const _POSIX_CHILD_MAX: u32 = 25;
pub const _POSIX_CLOCKRES_MIN: u32 = 20000000;
pub const _POSIX_DELAYTIMER_MAX: u32 = 32;
pub const _POSIX_HOST_NAME_MAX: u32 = 255;
pub const _POSIX_LINK_MAX: u32 = 8;
pub const _POSIX_LOGIN_NAME_MAX: u32 = 9;
pub const _POSIX_MAX_CANON: u32 = 255;
pub const _POSIX_MAX_INPUT: u32 = 255;
pub const _POSIX_MQ_OPEN_MAX: u32 = 8;
pub const _POSIX_MQ_PRIO_MAX: u32 = 32;
pub const _POSIX_NAME_MAX: u32 = 14;
pub const _POSIX_NGROUPS_MAX: u32 = 8;
pub const _POSIX_OPEN_MAX: u32 = 20;
pub const _POSIX_PATH_MAX: u32 = 256;
pub const _POSIX_PIPE_BUF: u32 = 512;
pub const _POSIX_RE_DUP_MAX: u32 = 255;
pub const _POSIX_RTSIG_MAX: u32 = 8;
pub const _POSIX_SEM_NSEMS_MAX: u32 = 256;
pub const _POSIX_SEM_VALUE_MAX: u32 = 32767;
pub const _POSIX_SIGQUEUE_MAX: u32 = 32;
pub const _POSIX_SSIZE_MAX: u32 = 32767;
pub const _POSIX_STREAM_MAX: u32 = 8;
pub const _POSIX_SS_REPL_MAX: u32 = 4;
pub const _POSIX_SYMLINK_MAX: u32 = 255;
pub const _POSIX_SYMLOOP_MAX: u32 = 8;
pub const _POSIX_THREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const _POSIX_THREAD_KEYS_MAX: u32 = 128;
pub const _POSIX_THREAD_THREADS_MAX: u32 = 64;
pub const _POSIX_TIMER_MAX: u32 = 32;
pub const _POSIX_TRACE_EVENT_NAME_MAX: u32 = 30;
pub const _POSIX_TRACE_NAME_MAX: u32 = 8;
pub const _POSIX_TRACE_SYS_MAX: u32 = 8;
pub const _POSIX_TRACE_USER_EVENT_MAX: u32 = 32;
pub const _POSIX_TTY_NAME_MAX: u32 = 9;
pub const _POSIX_TZNAME_MAX: u32 = 6;
pub const _POSIX2_BC_BASE_MAX: u32 = 99;
pub const _POSIX2_BC_DIM_MAX: u32 = 2048;
pub const _POSIX2_BC_SCALE_MAX: u32 = 99;
pub const _POSIX2_BC_STRING_MAX: u32 = 1000;
pub const _POSIX2_CHARCLASS_NAME_MAX: u32 = 14;
pub const _POSIX2_COLL_WEIGHTS_MAX: u32 = 2;
pub const _POSIX2_EXPR_NEST_MAX: u32 = 32;
pub const _POSIX2_LINE_MAX: u32 = 2048;
pub const _POSIX2_RE_DUP_MAX: u32 = 255;
pub const _XOPEN_IOV_MAX: u32 = 16;
pub const _XOPEN_NAME_MAX: u32 = 255;
pub const _XOPEN_PATH_MAX: u32 = 1024;
pub const HDF_BSP_ERR_START: i32 = -100;
pub const HDF_DEV_ERR_START: i32 = -200;
pub const HDF_WAIT_FOREVER: u32 = 4294967295;
pub const HDF_KILO_UNIT: u32 = 1000;
pub const HDF_LIBRARY_DIR: &[u8; 12] = b"/vendor/lib\0";
pub const HDF_ETC_DIR: &[u8; 12] = b"/vendor/etc\0";
pub const HDF_CONFIG_DIR: &[u8; 22] = b"/vendor/etc/hdfconfig\0";
pub const HDF_CHIP_PROD_CONFIG_DIR: &[u8; 25] = b"/chip_prod/etc/hdfconfig\0";
pub const HDF_MODULE_DIR: &[u8; 17] = b"/vendor/modules/\0";
pub const HOSTID_BITS: u32 = 8;
pub const DEVICEID_BITS: u32 = 16;
pub const DEVNODEID_BITS: u32 = 8;
pub const DEVNODEID_MASK: u32 = 255;
pub const DEVICEID_MASK: u32 = 65535;
pub const SCHED_OTHER: u32 = 0;
pub const SCHED_FIFO: u32 = 1;
pub const SCHED_RR: u32 = 2;
pub const SCHED_BATCH: u32 = 3;
pub const SCHED_IDLE: u32 = 5;
pub const SCHED_DEADLINE: u32 = 6;
pub const SCHED_RESET_ON_FORK: u32 = 1073741824;
pub const CSIGNAL: u32 = 255;
pub const CLONE_NEWTIME: u32 = 128;
pub const CLONE_VM: u32 = 256;
pub const CLONE_FS: u32 = 512;
pub const CLONE_FILES: u32 = 1024;
pub const CLONE_SIGHAND: u32 = 2048;
pub const CLONE_PIDFD: u32 = 4096;
pub const CLONE_PTRACE: u32 = 8192;
pub const CLONE_VFORK: u32 = 16384;
pub const CLONE_PARENT: u32 = 32768;
pub const CLONE_THREAD: u32 = 65536;
pub const CLONE_NEWNS: u32 = 131072;
pub const CLONE_SYSVSEM: u32 = 262144;
pub const CLONE_SETTLS: u32 = 524288;
pub const CLONE_PARENT_SETTID: u32 = 1048576;
pub const CLONE_CHILD_CLEARTID: u32 = 2097152;
pub const CLONE_DETACHED: u32 = 4194304;
pub const CLONE_UNTRACED: u32 = 8388608;
pub const CLONE_CHILD_SETTID: u32 = 16777216;
pub const CLONE_NEWCGROUP: u32 = 33554432;
pub const CLONE_NEWUTS: u32 = 67108864;
pub const CLONE_NEWIPC: u32 = 134217728;
pub const CLONE_NEWUSER: u32 = 268435456;
pub const CLONE_NEWPID: u32 = 536870912;
pub const CLONE_NEWNET: u32 = 1073741824;
pub const CLONE_IO: u32 = 2147483648;
pub const CPU_SETSIZE: u32 = 1024;
pub const CLOCKS_PER_SEC: u32 = 1000000;
pub const TIME_UTC: u32 = 1;
pub const CLOCK_REALTIME: u32 = 0;
pub const CLOCK_MONOTONIC: u32 = 1;
pub const CLOCK_PROCESS_CPUTIME_ID: u32 = 2;
pub const CLOCK_THREAD_CPUTIME_ID: u32 = 3;
pub const CLOCK_MONOTONIC_RAW: u32 = 4;
pub const CLOCK_REALTIME_COARSE: u32 = 5;
pub const CLOCK_MONOTONIC_COARSE: u32 = 6;
pub const CLOCK_BOOTTIME: u32 = 7;
pub const CLOCK_REALTIME_ALARM: u32 = 8;
pub const CLOCK_BOOTTIME_ALARM: u32 = 9;
pub const CLOCK_SGI_CYCLE: u32 = 10;
pub const CLOCK_TAI: u32 = 11;
pub const TIMER_ABSTIME: u32 = 1;
pub const PTHREAD_CREATE_JOINABLE: u32 = 0;
pub const PTHREAD_CREATE_DETACHED: u32 = 1;
pub const PTHREAD_MUTEX_NORMAL: u32 = 0;
pub const PTHREAD_MUTEX_DEFAULT: u32 = 0;
pub const PTHREAD_MUTEX_RECURSIVE: u32 = 1;
pub const PTHREAD_MUTEX_ERRORCHECK: u32 = 2;
pub const PTHREAD_MUTEX_DESTROYED: i32 = -1;
pub const PTHREAD_MUTEX_STALLED: u32 = 0;
pub const PTHREAD_MUTEX_ROBUST: u32 = 1;
pub const PTHREAD_PRIO_NONE: u32 = 0;
pub const PTHREAD_PRIO_INHERIT: u32 = 1;
pub const PTHREAD_PRIO_PROTECT: u32 = 2;
pub const PTHREAD_INHERIT_SCHED: u32 = 0;
pub const PTHREAD_EXPLICIT_SCHED: u32 = 1;
pub const PTHREAD_SCOPE_SYSTEM: u32 = 0;
pub const PTHREAD_SCOPE_PROCESS: u32 = 1;
pub const PTHREAD_PROCESS_PRIVATE: u32 = 0;
pub const PTHREAD_PROCESS_SHARED: u32 = 1;
pub const PTHREAD_ONCE_INIT: u32 = 0;
pub const PTHREAD_CANCEL_ENABLE: u32 = 0;
pub const PTHREAD_CANCEL_DISABLE: u32 = 1;
pub const PTHREAD_CANCEL_MASKED: u32 = 2;
pub const PTHREAD_CANCEL_DEFERRED: u32 = 0;
pub const PTHREAD_CANCEL_ASYNCHRONOUS: u32 = 1;
pub const PTHREAD_BARRIER_SERIAL_THREAD: i32 = -1;
pub const MAX_PRIORITY_NUM: u32 = 200;
pub const HDF_SYSEVENT: u32 = 64222;
pub const HDF_SYSEVENT_CLASS_POWER: u32 = 1;
pub const HDF_SYSEVENT_CLASS_MODULE: u32 = 2;
pub const OSAL_WAIT_FOREVER: u32 = 4294967295;
pub const RTLD_LAZY: u32 = 1;
pub const RTLD_NOW: u32 = 2;
pub const RTLD_NOLOAD: u32 = 4;
pub const RTLD_NODELETE: u32 = 4096;
pub const RTLD_GLOBAL: u32 = 256;
pub const RTLD_LOCAL: u32 = 0;
pub const RTLD_DI_LINKMAP: u32 = 2;
pub const CREATE_INHERIT_DEFAULT: u32 = 1;
pub const CREATE_INHERIT_CURRENT: u32 = 2;
pub const LOCAL_NS_PREFERED: u32 = 4;
pub const NS_NAME_MAX: u32 = 255;
pub const HCS_MATCH_ATTR: &[u8; 11] = b"match_attr\0";
pub const SECUREC_USING_STD_SECURE_LIB: u32 = 0;
pub const SECUREC_DISABLE_CRT_FUNC: u32 = 0;
pub const SECUREC_DISABLE_CRT_IMP: u32 = 0;
pub const SECUREC_IN_KERNEL: u32 = 0;
pub const SECUREC_EXPORT_KERNEL_SYMBOL: u32 = 0;
pub const SECUREC_ENABLE_SCANF_FILE: u32 = 1;
pub const SECUREC_ENABLE_WCHAR_FUNC: u32 = 1;
pub const SECUREC_SNPRINTF_TRUNCATED: u32 = 1;
pub const SECUREC_ENABLE_MEMSET: u32 = 1;
pub const SECUREC_ENABLE_MEMMOVE: u32 = 1;
pub const SECUREC_ENABLE_MEMCPY: u32 = 1;
pub const SECUREC_ENABLE_STRCPY: u32 = 1;
pub const SECUREC_ENABLE_STRNCPY: u32 = 1;
pub const SECUREC_ENABLE_STRCAT: u32 = 1;
pub const SECUREC_ENABLE_STRNCAT: u32 = 1;
pub const SECUREC_ENABLE_SPRINTF: u32 = 1;
pub const SECUREC_ENABLE_VSPRINTF: u32 = 1;
pub const SECUREC_ENABLE_SNPRINTF: u32 = 1;
pub const SECUREC_ENABLE_VSNPRINTF: u32 = 1;
pub const SECUREC_ENABLE_SSCANF: u32 = 1;
pub const SECUREC_ENABLE_VSSCANF: u32 = 1;
pub const SECUREC_ENABLE_SCANF: u32 = 1;
pub const SECUREC_ENABLE_VSCANF: u32 = 1;
pub const SECUREC_ENABLE_FSCANF: u32 = 1;
pub const SECUREC_ENABLE_VFSCANF: u32 = 1;
pub const SECUREC_ENABLE_STRTOK: u32 = 1;
pub const SECUREC_ENABLE_GETS: u32 = 1;
pub const SECUREC_HAVE_STDIO_H: u32 = 1;
pub const SECUREC_HAVE_STRING_H: u32 = 1;
pub const SECUREC_HAVE_STDLIB_H: u32 = 1;
pub const EOF: i32 = -1;
pub const SEEK_SET: u32 = 0;
pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const _IOFBF: u32 = 0;
pub const _IOLBF: u32 = 1;
pub const _IONBF: u32 = 2;
pub const BUFSIZ: u32 = 1024;
pub const FILENAME_MAX: u32 = 4096;
pub const FOPEN_MAX: u32 = 1000;
pub const TMP_MAX: u32 = 10000;
pub const L_tmpnam: u32 = 20;
pub const RENAME_NOREPLACE: u32 = 1;
pub const RENAME_EXCHANGE: u32 = 2;
pub const RENAME_WHITEOUT: u32 = 4;
pub const L_ctermid: u32 = 20;
pub const P_tmpdir: &[u8; 5] = b"/tmp\0";
pub const L_cuserid: u32 = 20;
pub const EXIT_FAILURE: u32 = 1;
pub const EXIT_SUCCESS: u32 = 0;
pub const RAND_MAX: u32 = 2147483647;
pub const WNOHANG: u32 = 1;
pub const WUNTRACED: u32 = 2;
pub const SECUREC_WITH_PERFORMANCE_ADDONS: u32 = 1;
pub const SECUREC_HAVE_STDDEF_H: u32 = 1;
pub const SECUREC_SUPPORT_FORMAT_WARNING: u32 = 0;
pub const SECUREC_SUPPORT_BUILTIN_EXPECT: u32 = 1;
pub const SECUREC_STRING_MAX_LEN: u32 = 2147483647;
pub const SECUREC_MEM_MAX_LEN: u32 = 2147483647;
pub const SECUREC_SUPPORT_STRTOLD: u32 = 0;
pub const SECUREC_HAVE_STDARG_H: u32 = 1;
pub const SECUREC_HAVE_ERRNO_H: u32 = 1;
pub const EPERM: u32 = 1;
pub const ENOENT: u32 = 2;
pub const ESRCH: u32 = 3;
pub const EINTR: u32 = 4;
pub const EIO: u32 = 5;
pub const ENXIO: u32 = 6;
pub const E2BIG: u32 = 7;
pub const ENOEXEC: u32 = 8;
pub const EBADF: u32 = 9;
pub const ECHILD: u32 = 10;
pub const EAGAIN: u32 = 11;
pub const ENOMEM: u32 = 12;
pub const EACCES: u32 = 13;
pub const EFAULT: u32 = 14;
pub const ENOTBLK: u32 = 15;
pub const EBUSY: u32 = 16;
pub const EEXIST: u32 = 17;
pub const EXDEV: u32 = 18;
pub const ENODEV: u32 = 19;
pub const ENOTDIR: u32 = 20;
pub const EISDIR: u32 = 21;
pub const EINVAL: u32 = 22;
pub const ENFILE: u32 = 23;
pub const EMFILE: u32 = 24;
pub const ENOTTY: u32 = 25;
pub const ETXTBSY: u32 = 26;
pub const EFBIG: u32 = 27;
pub const ENOSPC: u32 = 28;
pub const ESPIPE: u32 = 29;
pub const EROFS: u32 = 30;
pub const EMLINK: u32 = 31;
pub const EPIPE: u32 = 32;
pub const EDOM: u32 = 33;
pub const ERANGE: u32 = 34;
pub const EDEADLK: u32 = 35;
pub const ENAMETOOLONG: u32 = 36;
pub const ENOLCK: u32 = 37;
pub const ENOSYS: u32 = 38;
pub const ENOTEMPTY: u32 = 39;
pub const ELOOP: u32 = 40;
pub const EWOULDBLOCK: u32 = 11;
pub const ENOMSG: u32 = 42;
pub const EIDRM: u32 = 43;
pub const ECHRNG: u32 = 44;
pub const EL2NSYNC: u32 = 45;
pub const EL3HLT: u32 = 46;
pub const EL3RST: u32 = 47;
pub const ELNRNG: u32 = 48;
pub const EUNATCH: u32 = 49;
pub const ENOCSI: u32 = 50;
pub const EL2HLT: u32 = 51;
pub const EBADE: u32 = 52;
pub const EBADR: u32 = 53;
pub const EXFULL: u32 = 54;
pub const ENOANO: u32 = 55;
pub const EBADRQC: u32 = 56;
pub const EBADSLT: u32 = 57;
pub const EDEADLOCK: u32 = 35;
pub const EBFONT: u32 = 59;
pub const ENOSTR: u32 = 60;
pub const ENODATA: u32 = 61;
pub const ETIME: u32 = 62;
pub const ENOSR: u32 = 63;
pub const ENONET: u32 = 64;
pub const ENOPKG: u32 = 65;
pub const EREMOTE: u32 = 66;
pub const ENOLINK: u32 = 67;
pub const EADV: u32 = 68;
pub const ESRMNT: u32 = 69;
pub const ECOMM: u32 = 70;
pub const EPROTO: u32 = 71;
pub const EMULTIHOP: u32 = 72;
pub const EDOTDOT: u32 = 73;
pub const EBADMSG: u32 = 74;
pub const EOVERFLOW: u32 = 75;
pub const ENOTUNIQ: u32 = 76;
pub const EBADFD: u32 = 77;
pub const EREMCHG: u32 = 78;
pub const ELIBACC: u32 = 79;
pub const ELIBBAD: u32 = 80;
pub const ELIBSCN: u32 = 81;
pub const ELIBMAX: u32 = 82;
pub const ELIBEXEC: u32 = 83;
pub const EILSEQ: u32 = 84;
pub const ERESTART: u32 = 85;
pub const ESTRPIPE: u32 = 86;
pub const EUSERS: u32 = 87;
pub const ENOTSOCK: u32 = 88;
pub const EDESTADDRREQ: u32 = 89;
pub const EMSGSIZE: u32 = 90;
pub const EPROTOTYPE: u32 = 91;
pub const ENOPROTOOPT: u32 = 92;
pub const EPROTONOSUPPORT: u32 = 93;
pub const ESOCKTNOSUPPORT: u32 = 94;
pub const EOPNOTSUPP: u32 = 95;
pub const ENOTSUP: u32 = 95;
pub const EPFNOSUPPORT: u32 = 96;
pub const EAFNOSUPPORT: u32 = 97;
pub const EADDRINUSE: u32 = 98;
pub const EADDRNOTAVAIL: u32 = 99;
pub const ENETDOWN: u32 = 100;
pub const ENETUNREACH: u32 = 101;
pub const ENETRESET: u32 = 102;
pub const ECONNABORTED: u32 = 103;
pub const ECONNRESET: u32 = 104;
pub const ENOBUFS: u32 = 105;
pub const EISCONN: u32 = 106;
pub const ENOTCONN: u32 = 107;
pub const ESHUTDOWN: u32 = 108;
pub const ETOOMANYREFS: u32 = 109;
pub const ETIMEDOUT: u32 = 110;
pub const ECONNREFUSED: u32 = 111;
pub const EHOSTDOWN: u32 = 112;
pub const EHOSTUNREACH: u32 = 113;
pub const EALREADY: u32 = 114;
pub const EINPROGRESS: u32 = 115;
pub const ESTALE: u32 = 116;
pub const EUCLEAN: u32 = 117;
pub const ENOTNAM: u32 = 118;
pub const ENAVAIL: u32 = 119;
pub const EISNAM: u32 = 120;
pub const EREMOTEIO: u32 = 121;
pub const EDQUOT: u32 = 122;
pub const ENOMEDIUM: u32 = 123;
pub const EMEDIUMTYPE: u32 = 124;
pub const ECANCELED: u32 = 125;
pub const ENOKEY: u32 = 126;
pub const EKEYEXPIRED: u32 = 127;
pub const EKEYREVOKED: u32 = 128;
pub const EKEYREJECTED: u32 = 129;
pub const EOWNERDEAD: u32 = 130;
pub const ENOTRECOVERABLE: u32 = 131;
pub const ERFKILL: u32 = 132;
pub const EHWPOISON: u32 = 133;
pub const EOK: u32 = 0;
pub const EINVAL_AND_RESET: u32 = 150;
pub const ERANGE_AND_RESET: u32 = 162;
pub const EOVERLAP_AND_RESET: u32 = 182;
pub const SECUREC_ONLY_DECLARE_MEMSET: u32 = 0;
pub const LOG_DOMAIN: u32 = 0;
pub const HDF_INVALID_VERSION: u32 = 4294967295;
pub type wchar_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __ll: ::core::ffi::c_longlong,
    pub __ld: f64,
}
pub type size_t = ::core::ffi::c_uint;
pub type intmax_t = ::core::ffi::c_longlong;
pub type uintmax_t = ::core::ffi::c_ulonglong;
pub type int_fast8_t = i8;
pub type int_fast64_t = i64;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast64_t = u64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast16_t = i32;
pub type int_fast32_t = i32;
pub type uint_fast16_t = u32;
pub type uint_fast32_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __locale_struct {
    _unused: [u8; 0],
}
pub type locale_t = *mut __locale_struct;
pub const HDF_SUCCESS: HDF_STATUS = 0;
pub const HDF_FAILURE: HDF_STATUS = -1;
pub const HDF_ERR_NOT_SUPPORT: HDF_STATUS = -2;
pub const HDF_ERR_INVALID_PARAM: HDF_STATUS = -3;
pub const HDF_ERR_INVALID_OBJECT: HDF_STATUS = -4;
pub const HDF_ERR_MALLOC_FAIL: HDF_STATUS = -6;
pub const HDF_ERR_TIMEOUT: HDF_STATUS = -7;
pub const HDF_ERR_THREAD_CREATE_FAIL: HDF_STATUS = -10;
pub const HDF_ERR_QUEUE_FULL: HDF_STATUS = -15;
pub const HDF_ERR_DEVICE_BUSY: HDF_STATUS = -16;
pub const HDF_ERR_IO: HDF_STATUS = -17;
pub const HDF_ERR_BAD_FD: HDF_STATUS = -18;
pub const HDF_ERR_NOPERM: HDF_STATUS = -19;
pub const HDF_ERR_OUT_OF_RANGE: HDF_STATUS = -20;
pub const HDF_BSP_ERR_OP: HDF_STATUS = -101;
pub const HDF_ERR_BSP_PLT_API_ERR: HDF_STATUS = -102;
pub const HDF_PAL_ERR_DEV_CREATE: HDF_STATUS = -103;
pub const HDF_PAL_ERR_INNER: HDF_STATUS = -104;
pub const HDF_DEV_ERR_NO_MEMORY: HDF_STATUS = -201;
pub const HDF_DEV_ERR_NO_DEVICE: HDF_STATUS = -202;
pub const HDF_DEV_ERR_NO_DEVICE_SERVICE: HDF_STATUS = -203;
pub const HDF_DEV_ERR_DEV_INIT_FAIL: HDF_STATUS = -204;
pub const HDF_DEV_ERR_PUBLISH_FAIL: HDF_STATUS = -205;
pub const HDF_DEV_ERR_ATTACHDEV_FAIL: HDF_STATUS = -206;
pub const HDF_DEV_ERR_NODATA: HDF_STATUS = -207;
pub const HDF_DEV_ERR_NORANGE: HDF_STATUS = -208;
pub const HDF_DEV_ERR_OP: HDF_STATUS = -210;
pub const HDF_DEV_ERR_NETDOWN: HDF_STATUS = -211;
pub type HDF_STATUS = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObject {
    pub objectId: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DListHead {
    pub next: *mut DListHead,
    pub prev: *mut DListHead,
}
pub type devid_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IHdfDevice {
    pub object: HdfObject,
    pub Attach: ::core::option::Option<
        unsafe extern "C" fn(
            device: *mut IHdfDevice,
            deviceNode: *mut HdfDeviceNode,
        ) -> ::core::ffi::c_int,
    >,
    pub Detach: ::core::option::Option<
        unsafe extern "C" fn(
            device: *mut IHdfDevice,
            deviceNode: *mut HdfDeviceNode,
        ) -> ::core::ffi::c_int,
    >,
    pub GetDeviceNode: ::core::option::Option<
        unsafe extern "C" fn(device: *mut IHdfDevice, devid: devid_t) -> *mut HdfDeviceNode,
    >,
    pub DetachWithDevid: ::core::option::Option<
        unsafe extern "C" fn(device: *mut IHdfDevice, devid: devid_t) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDevice {
    pub super_: IHdfDevice,
    pub node: DListHead,
    pub devNodes: DListHead,
    pub deviceId: devid_t,
    pub devidIndex: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IHdfDeviceToken {
    pub object: HdfObject,
    pub devid: devid_t,
    pub servName: *const ::core::ffi::c_char,
    pub deviceName: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSListNode {
    pub next: *mut HdfSListNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSList {
    pub root: *mut HdfSListNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSListIterator {
    pub stepOnNext: ::core::ffi::c_int,
    pub prev: *mut HdfSListNode,
    pub curr: *mut HdfSListNode,
}
pub type HdfSListDeleter = ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSListNode)>;
pub type HdfSListSearchComparer =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSListNode, arg2: u32) -> bool>;
pub type HdfSListAddComparer = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut HdfSListNode, arg2: *mut HdfSListNode) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceToken {
    pub super_: IHdfDeviceToken,
    pub node: HdfSListNode,
}
pub const DEVICE_CLASS_DEFAULT: DeviceClass = 1;
pub const DEVICE_CLASS_PLAT: DeviceClass = 2;
pub const DEVICE_CLASS_SENSOR: DeviceClass = 4;
pub const DEVICE_CLASS_INPUT: DeviceClass = 8;
pub const DEVICE_CLASS_DISPLAY: DeviceClass = 16;
pub const DEVICE_CLASS_AUDIO: DeviceClass = 32;
pub const DEVICE_CLASS_CAMERA: DeviceClass = 64;
pub const DEVICE_CLASS_USB: DeviceClass = 128;
pub const DEVICE_CLASS_USERAUTH: DeviceClass = 256;
pub const DEVICE_CLASS_HIMEDIACOMM: DeviceClass = 512;
pub const DEVICE_CLASS_MAX: DeviceClass = 1024;
pub type DeviceClass = ::core::ffi::c_uint;
pub type char16_t = u16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBuf {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBufImpl {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfRemoteService {
    _unused: [u8; 0],
}
pub const SBUF_RAW: HdfSbufType = 0;
pub const SBUF_IPC: HdfSbufType = 1;
pub const SBUF_IPC_HW: HdfSbufType = 2;
pub const SBUF_TYPE_MAX: HdfSbufType = 3;
pub type HdfSbufType = ::core::ffi::c_uint;
pub type OnEventReceived = ::core::option::Option<
    unsafe extern "C" fn(
        priv_: *mut ::core::ffi::c_void,
        id: u32,
        data: *mut HdfSBuf,
    ) -> ::core::ffi::c_int,
>;
pub type OnDevEventReceive = ::core::option::Option<
    unsafe extern "C" fn(
        listener: *mut HdfDevEventlistener,
        service: *mut HdfIoService,
        id: u32,
        data: *mut HdfSBuf,
    ) -> ::core::ffi::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDevEventlistener {
    pub callBack: OnEventReceived,
    pub onReceive: OnDevEventReceive,
    pub listNode: DListHead,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoDispatcher {
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            service: *mut HdfObject,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoService {
    pub object: HdfObject,
    pub target: *mut HdfObject,
    pub dispatcher: *mut HdfIoDispatcher,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoServiceGroup {
    pub object: HdfObject,
}
pub type time_t = ::core::ffi::c_longlong;
pub type clockid_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: time_t,
    pub tv_nsec: ::core::ffi::c_long,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
}
impl timespec {
    #[inline]
    pub fn new_bitfield_1() -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __pthread {
    _unused: [u8; 0],
}
pub type pthread_t = *mut __pthread;
pub type pthread_once_t = ::core::ffi::c_int;
pub type pthread_key_t = ::core::ffi::c_uint;
pub type pthread_spinlock_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutexattr_t {
    pub __attr: ::core::ffi::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_condattr_t {
    pub __attr: ::core::ffi::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_barrierattr_t {
    pub __attr: ::core::ffi::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlockattr_t {
    pub __attr: [::core::ffi::c_uint; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sigset_t {
    pub __bits: [::core::ffi::c_ulong; 32usize],
}
pub type sigset_t = __sigset_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_attr_t {
    pub __u: pthread_attr_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_attr_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 9usize],
    pub __vi: [::core::ffi::c_int; 9usize],
    pub __s: [::core::ffi::c_ulong; 9usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_mutex_t {
    pub __u: pthread_mutex_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_mutex_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 6usize],
    pub __vi: [::core::ffi::c_int; 6usize],
    pub __p: [*mut ::core::ffi::c_void; 6usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_cond_t {
    pub __u: pthread_cond_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_cond_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 12usize],
    pub __vi: [::core::ffi::c_int; 12usize],
    pub __p: [*mut ::core::ffi::c_void; 12usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_rwlock_t {
    pub __u: pthread_rwlock_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_rwlock_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 8usize],
    pub __vi: [::core::ffi::c_int; 8usize],
    pub __p: [*mut ::core::ffi::c_void; 8usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_barrier_t {
    pub __u: pthread_barrier_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_barrier_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 5usize],
    pub __vi: [::core::ffi::c_int; 5usize],
    pub __p: [*mut ::core::ffi::c_void; 5usize],
}
pub type pid_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sched_param {
    pub sched_priority: ::core::ffi::c_int,
    pub __reserved1: ::core::ffi::c_int,
    pub __reserved2: [::core::ffi::c_long; 4usize],
    pub __reserved3: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cpu_set_t {
    pub __bits: [::core::ffi::c_ulong; 32usize],
}
pub type timer_t = *mut ::core::ffi::c_void;
pub type clock_t = ::core::ffi::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tm {
    pub tm_sec: ::core::ffi::c_int,
    pub tm_min: ::core::ffi::c_int,
    pub tm_hour: ::core::ffi::c_int,
    pub tm_mday: ::core::ffi::c_int,
    pub tm_mon: ::core::ffi::c_int,
    pub tm_year: ::core::ffi::c_int,
    pub tm_wday: ::core::ffi::c_int,
    pub tm_yday: ::core::ffi::c_int,
    pub tm_isdst: ::core::ffi::c_int,
    pub tm_gmtoff: ::core::ffi::c_long,
    pub tm_zone: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct itimerspec {
    pub it_interval: timespec,
    pub it_value: timespec,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sigevent {
    _unused: [u8; 0],
}
extern "C" {
}
extern "C" {
    pub static mut daylight: ::core::ffi::c_int;
}
extern "C" {
    pub static mut timezone: ::core::ffi::c_long;
}
extern "C" {
    pub static mut getdate_err: ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __ptcb {
    pub __f: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>,
    pub __x: *mut ::core::ffi::c_void,
    pub __next: *mut __ptcb,
}
pub const SERVICE_POLICY_NONE: ServicePolicy = 0;
pub const SERVICE_POLICY_PUBLIC: ServicePolicy = 1;
pub const SERVICE_POLICY_CAPACITY: ServicePolicy = 2;
pub const SERVICE_POLICY_FRIENDLY: ServicePolicy = 3;
pub const SERVICE_POLICY_PRIVATE: ServicePolicy = 4;
pub const SERVICE_POLICY_INVALID: ServicePolicy = 5;
pub type ServicePolicy = ::core::ffi::c_uint;
pub const DEVICE_PRELOAD_ENABLE: DevicePreload = 0;
pub const DEVICE_PRELOAD_ENABLE_STEP2: DevicePreload = 1;
pub const DEVICE_PRELOAD_DISABLE: DevicePreload = 2;
pub const DEVICE_PRELOAD_INVALID: DevicePreload = 3;
pub type DevicePreload = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct HdfDeviceObject {
    pub service: *mut IDeviceIoService,
    pub property: *const DeviceResourceNode,
    pub deviceClass: DeviceClass,
    pub priv_: *mut ::core::ffi::c_void,
    pub mutex: pthread_rwlock_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceIoClient {
    pub device: *mut HdfDeviceObject,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDeviceIoService {
    pub object: HdfObject,
    pub Open: ::core::option::Option<unsafe extern "C" fn(client: *mut HdfDeviceIoClient) -> i32>,
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            client: *mut HdfDeviceIoClient,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> i32,
    >,
    pub Release: ::core::option::Option<unsafe extern "C" fn(client: *mut HdfDeviceIoClient)>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SubscriberCallback {
    pub deviceObject: *mut HdfDeviceObject,
    pub OnServiceConnected: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject, service: *const HdfObject) -> i32,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDriverEntry {
    pub moduleVersion: i32,
    pub moduleName: *const ::core::ffi::c_char,
    pub Bind:
        ::core::option::Option<unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> i32>,
    pub Init:
        ::core::option::Option<unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> i32>,
    pub Release: ::core::option::Option<unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject)>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalMutex {
    pub realMutex: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfServiceObserver {
    pub services: HdfSList,
    pub observerMutex: OsalMutex,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfServiceObserverRecord {
    pub entry: HdfSListNode,
    pub serviceKey: u32,
    pub policy: u16,
    pub devId: devid_t,
    pub obsRecMutex: OsalMutex,
    pub subscribers: HdfSList,
    pub publisher: *mut HdfObject,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalAtomic {
    pub counter: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IHdfSRefListener {
    pub OnFirstAcquire: ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSRef)>,
    pub OnLastRelease: ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSRef)>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSRef {
    pub refs: OsalAtomic,
    pub listener: *mut IHdfSRefListener,
    pub Acquire: ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSRef)>,
    pub Release: ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfSRef)>,
    pub Count:
        ::core::option::Option<unsafe extern "C" fn(arg1: *const HdfSRef) -> ::core::ffi::c_int>,
}
pub const PSM_STATE_IDLE: HdfPsmState = 0;
pub const PSM_STATE_ACTIVE: HdfPsmState = 1;
pub const PSM_STATE_INACTIVE: HdfPsmState = 2;
pub type HdfPsmState = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IPowerStateToken {
    pub AcquireWakeLock: ::core::option::Option<unsafe extern "C" fn(arg1: *mut IPowerStateToken)>,
    pub ReleaseWakeLock: ::core::option::Option<unsafe extern "C" fn(arg1: *mut IPowerStateToken)>,
}
pub const KEVENT_POWER_SUSPEND: PowerKeventId = 0;
pub const KEVENT_POWER_DISPLAY_OFF: PowerKeventId = 1;
pub const KEVENT_POWER_RESUME: PowerKeventId = 2;
pub const KEVENT_POWER_DISPLAY_ON: PowerKeventId = 3;
pub const KEVENT_POWER_EVENT_MAX: PowerKeventId = 4;
pub type PowerKeventId = ::core::ffi::c_uint;
pub const KEVENT_MODULE_INSTALL: DriverModuleKeventId = 0;
pub const KEVENT_MODULE_REMOVE: DriverModuleKeventId = 1;
pub const KEVENT_MODULE_EVENT_MAX: DriverModuleKeventId = 2;
pub type DriverModuleKeventId = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSysEvent {
    pub eventClass: u64,
    pub syncToken: u64,
    pub eventid: u32,
    pub reserved: u32,
}
pub type HdfSysEventNotifierFn = ::core::option::Option<
    unsafe extern "C" fn(
        self_: *mut HdfSysEventNotifyNode,
        eventClass: u64,
        event: u32,
        content: *const ::core::ffi::c_char,
    ) -> i32,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSysEventNotifyNode {
    pub callback: HdfSysEventNotifierFn,
    pub listNode: DListHead,
    pub classFilter: u64,
}
pub const HDF_POWER_SYS_CTRL: PowerManagementMode = 0;
pub const HDF_POWER_DYNAMIC_CTRL: PowerManagementMode = 1;
pub const HDF_POWER_MODE_MAX: PowerManagementMode = 2;
pub type PowerManagementMode = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IPowerEventListener {
    pub DozeResume: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> ::core::ffi::c_int,
    >,
    pub DozeSuspend: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> ::core::ffi::c_int,
    >,
    pub Resume: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> ::core::ffi::c_int,
    >,
    pub Suspend: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PowerStateToken {
    pub super_: IPowerStateToken,
    pub listener: *const IPowerEventListener,
    pub deviceObject: *mut HdfDeviceObject,
    pub wakeRef: HdfSRef,
    pub psmState: HdfPsmState,
    pub mode: u32,
}
pub const SERVIE_STATUS_START: ServiceStatusType = 0;
pub const SERVIE_STATUS_CHANGE: ServiceStatusType = 1;
pub const SERVIE_STATUS_STOP: ServiceStatusType = 2;
pub const SERVIE_STATUS_REGISTER: ServiceStatusType = 3;
pub const SERVIE_STATUS_MAX: ServiceStatusType = 4;
pub type ServiceStatusType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServiceStatus {
    pub serviceName: *const ::core::ffi::c_char,
    pub deviceClass: u16,
    pub status: u16,
    pub info: *const ::core::ffi::c_char,
}
pub type OnServiceStatusReceived = ::core::option::Option<
    unsafe extern "C" fn(listener: *mut ServiceStatusListener, status: *mut ServiceStatus),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServiceStatusListener {
    pub callback: OnServiceStatusReceived,
    pub priv_: *mut ::core::ffi::c_void,
}
pub const SERVIE_STATUS_LISTENER_NOTIFY: ServiceStatusListenerCmd = 0;
pub const SERVIE_STATUS_LISTENER_MAX: ServiceStatusListenerCmd = 1;
pub type ServiceStatusListenerCmd = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServStatListenerHolder {
    pub listenClass: u16,
    pub node: DListHead,
    pub index: u64,
    pub NotifyStatus: ::core::option::Option<
        unsafe extern "C" fn(
            holder: *mut ServStatListenerHolder,
            status: *mut ServiceStatus,
        ) -> i32,
    >,
    pub Recycle: ::core::option::Option<unsafe extern "C" fn(holder: *mut ServStatListenerHolder)>,
}
pub const HDF_SERVICE_UNUSABLE: _bindgen_ty_1 = 0;
pub const HDF_SERVICE_USABLE: _bindgen_ty_1 = 1;
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const HDF_DEV_LOCAL_SERVICE: _bindgen_ty_2 = 0;
pub const HDF_DEV_REMOTE_SERVICE: _bindgen_ty_2 = 1;
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceInfo {
    pub node: HdfSListNode,
    pub isDynamic: bool,
    pub status: u16,
    pub deviceType: u16,
    pub deviceId: u32,
    pub policy: u16,
    pub priority: u16,
    pub preload: u16,
    pub permission: u16,
    pub moduleName: *const ::core::ffi::c_char,
    pub svcName: *const ::core::ffi::c_char,
    pub deviceMatchAttr: *const ::core::ffi::c_char,
    pub deviceName: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfPrivateInfo {
    pub length: u32,
    pub data: *const ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDriver {
    pub entry: *const HdfDriverEntry,
    pub type_: u16,
    pub bus: u16,
    pub node: DListHead,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDeviceNode {
    pub object: HdfObject,
    pub PublishService: ::core::option::Option<
        unsafe extern "C" fn(devNode: *mut HdfDeviceNode) -> ::core::ffi::c_int,
    >,
    pub RemoveService: ::core::option::Option<
        unsafe extern "C" fn(devNode: *mut HdfDeviceNode) -> ::core::ffi::c_int,
    >,
    pub LaunchNode: ::core::option::Option<
        unsafe extern "C" fn(devNode: *mut HdfDeviceNode) -> ::core::ffi::c_int,
    >,
    pub UnlaunchNode: ::core::option::Option<unsafe extern "C" fn(devNode: *mut HdfDeviceNode)>,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct HdfDeviceNode {
    pub super_: IDeviceNode,
    pub entry: DListHead,
    pub powerToken: *mut PowerStateToken,
    pub hostService: *mut DevHostService,
    pub deviceObject: HdfDeviceObject,
    pub token: *mut IHdfDeviceToken,
    pub driver: *mut HdfDriver,
    pub device: *mut HdfDevice,
    pub servName: *mut ::core::ffi::c_char,
    pub servInfo: *const ::core::ffi::c_char,
    pub driverName: *mut ::core::ffi::c_char,
    pub devId: devid_t,
    pub policy: u16,
    pub permission: u16,
    pub devStatus: u8,
    pub servStatus: bool,
    pub interfaceDesc: *mut ::core::ffi::c_char,
}
pub const DEVNODE_NONE: DevNodeStaus = 0;
pub const DEVNODE_INITED: DevNodeStaus = 1;
pub const DEVNODE_LAUNCHED: DevNodeStaus = 2;
pub type DevNodeStaus = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfServiceInfo {
    pub servName: *const ::core::ffi::c_char,
    pub servInfo: *const ::core::ffi::c_char,
    pub devClass: u16,
    pub devId: devid_t,
    pub interfaceDesc: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDevSvcManager {
    pub object: HdfObject,
    pub StartService: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevSvcManager) -> ::core::ffi::c_int,
    >,
    pub AddService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut HdfDeviceObject,
            arg3: *const HdfServiceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub UpdateService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut HdfDeviceObject,
            arg3: *const HdfServiceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub SubscribeService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: SubscriberCallback,
        ) -> ::core::ffi::c_int,
    >,
    pub UnsubscribeService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub GetService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> *mut HdfObject,
    >,
    pub GetObject: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> *mut HdfDeviceObject,
    >,
    pub RemoveService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: *const HdfDeviceObject,
        ),
    >,
    pub RegsterServListener: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut ServStatListenerHolder,
        ) -> ::core::ffi::c_int,
    >,
    pub UnregsterServListener: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevSvcManager, arg2: *mut ServStatListenerHolder),
    >,
    pub ListAllService:
        ::core::option::Option<unsafe extern "C" fn(arg1: *mut IDevSvcManager, arg2: *mut HdfSBuf)>,
    pub ListServiceByInterfaceDesc: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevSvcManagerClnt {
    pub devSvcMgrIf: *mut IDevSvcManager,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDevHostService {
    pub object: HdfObject,
    pub AddDevice: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            devInfo: *const HdfDeviceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub DelDevice: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            devId: devid_t,
        ) -> ::core::ffi::c_int,
    >,
    pub StartService: ::core::option::Option<
        unsafe extern "C" fn(hostService: *mut IDevHostService) -> ::core::ffi::c_int,
    >,
    pub PmNotify: ::core::option::Option<
        unsafe extern "C" fn(service: *mut IDevHostService, powerState: u32) -> ::core::ffi::c_int,
    >,
    pub Dump: ::core::option::Option<
        unsafe extern "C" fn(
            hostService: *mut IDevHostService,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
pub const POWER_STATE_DOZE_RESUME: HdfPowerState = 0;
pub const POWER_STATE_DOZE_SUSPEND: HdfPowerState = 1;
pub const POWER_STATE_RESUME: HdfPowerState = 2;
pub const POWER_STATE_SUSPEND: HdfPowerState = 3;
pub const POWER_STATE_MAX: HdfPowerState = 4;
pub type HdfPowerState = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct IDevmgrService {
    pub base: HdfObject,
    pub object: HdfDeviceObject,
    pub AttachDeviceHost: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            arg2: u16,
            arg3: *mut IDevHostService,
        ) -> ::core::ffi::c_int,
    >,
    pub AttachDevice: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            arg2: *mut IHdfDeviceToken,
        ) -> ::core::ffi::c_int,
    >,
    pub DetachDevice: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevmgrService, arg2: devid_t) -> ::core::ffi::c_int,
    >,
    pub LoadDevice: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            arg2: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub UnloadDevice: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            arg2: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub StartService: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevmgrService) -> ::core::ffi::c_int,
    >,
    pub PowerStateChange: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevmgrService,
            pEvent: HdfPowerState,
        ) -> ::core::ffi::c_int,
    >,
    pub ListAllDevice: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevmgrService, arg2: *mut HdfSBuf) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevmgrServiceClnt {
    pub devMgrSvcIf: *mut IDevmgrService,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfServiceSubscriber {
    pub entry: HdfSListNode,
    pub state: u32,
    pub devId: u32,
    pub callback: SubscriberCallback,
}
pub const HDF_SUBSCRIBER_STATE_PENDING: _bindgen_ty_3 = 0;
pub const HDF_SUBSCRIBER_STATE_READY: _bindgen_ty_3 = 1;
pub type _bindgen_ty_3 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalSem {
    pub realSemaphore: *mut ::core::ffi::c_void,
}
pub const OSAL_THREAD_PRI_LOW: OSAL_THREAD_PRIORITY = 0;
pub const OSAL_THREAD_PRI_DEFAULT: OSAL_THREAD_PRIORITY = 1;
pub const OSAL_THREAD_PRI_HIGH: OSAL_THREAD_PRIORITY = 2;
pub const OSAL_THREAD_PRI_HIGHEST: OSAL_THREAD_PRIORITY = 3;
pub type OSAL_THREAD_PRIORITY = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalThreadParam {
    pub name: *mut ::core::ffi::c_char,
    pub stackSize: size_t,
    pub priority: OSAL_THREAD_PRIORITY,
    pub policy: ::core::ffi::c_int,
}
pub type OsalThreadEntry = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void) -> ::core::ffi::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalThread {
    pub realThread: *mut ::core::ffi::c_void,
}
pub type HdfTaskFunc = ::core::option::Option<unsafe extern "C" fn(para: *mut HdfTaskType) -> i32>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfTaskType {
    pub node: DListHead,
    pub func: HdfTaskFunc,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfTaskQueue {
    pub sem: OsalSem,
    pub mutex: OsalMutex,
    pub head: DListHead,
    pub thread: OsalThread,
    pub threadRunFlag: bool,
    pub queueFunc: HdfTaskFunc,
    pub queueName: *const ::core::ffi::c_char,
}
pub const HDF_PM_REQUEST_ACQUIRE: HDF_PM_REQUEST_TYPE = 0;
pub const HDF_PM_REQUEST_RELEASE: HDF_PM_REQUEST_TYPE = 1;
pub type HDF_PM_REQUEST_TYPE = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfPmRequest {
    pub token: *mut PowerStateToken,
    pub pmType: HDF_PM_REQUEST_TYPE,
    pub task: HdfTaskType,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PmTaskQueue {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDriverLoader {
    pub object: HdfObject,
    pub GetDriver: ::core::option::Option<
        unsafe extern "C" fn(driverName: *const ::core::ffi::c_char) -> *mut HdfDriver,
    >,
    pub ReclaimDriver: ::core::option::Option<unsafe extern "C" fn(driver: *mut HdfDriver)>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDriverLoader {
    pub super_: IDriverLoader,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevHostService {
    pub super_: IDevHostService,
    pub hostId: u16,
    pub hostName: *const ::core::ffi::c_char,
    pub devices: DListHead,
    pub observer: HdfServiceObserver,
    pub sysEventNotifyNode: HdfSysEventNotifyNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MapNode {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Map {
    pub nodes: *mut *mut MapNode,
    pub nodeSize: u32,
    pub bucketSize: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevHostServiceClnt {
    pub node: DListHead,
    pub devices: HdfSList,
    pub unloadDevInfos: HdfSList,
    pub dynamicDevInfos: HdfSList,
    pub deviceHashMap: *mut Map,
    pub hostService: *mut IDevHostService,
    pub hostLock: OsalMutex,
    pub devCount: u16,
    pub hostId: u16,
    pub hostPid: ::core::ffi::c_int,
    pub hostName: *const ::core::ffi::c_char,
    pub stopFlag: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dl_namespace {
    pub name: [::core::ffi::c_char; 256usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dl_info {
    pub dli_fname: *const ::core::ffi::c_char,
    pub dli_fbase: *mut ::core::ffi::c_void,
    pub dli_sname: *const ::core::ffi::c_char,
    pub dli_saddr: *mut ::core::ffi::c_void,
}
pub const HDF_CONFIG_SOURCE: DeviceResourceType = 0;
pub const INVALID: DeviceResourceType = 1;
pub type DeviceResourceType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceAttr {
    pub name: *const ::core::ffi::c_char,
    pub value: *const ::core::ffi::c_char,
    pub next: *mut DeviceResourceAttr,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceNode {
    pub name: *const ::core::ffi::c_char,
    pub hashValue: u32,
    pub attrData: *mut DeviceResourceAttr,
    pub parent: *mut DeviceResourceNode,
    pub child: *mut DeviceResourceNode,
    pub sibling: *mut DeviceResourceNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceIface {
    pub GetRootNode: ::core::option::Option<unsafe extern "C" fn() -> *const DeviceResourceNode>,
    pub GetBool: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
        ) -> bool,
    >,
    pub GetUint8: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u8,
            def: u8,
        ) -> i32,
    >,
    pub GetUint8ArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut u8,
            def: u8,
        ) -> i32,
    >,
    pub GetUint8Array: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u8,
            len: u32,
            def: u8,
        ) -> i32,
    >,
    pub GetUint16: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u16,
            def: u16,
        ) -> i32,
    >,
    pub GetUint16ArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut u16,
            def: u16,
        ) -> i32,
    >,
    pub GetUint16Array: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u16,
            len: u32,
            def: u16,
        ) -> i32,
    >,
    pub GetUint32: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u32,
            def: u32,
        ) -> i32,
    >,
    pub GetUint32ArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut u32,
            def: u32,
        ) -> i32,
    >,
    pub GetUint32Array: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u32,
            len: u32,
            def: u32,
        ) -> i32,
    >,
    pub GetUint64: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u64,
            def: u64,
        ) -> i32,
    >,
    pub GetUint64ArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut u64,
            def: u64,
        ) -> i32,
    >,
    pub GetUint64Array: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut u64,
            len: u32,
            def: u64,
        ) -> i32,
    >,
    pub GetString: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            value: *mut *const ::core::ffi::c_char,
            def: *const ::core::ffi::c_char,
        ) -> i32,
    >,
    pub GetStringArrayElem: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
            index: u32,
            value: *mut *const ::core::ffi::c_char,
            def: *const ::core::ffi::c_char,
        ) -> i32,
    >,
    pub GetElemNum: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
        ) -> i32,
    >,
    pub GetNodeByMatchAttr: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrValue: *const ::core::ffi::c_char,
        ) -> *const DeviceResourceNode,
    >,
    pub GetChildNode: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            nodeName: *const ::core::ffi::c_char,
        ) -> *const DeviceResourceNode,
    >,
    pub GetNodeByRefAttr: ::core::option::Option<
        unsafe extern "C" fn(
            node: *const DeviceResourceNode,
            attrName: *const ::core::ffi::c_char,
        ) -> *const DeviceResourceNode,
    >,
}
#[repr(C)]
#[derive(Debug)]
pub struct HdfCString {
    pub size: ::core::ffi::c_int,
    pub value: __IncompleteArrayField<::core::ffi::c_char>,
}
pub type ssize_t = ::core::ffi::c_int;
pub type off_t = ::core::ffi::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    _unused: [u8; 0],
}
pub type FILE = _IO_FILE;
pub type va_list = u32;
pub type __isoc_va_list = u32;
#[repr(C)]
#[derive(Copy, Clone)]
pub union _G_fpos64_t {
    pub __opaque: [::core::ffi::c_char; 16usize],
    pub __lldata: ::core::ffi::c_longlong,
    pub __align: f64,
}
pub type fpos_t = _G_fpos64_t;
extern "C" {
}
extern "C" {
}
extern "C" {
}
pub type cookie_read_function_t = ::core::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::core::ffi::c_void,
        arg2: *mut ::core::ffi::c_char,
        arg3: size_t,
    ) -> ssize_t,
>;
pub type cookie_write_function_t = ::core::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::core::ffi::c_void,
        arg2: *const ::core::ffi::c_char,
        arg3: size_t,
    ) -> ssize_t,
>;
pub type cookie_seek_function_t = ::core::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::core::ffi::c_void,
        arg2: *mut off_t,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int,
>;
pub type cookie_close_function_t = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void) -> ::core::ffi::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_cookie_io_functions_t {
    pub read: cookie_read_function_t,
    pub write: cookie_write_function_t,
    pub seek: cookie_seek_function_t,
    pub close: cookie_close_function_t,
}
pub type cookie_io_functions_t = _IO_cookie_io_functions_t;
pub const FDSAN_OWNER_TYPE_DEFAULT: fdsan_owner_type = 0;
pub const FDSAN_OWNER_TYPE_MAX: fdsan_owner_type = 255;
pub const FDSAN_OWNER_TYPE_FILE: fdsan_owner_type = 1;
pub const FDSAN_OWNER_TYPE_DIRECTORY: fdsan_owner_type = 2;
pub const FDSAN_OWNER_TYPE_UNIQUE_FD: fdsan_owner_type = 3;
pub const FDSAN_OWNER_TYPE_ZIP_ARCHIVE: fdsan_owner_type = 4;
pub type fdsan_owner_type = ::core::ffi::c_uint;
pub const FDSAN_ERROR_LEVEL_DISABLED: fdsan_error_level = 0;
pub const FDSAN_ERROR_LEVEL_WARN_ONCE: fdsan_error_level = 1;
pub const FDSAN_ERROR_LEVEL_WARN_ALWAYS: fdsan_error_level = 2;
pub const FDSAN_ERROR_LEVEL_FATAL: fdsan_error_level = 3;
pub type fdsan_error_level = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct div_t {
    pub quot: ::core::ffi::c_int,
    pub rem: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ldiv_t {
    pub quot: ::core::ffi::c_long,
    pub rem: ::core::ffi::c_long,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lldiv_t {
    pub quot: ::core::ffi::c_longlong,
    pub rem: ::core::ffi::c_longlong,
}
extern "C" {
}
extern "C" {
}
pub type errno_t = ::core::ffi::c_int;
pub const HDF_OBJECT_ID_DEVMGR_SERVICE: _bindgen_ty_4 = 0;
pub const HDF_OBJECT_ID_DEVSVC_MANAGER: _bindgen_ty_4 = 1;
pub const HDF_OBJECT_ID_DEVHOST_SERVICE: _bindgen_ty_4 = 2;
pub const HDF_OBJECT_ID_DRIVER_INSTALLER: _bindgen_ty_4 = 3;
pub const HDF_OBJECT_ID_DRIVER_LOADER: _bindgen_ty_4 = 4;
pub const HDF_OBJECT_ID_DEVICE: _bindgen_ty_4 = 5;
pub const HDF_OBJECT_ID_DEVICE_TOKEN: _bindgen_ty_4 = 6;
pub const HDF_OBJECT_ID_DEVICE_SERVICE: _bindgen_ty_4 = 7;
pub const HDF_OBJECT_ID_REMOTE_SERVICE: _bindgen_ty_4 = 8;
pub const HDF_OBJECT_ID_MAX: _bindgen_ty_4 = 9;
pub type _bindgen_ty_4 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObjectCreator {
    pub Create: ::core::option::Option<unsafe extern "C" fn() -> *mut HdfObject>,
    pub Release: ::core::option::Option<unsafe extern "C" fn(arg1: *mut HdfObject)>,
}
pub const LOG_TYPE_MIN: LogType = 0;
pub const LOG_APP: LogType = 0;
pub const LOG_INIT: LogType = 1;
pub const LOG_CORE: LogType = 3;
pub const LOG_KMSG: LogType = 4;
pub const LOG_ONLY_PRERELEASE: LogType = 5;
pub const LOG_TYPE_MAX: LogType = 6;
pub type LogType = ::core::ffi::c_uint;
pub const LOG_LEVEL_MIN: LogLevel = 0;
pub const LOG_DEBUG: LogLevel = 3;
pub const LOG_INFO: LogLevel = 4;
pub const LOG_WARN: LogLevel = 5;
pub const LOG_ERROR: LogLevel = 6;
pub const LOG_FATAL: LogLevel = 7;
pub const LOG_LEVEL_MAX: LogLevel = 8;
pub type LogLevel = ::core::ffi::c_uint;
pub type LogCallback = ::core::option::Option<
    unsafe extern "C" fn(
        type_: LogType,
        level: LogLevel,
        domain: ::core::ffi::c_uint,
        tag: *const ::core::ffi::c_char,
        msg: *const ::core::ffi::c_char,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfVdiBase {
    pub moduleVersion: u32,
    pub moduleName: *const ::core::ffi::c_char,
    pub CreateVdiInstance: ::core::option::Option<
        unsafe extern "C" fn(vdiBase: *mut HdfVdiBase) -> ::core::ffi::c_int,
    >,
    pub DestoryVdiInstance: ::core::option::Option<
        unsafe extern "C" fn(vdiBase: *mut HdfVdiBase) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfVdiObject {
    pub dlHandler: usize,
    pub vdiBase: *mut HdfVdiBase,
}

// ============================================================
// Auto-generated Defensive Opaque Types
// These types were found in function signatures or variable
// declarations but were not generated by bindgen.
// ============================================================

/// Opaque placeholder for external type `clock_getres`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clock_getres {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `clock_gettime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clock_gettime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `clock_nanosleep`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clock_nanosleep {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `clock_settime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clock_settime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `ctime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ctime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `ctime_r`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ctime_r {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `difftime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct difftime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `gmtime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gmtime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `gmtime_r`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gmtime_r {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `localtime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct localtime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `localtime_r`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct localtime_r {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `mktime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mktime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `nanosleep`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nanosleep {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_cond_timedwait`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_cond_timedwait {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_mutex_timedlock`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutex_timedlock {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_rwlock_timedrdlock`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlock_timedrdlock {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_rwlock_timedwrlock`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlock_timedwrlock {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `pthread_timedjoin_np`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_timedjoin_np {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `sched_rr_get_interval`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sched_rr_get_interval {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `stime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct stime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `time`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct time {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `timegm`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timegm {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `timer_gettime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timer_gettime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `timer_settime`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timer_settime {
    _private: [u8; 0],
}

/// Opaque placeholder for external type `timespec_get`
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec_get {
    _private: [u8; 0],
}

// ============================================================
// Common Constants (自动追加)
// ============================================================

pub const TRUE: i32 = 1;
pub const FALSE: i32 = 0;
pub const SOFTBUS_OK: i32 = 0;
pub const SOFTBUS_ERR: i32 = -1;
pub const SOFTBUS_NOT_IMPLEMENT: i32 = -2;
pub const SOFTBUS_INVALID_PARAM: i32 = -3;
pub const SOFTBUS_MEM_ERR: i32 = -4;
pub const SOFTBUS_MALLOC_ERR: i32 = -5;
pub const SOFTBUS_PERMISSION_DENIED: i32 = -6;
pub const SOFTBUS_NETWORK_ERR: i32 = -7;
pub const LOS_OK: i32 = 0;
pub const LOS_NOK: i32 = -1;
pub const LOS_ERRNO_BASE: u32 = 0x02000000;
pub const AUDIO_FORMAT_TYPE_PCM_16_BIT: i32 = 1;
pub const AUDIO_FORMAT_TYPE_PCM_8_BIT: i32 = 0;
pub const AUDIO_FORMAT_TYPE_PCM_24_BIT: i32 = 2;
pub const AUDIO_FORMAT_TYPE_PCM_32_BIT: i32 = 3;
