/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub static APP_GALLERY: [::core::ffi::c_char; 12usize];
}
unsafe extern "C" {
    pub static ENTERPRISE: [::core::ffi::c_char; 11usize];
}
unsafe extern "C" {
    pub static ENTERPRISE_NORMAL: [::core::ffi::c_char; 18usize];
}
unsafe extern "C" {
    pub static ENTERPRISE_MDM: [::core::ffi::c_char; 15usize];
}
unsafe extern "C" {
    pub static OS_INTEGRATION: [::core::ffi::c_char; 15usize];
}
unsafe extern "C" {
    pub static INTERNALTESTING: [::core::ffi::c_char; 16usize];
}
