/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub static g_trustAppList: [TrustAppCert; 3usize];
}
unsafe extern "C" {
    pub static g_trustAppListTest: [TrustAppCert; 2usize];
}
pub const g_isDebugMode: bool = false;
pub const g_isActsMode: bool = false;
