/* automatically generated by rust-bindgen 0.72.1 */

pub type pthread_spinlock_t = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn pthread_spin_init(
        arg1: *mut pthread_spinlock_t,
        arg2: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pthread_spin_destroy(arg1: *mut pthread_spinlock_t) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pthread_spin_lock(arg1: *mut pthread_spinlock_t) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pthread_spin_unlock(arg1: *mut pthread_spinlock_t) -> ::core::ffi::c_int;
}
pub const LOG_TYPE_MIN: LogType = 0;
pub const LOG_APP: LogType = 0;
pub const LOG_INIT: LogType = 1;
pub const LOG_CORE: LogType = 3;
pub const LOG_KMSG: LogType = 4;
pub const LOG_ONLY_PRERELEASE: LogType = 5;
pub const LOG_TYPE_MAX: LogType = 6;
pub type LogType = ::core::ffi::c_uint;
pub const LOG_LEVEL_MIN: LogLevel = 0;
pub const LOG_DEBUG: LogLevel = 3;
pub const LOG_INFO: LogLevel = 4;
pub const LOG_WARN: LogLevel = 5;
pub const LOG_ERROR: LogLevel = 6;
pub const LOG_FATAL: LogLevel = 7;
pub const LOG_LEVEL_MAX: LogLevel = 8;
pub type LogLevel = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn HiLogPrint(
        type_: LogType,
        level: LogLevel,
        domain: ::core::ffi::c_uint,
        tag: *const ::core::ffi::c_char,
        fmt: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
}
