/* automatically generated by rust-bindgen 0.72.1 */

pub type size_t = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn __errno_location() -> *mut ::core::ffi::c_int;
}
pub type time_t = ::core::ffi::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: time_t,
    pub tv_nsec: ::core::ffi::c_long,
}
pub type clockid_t = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn nanosleep(arg1: *const timespec, arg2: *mut timespec) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn clock_gettime(arg1: clockid_t, arg2: *mut timespec) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[link_name = "\u{1}__nanosleep_time64"]
    pub fn nanosleep1(arg1: *const timespec, arg2: *mut timespec) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[link_name = "\u{1}__clock_gettime64"]
    pub fn clock_gettime1(arg1: clockid_t, arg2: *mut timespec) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn sleep(arg1: ::core::ffi::c_uint) -> ::core::ffi::c_uint;
}
pub type errno_t = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn memset_s(
        dest: *mut ::core::ffi::c_void,
        destMax: size_t,
        c: ::core::ffi::c_int,
        count: size_t,
    ) -> errno_t;
}
pub const LOG_TYPE_MIN: LogType = 0;
pub const LOG_APP: LogType = 0;
pub const LOG_INIT: LogType = 1;
pub const LOG_CORE: LogType = 3;
pub const LOG_KMSG: LogType = 4;
pub const LOG_ONLY_PRERELEASE: LogType = 5;
pub const LOG_TYPE_MAX: LogType = 6;
pub type LogType = ::core::ffi::c_uint;
pub const LOG_LEVEL_MIN: LogLevel = 0;
pub const LOG_DEBUG: LogLevel = 3;
pub const LOG_INFO: LogLevel = 4;
pub const LOG_WARN: LogLevel = 5;
pub const LOG_ERROR: LogLevel = 6;
pub const LOG_FATAL: LogLevel = 7;
pub const LOG_LEVEL_MAX: LogLevel = 8;
pub type LogLevel = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn HiLogPrint(
        type_: LogType,
        level: LogLevel,
        domain: ::core::ffi::c_uint,
        tag: *const ::core::ffi::c_char,
        fmt: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
}
