/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn AudioFillConfigData(
        device: *const HdfDeviceObject,
        configData: *mut AudioConfigData,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioGetRegConfig(
        device: *const HdfDeviceObject,
        configData: *mut AudioRegCfgData,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioGetPortConfig(
        device: *const HdfDeviceObject,
        configData: *mut AudioPortInfo,
    ) -> i32;
}
