/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn AudioCodecRegUpdate(codec: *mut CodecDevice, mixerCtrl: *mut AudioMixerControl) -> i32;
}
unsafe extern "C" {
    pub fn AudioDaiRegUpdate(dai: *const DaiDevice, mixerCtrl: *mut AudioMixerControl) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecMuxRegUpdate(
        codec: *mut CodecDevice,
        enumCtrl: *mut AudioEnumKcontrol,
        value: *const u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioSocRegisterPlatform(
        device: *mut HdfDeviceObject,
        platformData: *mut PlatformData,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioSocRegisterDai(device: *mut HdfDeviceObject, daiData: *mut DaiData) -> i32;
}
unsafe extern "C" {
    pub fn AudioRegisterDsp(
        device: *mut HdfDeviceObject,
        dspData: *mut DspData,
        DaiData: *mut DaiData,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioRegisterCodec(
        device: *mut HdfDeviceObject,
        codecData: *mut CodecData,
        daiData: *mut DaiData,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioBindDaiLink(audioCard: *mut AudioCard, configData: *const AudioConfigData) -> i32;
}
unsafe extern "C" {
    pub fn AudioUpdateCodecRegBits(
        codec: *mut CodecDevice,
        reg: u32,
        mask: u32,
        shift: u32,
        value: u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioUpdateDaiRegBits(
        dai: *const DaiDevice,
        reg: u32,
        mask: u32,
        shift: u32,
        value: u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioKcontrolGetCpuDai(kcontrol: *const AudioKcontrol) -> *mut DaiDevice;
}
unsafe extern "C" {
    pub fn AudioKcontrolGetCodec(kcontrol: *const AudioKcontrol) -> *mut CodecDevice;
}
unsafe extern "C" {
    pub fn AudioAddControls(
        audioCard: *mut AudioCard,
        controls: *const AudioKcontrol,
        controlMaxNum: i32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioAddControl(
        audioCard: *const AudioCard,
        ctl: *const AudioKcontrol,
    ) -> *mut AudioKcontrol;
}
unsafe extern "C" {
    pub fn AudioGetCtrlOpsRReg(
        elemValue: *mut AudioCtrlElemValue,
        mixerCtrl: *const AudioMixerControl,
        rcurValue: u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioGetCtrlOpsReg(
        elemValue: *mut AudioCtrlElemValue,
        mixerCtrl: *const AudioMixerControl,
        curValue: u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioSetCtrlOpsReg(
        kcontrol: *const AudioKcontrol,
        elemValue: *const AudioCtrlElemValue,
        mixerCtrl: *const AudioMixerControl,
        value: *mut u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioSetCtrlOpsRReg(
        elemValue: *const AudioCtrlElemValue,
        mixerCtrl: *mut AudioMixerControl,
        rvalue: *mut u32,
        updateRReg: *mut bool,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioDaiReadReg(dai: *const DaiDevice, reg: u32, val: *mut u32) -> i32;
}
unsafe extern "C" {
    pub fn AudioDaiWriteReg(dai: *const DaiDevice, reg: u32, val: u32) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecReadReg(codec: *const CodecDevice, reg: u32, val: *mut u32) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecWriteReg(codec: *const CodecDevice, reg: u32, val: u32) -> i32;
}
unsafe extern "C" {
    pub fn AudioInfoCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemInfo: *mut AudioCtrlElemInfo,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecGetCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *mut AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecSetCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *const AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioInfoEnumCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemInfo: *mut AudioCtrlElemInfo,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecGetEnumCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *mut AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecSetEnumCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *const AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCpuDaiSetCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *const AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCpuDaiGetCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *mut AudioCtrlElemValue,
    ) -> i32;
}
