/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn swap(a: *mut ::core::ffi::c_int, b: *mut ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn partition(
        arr: *mut ::core::ffi::c_int,
        low: ::core::ffi::c_int,
        high: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn quickSort(
        arr: *mut ::core::ffi::c_int,
        low: ::core::ffi::c_int,
        high: ::core::ffi::c_int,
    );
}
