/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServiceStatus {
    pub serviceName: *const ::core::ffi::c_char,
    pub deviceClass: u16,
    pub status: u16,
    pub info: *const ::core::ffi::c_char,
}
pub type OnServiceStatusReceived = ::core::option::Option<
    unsafe extern "C" fn(listener: *mut ServiceStatusListener, status: *mut ServiceStatus),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServiceStatusListener {
    pub callback: OnServiceStatusReceived,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ISvcMgrIoservice {
    pub RegisterServiceStatusListener: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *mut ISvcMgrIoservice,
            listener: *mut ServiceStatusListener,
            deviceClass: u16,
        ) -> i32,
    >,
    pub UnregisterServiceStatusListener: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *mut ISvcMgrIoservice,
            listener: *mut ServiceStatusListener,
        ) -> i32,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DListHead {
    pub next: *mut DListHead,
    pub prev: *mut DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObject {
    pub objectId: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBuf {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoDispatcher {
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            service: *mut HdfObject,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoService {
    pub object: HdfObject,
    pub target: *mut HdfObject,
    pub dispatcher: *mut HdfIoDispatcher,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SvcMgrIoservice {
    pub svcmgr: ISvcMgrIoservice,
    pub iosvc: *mut HdfIoService,
    pub listeners: DListHead,
}
