//! Compatibility / Fallback Layer
//!
//! This module is auto-generated to keep the translated project compiling.
//!
//! Design goals:
//! - Centralize placeholders and shims in ONE place (easy to audit & remove later).
//! - Keep function bodies as close to translated semantics as possible.
//!
//! IMPORTANT:
//! - Items here may be placeholders (value/layout unknown). Always review before relying on semantics.

#![allow(dead_code)]
#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]

/// Minimal FFI prelude (for legacy skeletons that import `crate::compat::ffi::*`).
pub mod ffi {
    pub use core::ffi::*;
}

// === C2R_COMPAT_PLACEHOLDERS_BEGIN ===
// (auto-appended placeholders will be inserted here)
// === C2R_COMPAT_PLACEHOLDERS_END ===

// === C2R_EXTERN_VARS_BEGIN ===
// Auto-generated by C2R step 2.56 (bindgen allowlist vars/consts).
// Source: archived_runs/deepseek-v4-pro-ohos10-full-0613-1/raw/framework_output/intermediate/core__ef5242b7ab08/workspace/.preprocessed/*.i (preprocessed translation units)
// Details: archived_runs/deepseek-v4-pro-ohos10-full-0613-1/raw/framework_output/intermediate/core__ef5242b7ab08/workspace/repair_history/core__ef5242b7ab08/translate_by_qwen3_coder/_manual_fix/extern_vars_from_bindgen_allowlist.json
use crate::types::{FILE};

#[allow(improper_ctypes)]
#[allow(non_snake_case)]
extern "C" {
    pub static stderr: *mut crate::types::FILE;
}

// === C2R_EXTERN_VARS_END ===

// === C2R_EXTERN_DECLS_BEGIN ===
// Auto-generated extern decls (C2R step 2.55; bindgen allowlist).
// Source: archived_runs/deepseek-v4-pro-ohos10-full-0613-1/raw/framework_output/intermediate/core__ef5242b7ab08/workspace/.preprocessed/*.i (preprocessed translation units)
// Details: archived_runs/deepseek-v4-pro-ohos10-full-0613-1/raw/framework_output/intermediate/core__ef5242b7ab08/workspace/repair_history/core__ef5242b7ab08/translate_by_qwen3_coder/_manual_fix/extern_decls_from_bindgen_allowlist.json
#[allow(improper_ctypes)]
#[allow(non_snake_case)]
extern "C" {
    pub fn DeviceResourceGetIfaceInstance(type_: crate::types::DeviceResourceType) -> *mut crate::types::DeviceResourceIface;
    pub fn HdfDeviceSetClass(deviceObject: *mut crate::types::HdfDeviceObject, deviceClass: crate::types::DeviceClass) -> bool;
    pub fn HiLogPrint(type_: crate::types::LogType, level: crate::types::LogLevel, domain: ::core::ffi::c_uint, tag: *const ::core::ffi::c_char, fmt: *const ::core::ffi::c_char, ...) -> ::core::ffi::c_int;
    pub fn OsalIoUnmap(addr: *mut ::core::ffi::c_void);
    pub fn OsalMemCalloc(size: crate::types::size_t) -> *mut ::core::ffi::c_void;
    pub fn OsalMemFree(mem: *mut ::core::ffi::c_void);
    pub fn OsalMutexLock(mutex: *mut crate::types::OsalMutex) -> i32;
    pub fn OsalMutexUnlock(mutex: *mut crate::types::OsalMutex) -> i32;
    pub fn memcpy_s(dest: *mut ::core::ffi::c_void, destMax: crate::types::size_t, src: *const ::core::ffi::c_void, count: crate::types::size_t) -> crate::types::errno_t;
    pub fn memset_s(dest: *mut ::core::ffi::c_void, destMax: crate::types::size_t, c: ::core::ffi::c_int, count: crate::types::size_t) -> crate::types::errno_t;
    pub fn strcmp(arg1: *const ::core::ffi::c_char, arg2: *const ::core::ffi::c_char) -> ::core::ffi::c_int;
}
// === C2R_EXTERN_DECLS_END ===

// === C2R_ACCESSOR_SHIMS_BEGIN ===
// (auto-appended accessor shim declarations will be inserted here)
// === C2R_ACCESSOR_SHIMS_END ===
