/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn AudioSapmNewComponents(
        audioCard: *mut AudioCard,
        component: *const AudioSapmComponent,
        cptMaxNum: i32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioSapmAddRoutes(
        audioCard: *mut AudioCard,
        route: *const AudioSapmRoute,
        routeMaxNum: i32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioSapmNewControls(audioCard: *mut AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioSapmSleep(audioCard: *mut AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioSampPowerUp(card: *const AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioSampSetPowerMonitor(card: *mut AudioCard, powerMonitorState: bool) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecSapmSetCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *const AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecSapmGetCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *mut AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecSapmSetEnumCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *const AudioCtrlElemValue,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCodecSapmGetEnumCtrlOps(
        kcontrol: *const AudioKcontrol,
        elemValue: *mut AudioCtrlElemValue,
    ) -> i32;
}
