/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DListHead {
    pub next: *mut DListHead,
    pub prev: *mut DListHead,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServiceStatus {
    pub serviceName: *const ::core::ffi::c_char,
    pub deviceClass: u16,
    pub status: u16,
    pub info: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSBuf {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServStatListenerHolder {
    pub listenClass: u16,
    pub node: DListHead,
    pub index: u64,
    pub NotifyStatus: ::core::option::Option<
        unsafe extern "C" fn(
            holder: *mut ServStatListenerHolder,
            status: *mut ServiceStatus,
        ) -> i32,
    >,
    pub Recycle: ::core::option::Option<unsafe extern "C" fn(holder: *mut ServStatListenerHolder)>,
}
pub const DEVICE_CLASS_DEFAULT: DeviceClass = 1;
pub const DEVICE_CLASS_PLAT: DeviceClass = 2;
pub const DEVICE_CLASS_SENSOR: DeviceClass = 4;
pub const DEVICE_CLASS_INPUT: DeviceClass = 8;
pub const DEVICE_CLASS_DISPLAY: DeviceClass = 16;
pub const DEVICE_CLASS_AUDIO: DeviceClass = 32;
pub const DEVICE_CLASS_CAMERA: DeviceClass = 64;
pub const DEVICE_CLASS_USB: DeviceClass = 128;
pub const DEVICE_CLASS_USERAUTH: DeviceClass = 256;
pub const DEVICE_CLASS_HIMEDIACOMM: DeviceClass = 512;
pub const DEVICE_CLASS_MAX: DeviceClass = 1024;
pub type DeviceClass = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfObject {
    pub objectId: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoDispatcher {
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            service: *mut HdfObject,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfIoService {
    pub object: HdfObject,
    pub target: *mut HdfObject,
    pub dispatcher: *mut HdfIoDispatcher,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pthread_rwlock_t {
    pub __u: pthread_rwlock_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union pthread_rwlock_t__bindgen_ty_1 {
    pub __i: [::core::ffi::c_int; 14usize],
    pub __vi: [::core::ffi::c_int; 14usize],
    pub __p: [*mut ::core::ffi::c_void; 7usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct HdfDeviceObject {
    pub service: *mut IDeviceIoService,
    pub property: *mut DeviceResourceNode,
    pub deviceClass: DeviceClass,
    pub priv_: *mut ::core::ffi::c_void,
    pub mutex: pthread_rwlock_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfDeviceIoClient {
    pub device: *mut HdfDeviceObject,
    pub priv_: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDeviceIoService {
    pub object: HdfObject,
    pub Open: ::core::option::Option<unsafe extern "C" fn(client: *mut HdfDeviceIoClient) -> i32>,
    pub Dispatch: ::core::option::Option<
        unsafe extern "C" fn(
            client: *mut HdfDeviceIoClient,
            cmdId: ::core::ffi::c_int,
            data: *mut HdfSBuf,
            reply: *mut HdfSBuf,
        ) -> i32,
    >,
    pub Release: ::core::option::Option<unsafe extern "C" fn(client: *mut HdfDeviceIoClient)>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SubscriberCallback {
    pub deviceObject: *mut HdfDeviceObject,
    pub OnServiceConnected: ::core::option::Option<
        unsafe extern "C" fn(deviceObject: *mut HdfDeviceObject, service: *const HdfObject) -> i32,
    >,
}
pub type devid_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSListNode {
    pub next: *mut HdfSListNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfSList {
    pub root: *mut HdfSListNode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfServiceInfo {
    pub servName: *const ::core::ffi::c_char,
    pub servInfo: *const ::core::ffi::c_char,
    pub devClass: u16,
    pub devId: devid_t,
    pub interfaceDesc: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IDevSvcManager {
    pub object: HdfObject,
    pub StartService: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevSvcManager) -> ::core::ffi::c_int,
    >,
    pub AddService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut HdfDeviceObject,
            arg3: *const HdfServiceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub UpdateService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut HdfDeviceObject,
            arg3: *const HdfServiceInfo,
        ) -> ::core::ffi::c_int,
    >,
    pub SubscribeService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: SubscriberCallback,
        ) -> ::core::ffi::c_int,
    >,
    pub UnsubscribeService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub GetService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> *mut HdfObject,
    >,
    pub GetObject: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
        ) -> *mut HdfDeviceObject,
    >,
    pub RemoveService: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: *const HdfDeviceObject,
        ),
    >,
    pub RegsterServListener: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *mut ServStatListenerHolder,
        ) -> ::core::ffi::c_int,
    >,
    pub UnregsterServListener: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut IDevSvcManager, arg2: *mut ServStatListenerHolder),
    >,
    pub ListAllService:
        ::core::option::Option<unsafe extern "C" fn(arg1: *mut IDevSvcManager, arg2: *mut HdfSBuf)>,
    pub ListServiceByInterfaceDesc: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut IDevSvcManager,
            arg2: *const ::core::ffi::c_char,
            arg3: *mut HdfSBuf,
        ) -> ::core::ffi::c_int,
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OsalMutex {
    pub realMutex: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HdfServiceObserver {
    pub services: HdfSList,
    pub observerMutex: OsalMutex,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevSvcManager {
    pub super_: IDevSvcManager,
    pub services: DListHead,
    pub observer: HdfServiceObserver,
    pub svcstatListeners: DListHead,
    pub mutex: OsalMutex,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DevSvcManagerExt {
    pub super_: DevSvcManager,
    pub ioService: IDeviceIoService,
    pub serv: *mut HdfIoService,
    pub mutex: OsalMutex,
    pub started: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DeviceResourceNode {
    pub _address: u8,
}
