/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn OsalSleep(sec: u32);
}
unsafe extern "C" {
    pub fn OsalMSleep(ms: u32);
}
unsafe extern "C" {
    pub fn OsalUSleep(us: u32);
}
unsafe extern "C" {
    pub fn OsalGetTime(time: *mut OsalTimespec) -> i32;
}
unsafe extern "C" {
    pub fn OsalDiffTime(
        start: *const OsalTimespec,
        end: *const OsalTimespec,
        diff: *mut OsalTimespec,
    ) -> i32;
}
unsafe extern "C" {
    pub fn OsalGetSysTimeMs() -> u64;
}
unsafe extern "C" {
    pub fn OsalMDelay(ms: u32);
}
unsafe extern "C" {
    pub fn OsalUDelay(us: u32);
}
