/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn OsalSemInit(sem: *mut OsalSem, value: u32) -> i32;
}
unsafe extern "C" {
    pub fn OsalSemWait(sem: *mut OsalSem, ms: u32) -> i32;
}
unsafe extern "C" {
    pub fn OsalSemPost(sem: *mut OsalSem) -> i32;
}
unsafe extern "C" {
    pub fn OsalSemDestroy(sem: *mut OsalSem) -> i32;
}
