/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn OsalThreadCreate(
        thread: *mut OsalThread,
        threadEntry: OsalThreadEntry,
        entryPara: *mut ::core::ffi::c_void,
    ) -> i32;
}
unsafe extern "C" {
    pub fn OsalThreadStart(thread: *mut OsalThread, param: *const OsalThreadParam) -> i32;
}
unsafe extern "C" {
    pub fn OsalThreadDestroy(thread: *mut OsalThread) -> i32;
}
