/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn OsalSpinInit(spinlock: *mut OsalSpinlock) -> i32;
}
unsafe extern "C" {
    pub fn OsalSpinDestroy(spinlock: *mut OsalSpinlock) -> i32;
}
unsafe extern "C" {
    pub fn OsalSpinLock(spinlock: *mut OsalSpinlock) -> i32;
}
unsafe extern "C" {
    pub fn OsalSpinUnlock(spinlock: *mut OsalSpinlock) -> i32;
}
