/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn CodecGetServiceName(
        device: *const HdfDeviceObject,
        drvCodecName: *mut *const ::core::ffi::c_char,
    ) -> i32;
}
unsafe extern "C" {
    pub fn CodecGetDaiName(
        device: *const HdfDeviceObject,
        drvDaiName: *mut *const ::core::ffi::c_char,
    ) -> i32;
}
unsafe extern "C" {
    pub fn CodecGetConfigInfo(device: *const HdfDeviceObject, codecData: *mut CodecData) -> i32;
}
unsafe extern "C" {
    pub fn CodecDaiGetPortConfigInfo(
        device: *const HdfDeviceObject,
        codecData: *mut DaiData,
    ) -> i32;
}
unsafe extern "C" {
    pub fn CodecSetConfigInfoOfControls(codeData: *mut CodecData, daiData: *mut DaiData) -> i32;
}
unsafe extern "C" {
    pub fn CodecSetCtlFunc(
        codeData: *mut CodecData,
        controlType: AudioControlType,
        getCtrl: *const ::core::ffi::c_void,
        setCtrl: *const ::core::ffi::c_void,
    ) -> i32;
}
unsafe extern "C" {
    pub fn CodecDeviceReadReg(codec: *const CodecDevice, reg: u32, value: *mut u32) -> i32;
}
unsafe extern "C" {
    pub fn CodecDeviceWriteReg(codec: *const CodecDevice, reg: u32, value: u32) -> i32;
}
unsafe extern "C" {
    pub fn CodecDaiRegI2cRead(dai: *const DaiDevice, reg: u32, value: *mut u32) -> i32;
}
unsafe extern "C" {
    pub fn CodecDaiRegI2cWrite(dai: *const DaiDevice, reg: u32, value: u32) -> i32;
}
unsafe extern "C" {
    pub fn CodecDeviceRegI2cRead(codec: *const CodecDevice, reg: u32, value: *mut u32) -> i32;
}
unsafe extern "C" {
    pub fn CodecDeviceRegI2cWrite(codec: *const CodecDevice, reg: u32, value: u32) -> i32;
}
unsafe extern "C" {
    pub fn CodecDeviceInitRegConfig(device: *const CodecDevice) -> i32;
}
unsafe extern "C" {
    pub fn CodecDaiDeviceStartupRegConfig(device: *const DaiDevice) -> i32;
}
