/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DspGetServiceName(
        device: *const HdfDeviceObject,
        drvDspName: *mut *const ::core::ffi::c_char,
    ) -> i32;
}
unsafe extern "C" {
    pub fn DspGetDaiName(
        device: *const HdfDeviceObject,
        drvDaiName: *mut *const ::core::ffi::c_char,
    ) -> i32;
}
