/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn SysReadl(addr: ::core::ffi::c_ulong) -> u32;
}
unsafe extern "C" {
    pub fn SysWritel(addr: ::core::ffi::c_ulong, value: u32);
}
unsafe extern "C" {
    pub fn PlatformDataFromCard(card: *const AudioCard) -> *mut PlatformData;
}
unsafe extern "C" {
    pub fn AudioBytesToFrames(frameBits: u32, size: u32) -> u32;
}
unsafe extern "C" {
    pub fn AudioDataBigEndianChange(
        srcData: *mut ::core::ffi::c_char,
        audioLen: u32,
        bitWidth: DataBitWidth,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioFormatToBitWidth(format: AudioFormat, bitWidth: *mut u32) -> i32;
}
unsafe extern "C" {
    pub fn AudioSetPcmInfo(platformData: *mut PlatformData, param: *const AudioPcmHwParams) -> i32;
}
unsafe extern "C" {
    pub fn AudioSetRenderBufInfo(data: *mut PlatformData, param: *const AudioPcmHwParams) -> i32;
}
unsafe extern "C" {
    pub fn AudioSetCaptureBufInfo(data: *mut PlatformData, param: *const AudioPcmHwParams) -> i32;
}
unsafe extern "C" {
    pub fn AudioPcmWrite(card: *const AudioCard, txData: *mut AudioTxData) -> i32;
}
unsafe extern "C" {
    pub fn AudioPcmRead(card: *const AudioCard, rxData: *mut AudioRxData) -> i32;
}
unsafe extern "C" {
    pub fn AudioPcmMmapWrite(card: *const AudioCard, txMmapData: *const AudioMmapData) -> i32;
}
unsafe extern "C" {
    pub fn AudioPcmMmapRead(card: *const AudioCard, rxMmapData: *const AudioMmapData) -> i32;
}
unsafe extern "C" {
    pub fn AudioRenderOpen(card: *const AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioCaptureOpen(card: *const AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioRenderClose(card: *const AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioPcmPointer(
        card: *const AudioCard,
        pointer: *mut u32,
        streamType: AudioStreamType,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioCaptureClose(card: *const AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioHwParams(card: *const AudioCard, param: *const AudioPcmHwParams) -> i32;
}
unsafe extern "C" {
    pub fn AudioRenderPrepare(card: *const AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioCapturePrepare(card: *const AudioCard) -> i32;
}
unsafe extern "C" {
    pub fn AudioRenderTrigger(card: *mut AudioCard, cmd: i32) -> i32;
}
unsafe extern "C" {
    pub fn AudioCaptureTrigger(card: *mut AudioCard, cmd: i32) -> i32;
}
unsafe extern "C" {
    pub fn AudioCapSilenceThresholdEvent(
        device: *mut HdfDeviceObject,
        reportMsg: *const AudioEvent,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioMmapReadTransfer(card: *const AudioCard, rxMmapData: *const AudioMmapData) -> i32;
}
