/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn DaiDataFromCard(card: *const AudioCard) -> *mut DaiData;
}
unsafe extern "C" {
    pub fn DaiGetConfigInfo(device: *const HdfDeviceObject, data: *mut DaiData) -> i32;
}
unsafe extern "C" {
    pub fn DaiCheckSampleRate(sampleRates: u32) -> i32;
}
unsafe extern "C" {
    pub fn DaiSetConfigInfoOfControls(data: *mut DaiData) -> i32;
}
unsafe extern "C" {
    pub fn DaiDeviceReadReg(dai: *const DaiDevice, reg: u32, val: *mut u32) -> i32;
}
unsafe extern "C" {
    pub fn DaiDeviceWriteReg(dai: *const DaiDevice, reg: u32, value: u32) -> i32;
}
