/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn AudioDmaBufAlloc(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaBufFree(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaRequestChannel(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaConfigChannel(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaPrep(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaSubmit(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaPending(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaPause(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaResume(data: *mut PlatformData, streamType: AudioStreamType) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaPointer(
        data: *mut PlatformData,
        streamType: AudioStreamType,
        pointer: *mut u32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaGetConfigInfo(device: *const HdfDeviceObject, data: *mut PlatformData) -> i32;
}
unsafe extern "C" {
    pub fn AudioDmaTransferStatusIsNormal(
        data: *mut PlatformData,
        streamType: AudioStreamType,
    ) -> bool;
}
